Repository scylladb/scylla-operator, pull requests merged in 2021-08, with the labels that each got.

#735 Add coredns rollout status checking to github actions
  .github/actions/setup-minikube/action.yaml
Labels: kind/flake, priority/important-soon

#739 Fix webhookserver PDB name
  deploy/operator/10_pdb.yaml
  deploy/operator/10_webhookserver.pdb.yaml
  examples/common/operator.yaml
  hack/ci-deploy.sh
  helm/scylla-operator/templates/webhookserver.pdb.yaml
Labels: kind/bug, priority/important-soon

#741 Explicitly set Scylla's metrics listen IP
  pkg/sidecar/config/config.go
Labels: kind/cleanup, priority/important-soon

#744 [v1.3] Fix minikube install 1.3
  .github/actions/setup-minikube/action.yaml
Labels: kind/machinery

#748 Tag Helm Charts with tagged versions
  Makefile
Labels: kind/machinery

#751 Promote v1.4 documentation and update release info
  docs/source/conf.py
  docs/source/releases.md
Labels: priority/important-soon, kind/documentation

#723 Add e2e webhook tests
  test/e2e/set/scyllacluster/scyllacluster_webhooks.go
Labels: kind/feature, priority/important-soon

#753 Handle PRs with multiple "kind/" labels in release notes
  pkg/cmd/releasenotes/releasenotes.go
  pkg/cmd/releasenotes/render.go
  pkg/cmd/releasenotes/render_test.go
Labels: priority/important-soon, kind/machinery

#692 Enhance e2e tests with writing and reading data
  go.mod
  go.sum
  test/e2e/set/scyllacluster/datainserter.go
  test/e2e/set/scyllacluster/helpers.go
  test/e2e/set/scyllacluster/scyllacluster_auth.go
  test/e2e/set/scyllacluster/scyllacluster_evictions.go
  test/e2e/set/scyllacluster/scyllacluster_pv.go
  test/e2e/set/scyllacluster/scyllacluster_replace.go
  test/e2e/set/scyllacluster/scyllacluster_scaling.go
  test/e2e/set/scyllacluster/scyllacluster_sysctl.go
  test/e2e/set/scyllacluster/scyllacluster_upgrades.go
  test/e2e/set/scyllacluster/scyllacluster_webhooks.go
  test/e2e/set/scyllacluster/scyllamanager.go
  test/e2e/set/scyllacluster/verify.go
  vendor/github.com/scylladb/go-reflectx/.golangci.yml
  vendor/github.com/scylladb/go-reflectx/.travis.yml
  vendor/github.com/scylladb/go-reflectx/LICENSE
  vendor/github.com/scylladb/go-reflectx/Makefile
  vendor/github.com/scylladb/go-reflectx/README.md
  vendor/github.com/scylladb/go-reflectx/reflect.go
  vendor/github.com/scylladb/go-reflectx/transform.go
  vendor/github.com/scylladb/gocqlx/v2/.gitignore
  vendor/github.com/scylladb/gocqlx/v2/.golangci.yml
  vendor/github.com/scylladb/gocqlx/v2/LICENSE
  vendor/github.com/scylladb/gocqlx/v2/Makefile
  vendor/github.com/scylladb/gocqlx/v2/README.md
  vendor/github.com/scylladb/gocqlx/v2/doc.go
  vendor/github.com/scylladb/gocqlx/v2/go.mod
  vendor/github.com/scylladb/gocqlx/v2/go.sum
  vendor/github.com/scylladb/gocqlx/v2/gocqlx.go
  vendor/github.com/scylladb/gocqlx/v2/iterx.go
  vendor/github.com/scylladb/gocqlx/v2/mapper.go
  vendor/github.com/scylladb/gocqlx/v2/qb/README.md
  vendor/github.com/scylladb/gocqlx/v2/qb/batch.go
  vendor/github.com/scylladb/gocqlx/v2/qb/cmp.go
  vendor/github.com/scylladb/gocqlx/v2/qb/delete.go
  vendor/github.com/scylladb/gocqlx/v2/qb/doc.go
  vendor/github.com/scylladb/gocqlx/v2/qb/func.go
  vendor/github.com/scylladb/gocqlx/v2/qb/insert.go
  vendor/github.com/scylladb/gocqlx/v2/qb/qb.go
  vendor/github.com/scylladb/gocqlx/v2/qb/select.go
  vendor/github.com/scylladb/gocqlx/v2/qb/token.go
  vendor/github.com/scylladb/gocqlx/v2/qb/update.go
  vendor/github.com/scylladb/gocqlx/v2/qb/using.go
  vendor/github.com/scylladb/gocqlx/v2/qb/utils.go
  vendor/github.com/scylladb/gocqlx/v2/qb/value.go
  vendor/github.com/scylladb/gocqlx/v2/queryx.go
  vendor/github.com/scylladb/gocqlx/v2/queryx_wrap.go
  vendor/github.com/scylladb/gocqlx/v2/session.go
  vendor/github.com/scylladb/gocqlx/v2/table/doc.go
  vendor/github.com/scylladb/gocqlx/v2/table/table.go
  vendor/github.com/scylladb/gocqlx/v2/udt.go
  vendor/modules.txt
Labels: kind/feature, priority/important-longterm

#761 Revert "Hide master from documentation version dropdown"
  docs/source/conf.py
Labels: priority/important-soon, kind/machinery

#752 allow overrides for helm scylla-operator replicas
  helm/scylla-operator/templates/operator.deployment.yaml
  helm/scylla-operator/templates/operator.pdb.yaml
  helm/scylla-operator/templates/webhookserver.deployment.yaml
  helm/scylla-operator/templates/webhookserver.pdb.yaml
  helm/scylla-operator/values.yaml
Labels: kind/feature

#740 Add automatic update of CRD schemas in helm charts' schemas
  .github/workflows/go.yaml
  Makefile
  helm/scylla-manager/values.schema.json
  helm/scylla-manager/values.schema.template.json
  helm/scylla/values.schema.json
Labels: kind/feature, priority/important-soon

#766 Fix backup.rateLimit type in CRD example
  docs/source/scylla_cluster_crd.md
Labels: priority/important-soon, kind/documentation
