Repository scylladb/scylla-operator, pull requests merged in 2021-12, with the labels that each got.

#864 Operator upgrade guide
  docs/source/upgrade.md
Labels: kind/documentation

#870 Mark v1.6 as stable documentation
  docs/source/conf.py
Labels: kind/documentation

#871 Bump release schedule
  docs/source/releases.md
Labels: kind/documentation

#873 Don't act on scylla pods that are being deleted in nodeconfigpod controller
  pkg/controller/nodeconfigpod/sync.go
Labels: kind/bug, priority/critical-urgent

#872 Performance tuning documentation
  docs/source/index.rst
  docs/source/performance.md
Labels: kind/documentation

#877 Reword the performance documentation
  docs/source/performance.md
Labels: kind/documentation

#878 [v1.6] Add performance documentation
  docs/source/index.rst
  docs/source/performance.md
Labels: kind/documentation

#879 [v1.6] Don't act on scylla pods that are being deleted
  pkg/controller/nodeconfigpod/sync.go
Labels: kind/bug, priority/critical-urgent

#880 Bump minikube to v1.24
  .github/actions/setup-minikube/action.yaml
Labels: priority/important-soon, kind/machinery

#889 Account for image pull times when determining in e2e timeouts
  test/e2e/utils/config.go
  test/e2e/utils/helpers.go
Labels: kind/flake, priority/critical-urgent

#882 Fix ownerRefs for nodeconfigpod controller
  pkg/controller/nodeconfigpod/controller.go
  pkg/controller/nodeconfigpod/resource_test.go
  pkg/resourceapply/apps.go
  pkg/resourceapply/apps_test.go
  pkg/resourceapply/core.go
  pkg/resourceapply/core_test.go
  pkg/resourceapply/policy.go
  pkg/resourceapply/policy_test.go
  pkg/resourceapply/rbac.go
  pkg/resourceapply/rbac_test.go
Labels: kind/bug, priority/critical-urgent

#891 Update readiness immediatelly
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
Labels: kind/feature, priority/important-soon

#892 Bump golang to 1.17.5
  .github/workflows/go.yaml
  .github/workflows/releases.yaml
  Dockerfile
Labels: priority/important-soon, kind/machinery

#901 Delete drained pods on upgrades
  pkg/controller/scyllacluster/sync_statefulsets.go
Labels: kind/bug, priority/critical-urgent

#714 Add e2e test for rebootstrapping from existing PVCs
  test/e2e/set/scyllacluster/scyllacluster_rebootstrap.go
Labels: kind/feature

#900 Raise loglevel in CI to V4
  .github/workflows/go.yaml
Labels: priority/important-soon, kind/machinery

#895 Fix sysctls example in docs
  docs/source/generic.md
Labels: kind/documentation, priority/important-longterm

#902 Fix supported releases for v1.6
  docs/source/releases.md
Labels: kind/documentation

#903 [v1.6] Fix supported releases for v1.6
  docs/source/releases.md
Labels: priority/important-soon, kind/documentation

#770 Convert ephemeral storage to xfs on GKE
  Dockerfile
  Makefile
  docs/source/gke.md
  docs/source/releases.md
  examples/gke/cluster.yaml
  examples/gke/gke.sh
  examples/gke/raid-daemonset.yaml
  examples/gke/xfs-formatter-daemonset.yaml
  hack/gke/systemd/mnt-raid\x2ddisks-disk0.mount
  hack/gke/systemd/xfs-formatter.service
  hack/gke/xfs-formatter/bin/tune2fs
  hack/gke/xfs-formatter/xfs-checker.sh
  hack/gke/xfs-formatter/xfs-formatter.sh
  hack/test/gke/xfs-formatter/tune2fs_test.sh
Labels: kind/bug, priority/important-soon

#905 [v1.6] Delete drained pods on upgrades
  pkg/controller/scyllacluster/sync_statefulsets.go
Labels: kind/bug, priority/important-soon
