Repository scylladb/scylla-operator, pull requests merged in 2021-10, with the labels that each got.

#790 Update release instructions
  release.md
Labels: kind/documentation, priority/important-longterm

#792 Bump cert-manager manifest to 1.5.3
  examples/common/cert-manager.yaml
Labels: priority/important-soon, kind/machinery

#799 Bump Scylla and Scylla Manager Agent versions
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  test/e2e/fixture/scyllacluster/basic.scyllacluster.yaml
  test/e2e/set/scyllacluster/config.go
Labels: kind/documentation
