Repository scylladb/scylla-operator, pull requests merged in 2021-06, with the labels that each got.

#627 Wait for cert-manager webhook CA
  hack/ci-deploy.sh
Labels: kind/flake, priority/important-longterm

#623 Collect KAS audit logs and API call stats in e2e tests
  .github/actions/setup-minikube/action.yaml
  .github/workflows/go.yaml
Labels: kind/machinery, priority/important-soon

#628 Disable deprecated auth in GKE example
  examples/gke/gke.sh
Labels: kind/documentation

#629 Collect rotated KAS audit logs
  .github/workflows/go.yaml
Labels: kind/machinery, priority/important-longterm

#632 Add e2e for scaling a ScyllaCluster
  test/e2e/set/scyllacluster/helpers.go
  test/e2e/set/scyllacluster/scyllacluster_scaling.go
Labels: kind/feature, priority/important-longterm

#634 Add e2e test for automatic orphaned volume cleanup
  go.mod
  pkg/controller/helpers/mergepatch.go
  pkg/controller/helpers/mergepatch_test.go
  test/e2e/set/scyllacluster/helpers.go
  test/e2e/set/scyllacluster/scyllacluster_pv.go
  vendor/modules.txt
Labels: kind/feature, priority/important-longterm

#635 Raise e2e timeout
  .github/workflows/go.yaml
Labels: kind/machinery, priority/important-soon

#644 Add upgrade guide for 1.3
  docs/source/upgrade.md
Labels: kind/documentation

#645 [v1.3] Add upgrade guide for 1.3
  docs/source/upgrade.md
Labels: kind/documentation

#647 Fix docs about GKE script parameters and Helm example resources listsing
  docs/source/gke.md
  docs/source/helm.md
Labels: kind/documentation

#648 [v1.3] Fix docs about GKE script parameters and Helm example resources listsing
  docs/source/gke.md
  docs/source/helm.md
Labels: kind/documentation

#649 Mark v1.3 docs as latests stable and set release date for v1.4
  docs/source/conf.py
  docs/source/releases.md
Labels: kind/documentation

#650 Use dedicated raid device in GKE example to avoid conflicts
  examples/gke/raid-daemonset.yaml
Labels: kind/bug, priority/important-soon

#652 [v1.2] Use dedicated raid device in GKE example to avoid conflicts
  examples/gke/raid-daemonset.yaml
Labels: kind/bug

#651 [v1.3] Use dedicated raid device in GKE example to avoid conflicts
  examples/gke/raid-daemonset.yaml
Labels: kind/bug

#640 Explicitly set gcloud project in GKE example commands
  examples/gke/gke.sh
Labels: kind/documentation

#656 Document operator support matrix
  README.md
  docs/source/generic.md
  docs/source/releases.md
Labels: kind/documentation, priority/important-soon

#659 Fix broken references in node operations documentation
  docs/source/nodeoperations/replace_node.md
  docs/source/nodeoperations/restore.md
Labels: kind/documentation

#661 Set overpovisioned parameter when Scylla Pod QoS is not Guaranteed
  pkg/sidecar/config/config.go
  pkg/sidecar/identity/member.go
Labels: kind/feature

#664 Claim kube version >= 1.19.10
  README.md
  docs/source/releases.md
Labels: kind/documentation, priority/important-soon

#662 Explicitly set helper containers resources limits
  pkg/controller/scyllacluster/resource/resource.go
Labels: kind/feature
