Repository scylladb/scylla-operator, pull requests merged in 2021-05, with the labels that each got.

#574 Add optional SecurityContext to Helm Charts
  helm/scylla-manager/templates/controller_deployment.yaml
  helm/scylla-manager/templates/manager_deployment.yaml
  helm/scylla-manager/values.schema.json
  helm/scylla-manager/values.yaml
  helm/scylla-operator/templates/deployment.yaml
  helm/scylla-operator/values.schema.json
  helm/scylla-operator/values.yaml
Labels: kind/feature, priority/important-soon

#576 Fix service DNS names for in-cluster communication
  deploy/operator/10_certificate.yaml
  examples/common/operator.yaml
  helm/scylla-operator/templates/certificate.yaml
  pkg/naming/names.go
Labels: kind/bug

#559 Document branching and release procedure
  release.md
Labels: kind/documentation

#579 Use scylla 4.4 in e2e tests.
  test/e2e/set/scyllacluster/config.go
Labels: kind/feature

#581 Release v1.2 docs and add a release schedule for v1.3
  docs/source/conf.py
  docs/source/releases.md
Labels: kind/documentation

#592 Make v1.2 docs the latest version
  docs/source/conf.py
Labels: kind/documentation, priority/important-soon

#585 Remove experimental label from EKS example
  docs/source/eks.md
  docs/source/index.rst
Labels: kind/documentation

#599 Added webhook cleanup step to upgrade procedure
  docs/source/upgrade.md
Labels: kind/documentation

#601 [v1.2] Added webhook cleanup step to upgrade procedure
  docs/source/upgrade.md
Labels: kind/documentation

#598 Add Helm publishing step to release process
  release.md
Labels: kind/documentation

#603 Use REST API for schema agreement check
  go.mod
  go.sum
  pkg/controllers/cluster/actions/upgrade_version.go
  pkg/scyllaclient/client.go
  pkg/test/integration/scylla.go
  test/integration/upgrade_version_test.go
  vendor/github.com/scylladb/go-reflectx/.golangci.yml
  vendor/github.com/scylladb/go-reflectx/.travis.yml
  vendor/github.com/scylladb/go-reflectx/LICENSE
  vendor/github.com/scylladb/go-reflectx/Makefile
  vendor/github.com/scylladb/go-reflectx/README.md
  vendor/github.com/scylladb/go-reflectx/reflect.go
  vendor/github.com/scylladb/go-reflectx/transform.go
  vendor/github.com/scylladb/gocqlx/v2/.gitignore
  vendor/github.com/scylladb/gocqlx/v2/.golangci.yml
  vendor/github.com/scylladb/gocqlx/v2/LICENSE
  vendor/github.com/scylladb/gocqlx/v2/Makefile
  vendor/github.com/scylladb/gocqlx/v2/README.md
  vendor/github.com/scylladb/gocqlx/v2/doc.go
  vendor/github.com/scylladb/gocqlx/v2/go.mod
  vendor/github.com/scylladb/gocqlx/v2/go.sum
  vendor/github.com/scylladb/gocqlx/v2/gocqlx.go
  vendor/github.com/scylladb/gocqlx/v2/iterx.go
  vendor/github.com/scylladb/gocqlx/v2/mapper.go
  vendor/github.com/scylladb/gocqlx/v2/queryx.go
  vendor/github.com/scylladb/gocqlx/v2/queryx_wrap.go
  vendor/github.com/scylladb/gocqlx/v2/session.go
  vendor/github.com/scylladb/gocqlx/v2/udt.go
  vendor/modules.txt
Labels: kind/bug, priority/important-soon

#609 Default scylla to 4.4.2 and manager to 2.3.0
  deploy/manager/dev/50_manager_deployment.yaml
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_manager_deployment.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  examples/common/manager.yaml
  helm/deploy/manager_prod.yaml
  helm/scylla-manager/values.yaml
  helm/scylla/values.yaml
  test/e2e/fixture/scyllacluster/basic.scyllacluster.yaml
  test/e2e/set/scyllacluster/config.go
Labels: kind/feature, priority/important-soon

#611 Fix panic in orphaned PV cleanup when PV NodeAffinity is empty
  pkg/controllers/cluster/cleanup.go
Labels: kind/bug

#612 Add fix to documentation about TRUNCATE issues in Minikube
  docs/source/index.rst
  docs/source/known_issues.md
Labels: kind/documentation

#605 Provision autogenerated auth token for Scylla API
  deploy/operator/00_clusterrole_def.yaml
  deploy/operator/00_scyllacluster_member_clusterrole_def.yaml
  docs/source/generic.md
  examples/common/operator.yaml
  helm/scylla-operator/templates/clusterrole_def.yaml
  helm/scylla-operator/templates/scyllacluster_member_clusterrole_def.yaml
  pkg/controllers/cluster/actions/upgrade_version.go
  pkg/controllers/cluster/agent.go
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/cluster/resource/resource.go
  pkg/controllers/cluster/sync.go
  pkg/controllers/helpers/agent.go
  pkg/controllers/manager/manager_controller.go
  pkg/controllers/sidecar/sidecar_controller.go
  pkg/naming/constants.go
  pkg/naming/names.go
  pkg/scyllaclient/config.go
  pkg/util/resourceapply/secret.go
  pkg/util/resourceapply/secret_test.go
  test/e2e/set/scyllacluster/helpers.go
  test/e2e/set/scyllacluster/scyllacluster_auth.go
  test/integration/upgrade_version_test.go
Labels: area/security, kind/feature, priority/important-soon

#617 Iterate over PR numbers not indexes during release notes generation
  pkg/cmd/releasenotes/releasenotes.go
Labels: kind/machinery

#616 Use --format=docker to support SHELL instruction in the Dockerfile
  .github/workflows/go.yaml
Labels: kind/bug, priority/important-soon

#613 Change EKS example to multi-zone cluster
  docs/source/eks.md
  examples/eks/cluster.yaml
  examples/eks/eks-cluster.yaml
  examples/eks/eks.sh
  examples/eks/node-setup-daemonset.yaml
Labels: kind/documentation

#618 [v1.3] Pin tags to 1.3
  Makefile
  deploy/manager/dev/50_controller_deployment.yaml
  deploy/manager/prod/50_controller_deployment.yaml
  deploy/operator/50_deployment.yaml
  examples/common/manager.yaml
  examples/common/operator.yaml
  helm/scylla-manager/Chart.yaml
  helm/scylla-operator/Chart.yaml
Labels: kind/machinery

#619 Enable builiding docs for 1.3
  docs/source/conf.py
Labels: kind/documentation
