Repository scylladb/scylla-operator, pull requests merged in 2021-11, with the labels that each got.

#824 Build and publish Helm charts as CI artifacts
  .github/workflows/go.yaml
  Makefile
  helm/.gitignore
Labels: kind/machinery

#827 Freeze docutils dependency version to 0.17
  docs/pyproject.toml
Labels: kind/documentation

#831 Fix panic in pruneSevices
  pkg/controller/scyllacluster/sync_services.go
Labels: kind/bug, priority/important-soon

#832 [v1.5] Fix panic in pruneSevices
  pkg/controller/scyllacluster/sync_services.go
Labels: kind/bug, priority/important-soon

#830 Bump Scylla to 4.5.1 and manager to 2.5.2
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  examples/common/manager.yaml
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  helm/deploy/manager_prod.yaml
  helm/scylla/values.yaml
  test/e2e/fixture/scyllacluster/basic.scyllacluster.yaml
  test/e2e/set/scyllacluster/config.go
Labels: kind/feature, priority/important-longterm

#837 Fix spelling in CRD documentation
  docs/source/scylla_cluster_crd.md
Labels: kind/documentation

#845 Increase Scylla probes timeout to 30s
  pkg/controller/scyllacluster/resource/resource.go
  pkg/controller/scyllacluster/resource/resource_test.go
Labels: kind/bug

#843 Fix deploying multiple racks
  .github/actions/setup-minikube/action.yaml
  .github/workflows/go.yaml
  pkg/controller/scyllacluster/sync_statefulsets.go
  test/e2e/set/scyllacluster/config.go
  test/e2e/set/scyllacluster/helpers.go
  test/e2e/set/scyllacluster/scyllacluster_pv.go
  test/e2e/set/scyllacluster/scyllacluster_upgrades.go
Labels: kind/bug, priority/important-soon

#857 [v1.6] Pin tags to 1.6
  Makefile
  deploy/manager/dev/50_controller_deployment.yaml
  deploy/manager/prod/50_controller_deployment.yaml
  deploy/operator/50_operator.deployment.yaml
  deploy/operator/50_webhookserver.deployment.yaml
  examples/common/manager.yaml
  examples/common/operator.yaml
  helm/scylla-manager/Chart.yaml
  helm/scylla-operator/Chart.yaml
Labels: priority/important-soon, kind/machinery

#860 [v1.6] Bump Go to 1.17.2 in release script
  .github/workflows/releases.yaml
Labels: kind/machinery

#861 Bump Go to 1.17.2 in release script
  .github/workflows/releases.yaml
Labels: kind/machinery

#858 Build and publish 1.6 documentation
  docs/source/conf.py
Labels: kind/documentation

#867 Increase TerminationGracePeriodSeconds of Scylla pods
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
Labels: kind/bug, priority/important-soon
