Repository scylladb/scylla-operator, pull requests merged in 2021-04, with the labels that each got.

#541 Claim minimal Kubernetes version
  README.md
Labels: kind/documentation, priority/important-soon

#438 cluster: Manage Pod Disruption Budget (#214)
  deploy/operator/10_clusterrole.yaml
  examples/common/operator.yaml
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/cluster/pdb.go
  pkg/controllers/cluster/resource/resource.go
  pkg/controllers/cluster/sync.go
  pkg/naming/constants.go
  pkg/naming/names.go
  pkg/util/resource/helpers.go
  pkg/util/resourceapply/events.go
  pkg/util/resourceapply/hash.go
  pkg/util/resourceapply/hash_test.go
  pkg/util/resourceapply/pdb.go
  pkg/util/resourceapply/pdb_test.go
  test/e2e/framework/framework.go
  test/e2e/set/scyllacluster/helpers.go
  test/e2e/set/scyllacluster/scyllacluster_evictions.go
  test/e2e/set/scyllacluster/verify.go
Labels: kind/feature, priority/important-soon

#549 sidecar/config: fix ScyllaArgs parsing
  pkg/controllers/sidecar/config/config.go
  pkg/controllers/sidecar/config/config_test.go
Labels: kind/bug, priority/important-soon

#560 Add Verify PR jobs
  .github/workflows/pr.yaml
Labels: kind/ci-cd

#553 e2e: Dump test namespace content
  .github/workflows/go.yaml
  pkg/cmd/tests/options.go
  test/e2e/framework/dump.go
  test/e2e/framework/framework.go
Labels: kind/ci-cd, priority/important-soon

#551 makefile: use the same image tag for manifests and images
  Makefile
  helm/deploy/manager_prod.yaml
  helm/deploy/operator.yaml
  helm/scylla-manager/Chart.yaml
  helm/scylla-operator/Chart.yaml
Labels: kind/ci-cd

#565 [v1.1] Verify PRs
  .github/workflows/pr.yaml
Labels: kind/ci-cd

#564 [v1.2] Verify PRs
  .github/workflows/pr.yaml
Labels: kind/ci-cd

#562 [v1.2] makefile: use the same tag for manifests, images and charts
  Makefile
  helm/deploy/manager_prod.yaml
  helm/deploy/operator.yaml
  helm/scylla-manager/Chart.yaml
  helm/scylla-operator/Chart.yaml
Labels: kind/ci-cd

#561 e2e: Added smoke test for Scylla Manager integration (#478)
  test/e2e/set/scyllacluster/config.go
  test/e2e/set/scyllacluster/helpers.go
  test/e2e/set/scyllacluster/scyllamanager.go
Labels: kind/feature

#547 scripts: add support for arch linux on install dependencies
  install-dependencies.sh
Labels: kind/ci-cd

#557 integration test: correct failing integration test due to 10_webhook.yaml missing file
  pkg/test/integration/envtest.go
Labels: kind/failing-test

#569 [v1.2] Added smoke test for Scylla Manager integration
  test/e2e/set/scyllacluster/config.go
  test/e2e/set/scyllacluster/helpers.go
  test/e2e/set/scyllacluster/scyllamanager.go
Labels: kind/feature

#571 Allow to set placement options for manager controller (#496)
  helm/scylla-manager/templates/controller_deployment.yaml
  helm/scylla-manager/values.schema.json
  helm/scylla-manager/values.yaml
Labels: kind/feature

#572 [v1.2] Allow to set placement options for manager controller (#496)
  helm/scylla-manager/templates/controller_deployment.yaml
  helm/scylla-manager/values.schema.json
  helm/scylla-manager/values.yaml
Labels: kind/feature

#467 helm: Add aggregationRule to ClusterRoles (#440)
  Makefile
  deploy/manager/dev/00_controller_clusterrole.yaml
  deploy/manager/dev/00_controller_clusterrole_def.yaml
  deploy/manager/dev/20_controller_clusterrolebinding.yaml
  deploy/manager/prod/00_controller_clusterrole.yaml
  deploy/manager/prod/00_controller_clusterrole_def.yaml
  deploy/manager/prod/20_controller_clusterrolebinding.yaml
  deploy/operator/00_clusterrole.yaml
  deploy/operator/00_clusterrole_def.yaml
  deploy/operator/00_scyllacluster_member_clusterrole.yaml
  deploy/operator/00_scyllacluster_member_clusterrole_def.yaml
  deploy/operator/20_clusterrolebinding.yaml
  examples/common/manager.yaml
  examples/common/operator.yaml
  helm/scylla-manager/templates/controller_clusterrole.yaml
  helm/scylla-manager/templates/controller_clusterrole_def.yaml
  helm/scylla-manager/templates/controller_clusterrolebinding.yaml
  helm/scylla-operator/templates/clusterrole.yaml
  helm/scylla-operator/templates/clusterrole_def.yaml
  helm/scylla-operator/templates/clusterrolebinding.yaml
  helm/scylla-operator/templates/scyllacluster_member_clusterrole.yaml
  helm/scylla-operator/templates/scyllacluster_member_clusterrole_def.yaml
Labels: kind/feature

#568 Add 1.1.0->1.2.0 upgrade guide and refreshed examples
  docs/source/contributing.md
  docs/source/eks.md
  docs/source/generic.md
  docs/source/gke.md
  docs/source/manager.md
  docs/source/node_operations.md
  docs/source/releases.md
  docs/source/scylla_cluster_crd.md
  docs/source/upgrade.md
Labels: kind/documentation

#563 [v1.2] Use 1.2 version in manifests and charts as default image version
  Makefile
  deploy/manager/dev/50_controller_deployment.yaml
  deploy/manager/prod/50_controller_deployment.yaml
  deploy/operator/50_deployment.yaml
  examples/common/manager.yaml
  examples/common/operator.yaml
  helm/scylla-manager/Chart.yaml
  helm/scylla-operator/Chart.yaml
Labels: kind/ci-cd

#504 helm: Fix ServiceAccount for Scylla Manager chart
  Makefile
  deploy/manager/dev/10_manager_serviceaccount.yaml
  deploy/manager/dev/50_manager_deployment.yaml
  deploy/manager/prod/10_manager_serviceaccount.yaml
  deploy/manager/prod/50_manager_deployment.yaml
  examples/common/manager.yaml
  helm/scylla-manager/templates/manager_deployment.yaml
  helm/scylla-manager/templates/manager_serviceaccount.yaml
Labels: kind/feature
