Repository scylladb/scylla-operator, pull requests merged in 2021-07, with the labels that each got.

#667 Force fixed names and namespaces for system components in helm
  helm/scylla-manager/templates/NOTES.txt
  helm/scylla-manager/templates/controller_clusterrolebinding.yaml
  helm/scylla-manager/templates/controller_deployment.yaml
  helm/scylla-manager/templates/controller_pdb.yaml
  helm/scylla-manager/templates/controller_serviceaccount.yaml
  helm/scylla-manager/templates/manager_configmap.yaml
  helm/scylla-manager/templates/manager_deployment.yaml
  helm/scylla-manager/templates/manager_service.yaml
  helm/scylla-manager/templates/manager_serviceaccount.yaml
  helm/scylla-manager/templates/manager_servicemonitor.yaml
  helm/scylla-manager/values.schema.json
  helm/scylla-operator/templates/NOTES.txt
  helm/scylla-operator/templates/certificate.yaml
  helm/scylla-operator/templates/clusterrolebinding.yaml
  helm/scylla-operator/templates/issuer.yaml
  helm/scylla-operator/templates/operator.deployment.yaml
  helm/scylla-operator/templates/operator.serviceaccount.yaml
  helm/scylla-operator/templates/pdb.yaml
  helm/scylla-operator/templates/validatingwebhook.yaml
  helm/scylla-operator/templates/webhookserver.deployment.yaml
  helm/scylla-operator/templates/webhookserver.service.yaml
  helm/scylla-operator/templates/webhookserver.serviceaccount.yaml
  helm/scylla-operator/values.schema.json
  helm/scylla-operator/values.yaml
Labels: kind/bug, priority/important-soon

#673 Fix operator upgrade bugs
  deploy/operator/00_clusterrole_def.yaml
  examples/common/operator.yaml
  helm/scylla-operator/templates/clusterrole_def.yaml
  pkg/controller/helpers/apps.go
  pkg/controller/scyllacluster/resource/resource.go
  pkg/controller/scyllacluster/sync_agent_config.go
  pkg/controller/scyllacluster/sync_pdb.go
  pkg/controller/scyllacluster/sync_services.go
  pkg/controller/scyllacluster/sync_statefulsets.go
  pkg/resourceapply/apps.go
  pkg/resourceapply/apps_test.go
  pkg/resourceapply/core.go
  pkg/resourceapply/core_test.go
  pkg/resourceapply/policy.go
  pkg/resourceapply/policy_test.go
Labels: kind/bug, priority/important-soon

#668 Support observedGeneration API concept
  examples/common/operator.yaml
  pkg/api/scylla/v1/cluster_types.go
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/zz_generated.deepcopy.go
  pkg/controller/scyllacluster/status.go
  test/e2e/set/scyllacluster/helpers.go
  test/e2e/set/scyllacluster/verify.go
Labels: kind/feature, priority/important-soon

#597 Implement seedless mode
  pkg/controller/scyllacluster/resource/resource.go
  pkg/controller/scyllacluster/sync_services.go
  pkg/sidecar/identity/member_test.go
  test/e2e/set/scyllacluster/helpers.go
  test/e2e/set/scyllacluster/scyllacluster_replace.go
Labels: kind/feature, priority/important-longterm

#671 Remove the PVC when the service is decommissioned
  pkg/controller/scyllacluster/sync_services.go
  pkg/naming/names.go
  test/e2e/set/scyllacluster/scyllacluster_scaling.go
  test/e2e/set/scyllacluster/verify.go
Labels: kind/bug, priority/important-soon

#681 Fix GH action to work with new minikube 1.22.0
  .github/actions/setup-minikube/action.yaml
Labels: kind/machinery, priority/critical-urgent

#655 Hide master from documentation version dropdown
  docs/source/conf.py
Labels: kind/documentation

#684 Extend RackStatus API with UpdatedMembers and Stale fields
  examples/common/operator.yaml
  pkg/api/scylla/v1/cluster_types.go
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/zz_generated.deepcopy.go
  pkg/controller/scyllacluster/controller.go
  pkg/controller/scyllacluster/status.go
  pkg/controller/scyllacluster/sync_statefulsets.go
  test/e2e/set/scyllacluster/helpers.go
  test/e2e/set/scyllacluster/verify.go
Labels: kind/api-change, priority/critical-urgent

#683 Fix controller leader election lock names
  pkg/cmd/operator/manager_controller.go
  pkg/cmd/operator/operator.go
Labels: kind/bug, priority/important-soon

#666 Fix scylla manager DNS name in the URL
  pkg/cmd/operator/manager_controller.go
  pkg/naming/constants.go
  test/e2e/set/scyllacluster/config.go
  test/e2e/set/scyllacluster/helpers.go
Labels: kind/bug, priority/important-soon

#685 Group artificial delays supplying expectations
  pkg/controller/scyllacluster/status.go
  pkg/controller/scyllacluster/sync_statefulsets.go
Labels: kind/bug, priority/important-soon

#674 Add support for manually triggering ScyllaCluster rollout
  examples/common/operator.yaml
  pkg/api/scylla/v1/cluster_types.go
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/controller/scyllacluster/resource/resource.go
  pkg/naming/constants.go
  test/e2e/set/scyllacluster/scyllacluster_auth.go
Labels: kind/api-change, priority/important-soon

#689 Collect logs only for running containers
  test/e2e/framework/dump.go
Labels: kind/flake, priority/important-soon

#690 Fix e2e flake retry for promotion jobs
  .github/workflows/go.yaml
Labels: kind/machinery, priority/important-soon

#691 Use exponential backoff in OrphanedPV controller
  pkg/controller/helpers/error.go
  pkg/controller/helpers/error_test.go
  pkg/controller/orphanedpv/controller.go
  pkg/controller/orphanedpv/sync.go
Labels: kind/feature, priority/important-soon

#693 Add cluster delete instructions and reference to generic in gke docs
  docs/source/eks.md
  docs/source/gke.md
Labels: kind/documentation

#697 Make node replacement less likely to hit StatefulSet bug
  pkg/controller/scyllacluster/controller.go
  pkg/controller/scyllacluster/sync_services.go
Labels: kind/bug, priority/important-soon

#699 Fix error handling when making racks and report an event
  pkg/controller/scyllacluster/resource/resource.go
  pkg/controller/scyllacluster/sync_statefulsets.go
Labels: kind/bug, priority/important-soon

#705 Keep the seed node for N-1 compatibility
  pkg/controller/scyllacluster/resource/resource.go
Labels: kind/bug, priority/important-soon

#706 Fix date ranges for listing PRs in gen-release-notes
  pkg/cmd/releasenotes/generate.go
  pkg/cmd/releasenotes/github.go
  pkg/cmd/releasenotes/options.go
  pkg/cmd/releasenotes/releasenotes.go
Labels: kind/machinery, priority/critical-urgent

#707 Automatically publish release notes when a tag is created
  .github/workflows/releases.yaml
  hack/lib/semver.sh
  pkg/cmd/releasenotes/generate.go
  pkg/cmd/releasenotes/options.go
  pkg/cmd/releasenotes/releasenotes.go
  pkg/cmd/releasenotes/render.go
  release.md
Labels: kind/machinery, priority/important-soon

#708 Raise manager e2e timeout
  test/e2e/set/scyllacluster/config.go
Labels: kind/flake, priority/important-soon

#709 [v1.4] Initialize v1.4 branch
  Makefile
  deploy/manager/dev/50_controller_deployment.yaml
  deploy/manager/prod/50_controller_deployment.yaml
  deploy/operator/50_operator.deployment.yaml
  deploy/operator/50_webhookserver.deployment.yaml
  examples/common/manager.yaml
  examples/common/operator.yaml
  helm/scylla-manager/Chart.yaml
  helm/scylla-operator/Chart.yaml
Labels: kind/machinery, priority/important-soon

#710 Enable building v1.4 docs
  docs/source/conf.py
Labels: kind/machinery, priority/important-soon

#700 Prefer placing pods on different nodes for webhookserver and operator
  deploy/operator/50_operator.deployment.yaml
  deploy/operator/50_webhookserver.deployment.yaml
  examples/common/operator.yaml
  helm/scylla-operator/templates/_helpers.tpl
  helm/scylla-operator/templates/webhookserver.deployment.yaml
  helm/scylla-operator/values.yaml
Labels: kind/feature, priority/important-longterm

#715 Add PodDisruptionBudget for webhook server
  Makefile
  deploy/operator/10_operator.pdb.yaml
  deploy/operator/10_webhookserver.pdb.yaml
  examples/common/operator.yaml
  helm/scylla-operator/templates/operator.pdb.yaml
  helm/scylla-operator/templates/webhookserver.pdb.yaml
Labels: kind/bug, priority/important-soon

#720 Fix zone/region mapping in gke example cluster
  examples/gke/cluster.yaml
Labels: kind/documentation

#712 Add enhancement proposal process
  enhancements/README.md
  enhancements/proposal-template.md
  enhancements/proposals/dir_placeholder.delete_me_with_first_proposal
Labels: kind/documentation, priority/important-soon

#725 Add readiness probe to scylla-manager deployment
  deploy/manager/dev/50_manager_deployment.yaml
  deploy/manager/prod/50_manager_deployment.yaml
  examples/common/manager.yaml
  hack/ci-deploy.sh
  helm/scylla-manager/templates/manager_deployment.yaml
Labels: kind/feature

#727 Remove seed node replacement instructions from documentation
  docs/source/nodeoperations/replace_node.md
Labels: kind/documentation

#728 [v1.4] Remove seed node replacement instructions from documentation
  docs/source/nodeoperations/replace_node.md
Labels: kind/documentation

#729 Fix namespace names in docs
  docs/source/manager.md
  examples/common/monitoring/scylla-manager-service-monitor.yaml
Labels: kind/documentation, priority/important-soon

#731 [v1.4] Fix namespace names in docs
  docs/source/manager.md
  examples/common/monitoring/scylla-manager-service-monitor.yaml
Labels: kind/documentation

#733 Temporarily force deletion of pods when replacing nodes
  pkg/controller/scyllacluster/sync_services.go
Labels: kind/bug, priority/important-soon

#734 [v1.4] Temporarily force deletion of pods when replacing nodes
  pkg/controller/scyllacluster/sync_services.go
Labels: kind/bug, priority/important-soon

#678 Add support for imagePullSecrets for Scylla and Agent images
  examples/common/operator.yaml
  go.mod
  go.sum
  pkg/api/scylla/v1/cluster_types.go
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/zz_generated.deepcopy.go
  pkg/controller/scyllacluster/resource/resource.go
  pkg/controller/scyllacluster/resource/resource_test.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/flags.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_legacy.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_recent.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/internal/value/name.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_references.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/go-cmp/cmp/report_text.go
  vendor/github.com/google/go-cmp/cmp/report_value.go
  vendor/modules.txt
Labels: kind/api-change, kind/feature

#695 Chain validation errors
  pkg/admissionreview/handler.go
  pkg/api/validation/cluster_validation.go
  pkg/api/validation/cluster_validation_test.go
  pkg/cmd/operator/webhooks.go
Labels: kind/feature, priority/important-longterm

#722 Remove seed node label
  pkg/controller/scyllacluster/resource/resource.go
  pkg/naming/constants.go
  pkg/naming/labels.go
Labels: kind/cleanup
