Repository scylladb/scylla-operator, pull requests merged in 2021-09, with the labels that each got.

#774 Pin minikube version
  .github/actions/setup-minikube/action.yaml
Labels: priority/critical-urgent, kind/machinery

#773 Fix default anti-affinity rules for scylla-operator
  deploy/operator/50_operator.deployment.yaml
  deploy/operator/50_webhookserver.deployment.yaml
  examples/common/operator.yaml
  helm/scylla-operator/values.yaml
Labels: kind/bug, priority/important-soon

#776 [v1.5] Init v1.5 branch
  Makefile
  deploy/manager/dev/50_controller_deployment.yaml
  deploy/manager/prod/50_controller_deployment.yaml
  deploy/operator/50_operator.deployment.yaml
  deploy/operator/50_webhookserver.deployment.yaml
  examples/common/manager.yaml
  examples/common/operator.yaml
  helm/scylla-manager/Chart.yaml
  helm/scylla-operator/Chart.yaml
Labels: priority/important-soon, kind/machinery

#777 Enable building v1.5 docs
  docs/source/conf.py
Labels: priority/important-soon, kind/machinery

#780 Reserve time for flake retries
  .github/workflows/go.yaml
Labels: priority/important-soon, kind/machinery

#783 Handle multiple tags for the same commit on promotion
  .github/workflows/go.yaml
  Makefile
  hack/ci-detect-tags.sh
Labels: priority/critical-urgent, kind/machinery

#781 Allow code generation for multiple API versions
  Dockerfile
  Makefile
  examples/common/operator.yaml
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
Labels: priority/important-longterm, kind/machinery

#785 Don't GC events during CI runs
  .github/actions/setup-minikube/action.yaml
Labels: priority/important-soon, kind/flake

#788 Release 1.5 and update release schedule
  docs/source/releases.md
Labels: priority/important-soon, kind/documentation

#787 Mark v1.5 docs as latest stable
  docs/source/conf.py
Labels: priority/important-soon, kind/machinery

#795 Remove redundant sleep from e2e upgrade test
  test/e2e/set/scyllacluster/scyllacluster_upgrades.go
Labels: kind/cleanup
