Repository scylladb/scylla-operator, pull requests merged in 2022-11, with the labels that each got.

#1085 Don't use "any" prefix for LB CQL service
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
  pkg/controller/scyllacluster/sync_certs.go
  pkg/naming/constants.go
  pkg/naming/names.go
  test/e2e/set/scyllacluster/scyllacluster_expose.go
  test/e2e/set/scyllacluster/scyllacluster_tls.go
Labels: kind/bug, priority/important-soon

#1084 Fix running parallel processes in test runner
  pkg/cmd/tests/tests_run.go
Labels: priority/important-soon, kind/machinery

#1087 Make sure manager controller reacts to SA token changes
  pkg/controller/manager/controller.go
Labels: kind/bug, priority/important-soon

#1098 Fix repository paths so it can be vendored
  .github/workflows/go.yaml
  hack/gke/systemd/go.mod
Labels: kind/bug, priority/important-soon

#1102 Bump gocql to scylladb/gocql@v1.7.3
  go.mod
  go.sum
  vendor/github.com/gocql/gocql/events.go
  vendor/github.com/gocql/gocql/host_source_scylla.go
  vendor/github.com/gocql/gocql/scylla.go
  vendor/modules.txt
Labels: priority/important-soon, kind/failing-test
