Repository scylladb/scylla-operator, pull requests merged in 2022-04, with the labels that each got.

#969 Allow directly selecting member services for building CQL connections
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
  pkg/naming/constants.go
  test/e2e/utils/helpers.go
Labels: kind/feature

#949 Add link to Scylla University lesson
  README.md
Labels: kind/documentation

#967 Fix decommissioning of drained nodes
  .github/actions/setup-minikube/action.yaml
  pkg/controller/sidecar/sync.go
  pkg/controllerhelpers/core.go
  pkg/helpers/mergepatch.go
  test/e2e/set/nodeconfig/nodeconfig_optimizations.go
  test/e2e/set/scyllacluster/scyllacluster_replace.go
  test/e2e/set/scyllacluster/scyllacluster_scaling.go
  test/e2e/utils/helpers.go
Labels: kind/bug, priority/important-soon

#970 Fix "local ssd disks" link in EKS deployment docs
  docs/source/eks.md
Labels: kind/documentation

#976 Gather logs from previous iterations of restarted containers of non-e2e namespaced resources
  hack/ci-gather-artifacts.sh
Labels: priority/important-longterm, kind/machinery

#977 Bump scylla to 4.6.3 and manager to 2.6.3
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  examples/common/manager.yaml
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  helm/deploy/manager_prod.yaml
  helm/scylla/values.yaml
  pkg/naming/constants.go
  test/e2e/fixture/scylla/basic.scyllacluster.yaml
  test/e2e/set/scyllacluster/config.go
Labels: kind/feature, priority/important-soon
