Repository scylladb/scylla-operator, pull requests merged in 2022-10, with the labels that each got.

#1049 Avoid watch cache when using UntilWithSync
  pkg/cmd/operator/sidecar.go
  pkg/helpers/cache.go
  test/e2e/framework/util.go
  test/e2e/utils/helpers.go
Labels: kind/bug, priority/critical-urgent

#1060 Add resource version to e2e messages waiting for ScyllaCluster rollout
  test/e2e/set/nodeconfig/nodeconfig_optimizations.go
  test/e2e/set/scyllacluster/scyllacluster_auth.go
  test/e2e/set/scyllacluster/scyllacluster_evictions.go
  test/e2e/set/scyllacluster/scyllacluster_pv.go
  test/e2e/set/scyllacluster/scyllacluster_rebootstrap.go
  test/e2e/set/scyllacluster/scyllacluster_replace.go
  test/e2e/set/scyllacluster/scyllacluster_scaling.go
  test/e2e/set/scyllacluster/scyllacluster_shardawareness.go
  test/e2e/set/scyllacluster/scyllacluster_sysctl.go
  test/e2e/set/scyllacluster/scyllacluster_updates.go
  test/e2e/set/scyllacluster/scyllacluster_upgrades.go
  test/e2e/set/scyllacluster/scyllacluster_webhooks.go
  test/e2e/set/scyllacluster/scyllamanager.go
Labels: priority/important-soon, kind/machinery

#1062 Raise loglevel for manager controller in CI
  .github/actions/run-e2e/action.yaml
Labels: priority/important-soon, kind/machinery

#1054 Wait for scylla nodes to have a full quorum before testing CQL in e2e tests
  test/e2e/set/scyllacluster/scyllacluster_auth.go
  test/e2e/set/scyllacluster/scyllacluster_evictions.go
  test/e2e/set/scyllacluster/scyllacluster_expose.go
  test/e2e/set/scyllacluster/scyllacluster_hostid.go
  test/e2e/set/scyllacluster/scyllacluster_pv.go
  test/e2e/set/scyllacluster/scyllacluster_rebootstrap.go
  test/e2e/set/scyllacluster/scyllacluster_replace.go
  test/e2e/set/scyllacluster/scyllacluster_scaling.go
  test/e2e/set/scyllacluster/scyllacluster_shardawareness.go
  test/e2e/set/scyllacluster/scyllacluster_sysctl.go
  test/e2e/set/scyllacluster/scyllacluster_updates.go
  test/e2e/set/scyllacluster/scyllacluster_upgrades.go
  test/e2e/set/scyllacluster/scyllacluster_webhooks.go
  test/e2e/set/scyllacluster/scyllamanager.go
  test/e2e/set/scyllacluster/verify.go
  test/e2e/utils/datainserter.go
  test/e2e/utils/helpers.go
Labels: priority/important-soon, kind/flake

#1065 Fix e2e wait timeout for scylla quorum
  test/e2e/utils/helpers.go
Labels: priority/important-soon, kind/flake

#1069 Adjust rate limits and timeouts for e2e tests
  hack/ci-deploy.sh
  pkg/controller/scyllacluster/controller.go
  test/e2e/utils/config.go
  test/e2e/utils/helpers.go
Labels: priority/important-soon, kind/machinery

#1001 Fix Scylla Monitoring support
  docs/source/monitoring.md
  examples/common/monitoring/scylla-manager-service-monitor.yaml
  examples/common/monitoring/scylla-service-monitor.yaml
  examples/common/monitoring/values.yaml
Labels: priority/important-soon, kind/documentation

#1067 Update actions in CI
  .github/actions/docs/build/action.yaml
  .github/actions/run-e2e/action.yaml
  .github/workflows/docs_build.yaml
  .github/workflows/docs_deploy.yaml
  .github/workflows/go.yaml
  .github/workflows/pr.yaml
  .github/workflows/releases.yaml
Labels: priority/important-longterm, kind/machinery

#1070 Add Status Conditions
  examples/common/operator.yaml
  pkg/api/scylla/v1/cluster_types.go
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/zz_generated.deepcopy.go
  pkg/controller/scyllacluster/conditions.go
  pkg/controller/scyllacluster/controller.go
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/sync.go
  pkg/controller/scyllacluster/sync_agent_config.go
  pkg/controller/scyllacluster/sync_ingress.go
  pkg/controller/scyllacluster/sync_pdb.go
  pkg/controller/scyllacluster/sync_rolebindings.go
  pkg/controller/scyllacluster/sync_serviceaccounts.go
  pkg/controller/scyllacluster/sync_services.go
  pkg/controller/scyllacluster/sync_statefulsets.go
  pkg/controllerhelpers/core.go
  pkg/controllerhelpers/core_test.go
  pkg/helpers/status.go
  pkg/internalapi/conditions.go
  pkg/resource/helpers.go
  pkg/resourceapply/core.go
  pkg/util/errors/multiline.go
  pkg/util/errors/multiline_test.go
  test/e2e/set/scyllacluster/verify.go
  test/e2e/utils/helpers.go
Labels: kind/feature, priority/important-soon

#1064 Tee test logs of e2e test runner's parallel processes to files
  pkg/cmd/tests/tests_run.go
Labels: kind/machinery
