Repository scylladb/scylla-operator, pull requests merged in 2022-08, with the labels that each got.

#1008 Drop unsupported releases from docs
  docs/source/conf.py
Labels: kind/documentation

#1010 [v1.6] Fallback image builds to cgroupfs to workaround ubuntu systemd issues
  .github/workflows/go.yaml
Labels: kind/machinery

#1009 [v1.6] Update docs theme to 1.0.6 and add CI
  .github/actions/docs/build/action.yaml
  .github/actions/docs/setup/action.yaml
  .github/workflows/docs_build.yaml
  .github/workflows/docs_deploy.yaml
  .github/workflows/pages.yaml
  .gitignore
  docs/Makefile
  docs/_utils/deploy.sh
  docs/_utils/setup.sh
  docs/hack/install-poetry.sh
  docs/poetry.lock
  docs/pyproject.toml
  docs/redirections.yaml
  docs/source/conf.py
  docs/source/index.rst
  docs/source/nodeoperations/automatic_cleanup.md
  docs/source/nodeoperations/maintenance_mode.md
  docs/source/nodeoperations/replace_node.md
  docs/source/nodeoperations/restore.md
  docs/source/nodeoperations/scylla_upgrade.md
Labels: kind/documentation

#1011 Fix loglevel type and change image tag in example helm values for Scylla Operator Chart
  examples/helm/values.operator.yaml
Labels: kind/machinery

#1004 Fix incorrect webhook service name in helm chart
  helm/scylla-operator/templates/webhookserver.service.yaml
Labels: kind/machinery

#1012 [v1.6] Build docs on presubmits only for the current branch
  .github/actions/docs/build/action.yaml
  .github/workflows/docs_build.yaml
  .github/workflows/docs_deploy.yaml
Labels: kind/machinery

#965 Bump docs theme from 1.1 to 1.2
  docs/poetry.lock
  docs/pyproject.toml
  docs/source/conf.py
Labels: priority/important-soon, kind/machinery

#993 Reconcile Ingress objects for ScyllaCluster
  deploy/operator/00_clusterrole_def.yaml
  examples/common/operator.yaml
  helm/scylla-manager/values.schema.json
  helm/scylla-operator/templates/clusterrole_def.yaml
  helm/scylla/templates/scyllacluster.yaml
  helm/scylla/values.schema.json
  pkg/api/scylla/v1/cluster_types.go
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/zz_generated.deepcopy.go
  pkg/api/validation/cluster_validation.go
  pkg/api/validation/cluster_validation_test.go
  pkg/cmd/operator/operator.go
  pkg/controller/scyllacluster/controller.go
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
  pkg/controller/scyllacluster/sync.go
  pkg/controller/scyllacluster/sync_ingress.go
  pkg/controller/scyllacluster/sync_services.go
  pkg/controllertools/ingressmanager.go
  pkg/naming/constants.go
  pkg/resourceapply/networking.go
  pkg/resourceapply/networking_test.go
  test/e2e/set/scyllacluster/scyllacluster_expose.go
Labels: kind/feature, priority/important-soon

#1017 Close idle connections to scylla API when done using them
  pkg/controller/scyllacluster/sync_statefulsets.go
  pkg/controller/sidecar/controller.go
  pkg/controller/sidecar/sync.go
  pkg/scyllaclient/client.go
  pkg/sidecar/probes.go
  test/e2e/set/scyllacluster/scyllacluster_auth.go
  test/e2e/set/scyllacluster/scyllacluster_hostid.go
  test/e2e/set/scyllacluster/verify.go
Labels: kind/bug, priority/important-soon

#1018 [v1.7] Close idle connections to scylla API when done using them
  pkg/controller/scyllacluster/sync_statefulsets.go
  pkg/controller/sidecar/sync.go
  pkg/scyllaclient/client.go
  pkg/sidecar/probes.go
  test/e2e/set/scyllacluster/scyllacluster_auth.go
  test/e2e/set/scyllacluster/verify.go
Labels: kind/bug, priority/important-soon
