Repository scylladb/scylla-operator, pull requests merged in 2022-02, with the labels that each got.

#933 Keep custom annotations on ServiceAccounts
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/sync_serviceaccounts.go
  pkg/resourceapply/core.go
  pkg/resourceapply/core_test.go
  test/e2e/set/scyllacluster/scyllacluster_sa.go
Labels: kind/bug

#935 [v1.7] Keep custom annotations on ServiceAccounts
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/sync_serviceaccounts.go
  pkg/resourceapply/core.go
  pkg/resourceapply/core_test.go
  test/e2e/set/scyllacluster/scyllacluster_sa.go
Labels: kind/bug

#937 Bring back ServiceAccount template in Scylla Helm chart
  helm/scylla/templates/_helpers.tpl
  helm/scylla/templates/serviceaccount.yaml
Labels: kind/bug, priority/important-soon

#939 [v1.7] Bring back ServiceAccount template in Scylla Helm chart
  helm/scylla/templates/_helpers.tpl
  helm/scylla/templates/serviceaccount.yaml
Labels: kind/bug, priority/important-soon

#942 Update Scylla docs theme to 1.1.0
  docs/poetry.lock
  docs/pyproject.toml
  docs/source/conf.py
Labels: priority/important-soon, kind/machinery

#945 Bump docomentation dependencies
  docs/hack/install-poetry.sh
  docs/poetry.lock
  docs/pyproject.toml
Labels: priority/important-soon, kind/machinery
