Repository scylladb/scylla-operator, pull requests merged in 2022-09, with the labels that each got.

#1005 Promote PodDisruptionBudgets from V1Beta1 to V1
  deploy/manager/dev/10_controller_pdb.yaml
  deploy/manager/prod/10_controller_pdb.yaml
  deploy/operator/10_operator.pdb.yaml
  deploy/operator/10_webhookserver.pdb.yaml
  docs/source/releases.md
  examples/common/manager.yaml
  examples/common/operator.yaml
  helm/scylla-manager/templates/controller_pdb.yaml
  helm/scylla-operator/templates/operator.pdb.yaml
  helm/scylla-operator/templates/webhookserver.pdb.yaml
  pkg/cmd/operator/operator.go
  pkg/controller/scyllacluster/controller.go
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/sync.go
  pkg/controller/scyllacluster/sync_pdb.go
  pkg/controllertools/pdbmanager.go
  pkg/resourceapply/policy.go
  pkg/resourceapply/policy_test.go
  test/e2e/set/scyllacluster/verify.go
Labels: kind/feature

#1026 Update Golang to 1.19
  .github/workflows/go.yaml
  Dockerfile
  go.mod
  pkg/client/scylla/clientset/versioned/fake/register.go
  pkg/client/scylla/clientset/versioned/scheme/register.go
Labels: priority/important-soon, kind/machinery

#1032 Unify WaitForState implementations
  test/e2e/set/nodeconfig/nodeconfig_optimizations.go
  test/e2e/set/scyllacluster/scyllacluster_auth.go
  test/e2e/set/scyllacluster/scyllacluster_evictions.go
  test/e2e/set/scyllacluster/scyllacluster_expose.go
  test/e2e/set/scyllacluster/scyllacluster_hostid.go
  test/e2e/set/scyllacluster/scyllacluster_pv.go
  test/e2e/set/scyllacluster/scyllacluster_rebootstrap.go
  test/e2e/set/scyllacluster/scyllacluster_replace.go
  test/e2e/set/scyllacluster/scyllacluster_sa.go
  test/e2e/set/scyllacluster/scyllacluster_scaling.go
  test/e2e/set/scyllacluster/scyllacluster_shardawareness.go
  test/e2e/set/scyllacluster/scyllacluster_sysctl.go
  test/e2e/set/scyllacluster/scyllacluster_updates.go
  test/e2e/set/scyllacluster/scyllacluster_upgrades.go
  test/e2e/set/scyllacluster/scyllacluster_webhooks.go
  test/e2e/set/scyllacluster/scyllamanager.go
  test/e2e/utils/helpers.go
Labels: priority/important-soon, kind/cleanup

#1029 Fix NodeConfig e2e flake and correct resourcequotas resource name in test machinery
  test/e2e/set/nodeconfig/nodeconfig_optimizations.go
Labels: priority/important-soon, kind/flake

#1040 Raise loglevel for manager controller in CI
  .github/workflows/go.yaml
Labels: priority/important-soon, kind/machinery

#1039 Use more workers by default to make the controller more responsive
  pkg/cmd/operator/operator.go
Labels: kind/feature, priority/critical-urgent

#1042 Drop migration workaround for manual ServiceAccounts
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/sync_serviceaccounts.go
Labels: kind/cleanup, priority/important-longterm

#1046 Split serial and parallel e2e suites into dedicated jobs
  .github/actions/run-e2e/action.yaml
  .github/workflows/go.yaml
Labels: priority/important-soon, kind/machinery

#1048 Disable shadawareness E2E giving false positives
  test/e2e/set/scyllacluster/scyllacluster_shardawareness.go
Labels: priority/important-soon, kind/failing-test
