Repository scylladb/scylla-operator, pull requests merged in 2022-01, with the labels that each got.

#898 Switch liveness probe to /system/uptime_ms endpoint
  pkg/scyllaclient/client_ping.go
  pkg/scyllaclient/internal/scylla/client/operations/operations_client.go
  pkg/scyllaclient/internal/scylla/client/operations/system_uptime_ms_get_parameters.go
  pkg/scyllaclient/internal/scylla/client/operations/system_uptime_ms_get_responses.go
  pkg/scyllaclient/scylla.json
  pkg/sidecar/probes.go
Labels: kind/bug, priority/important-soon

#886 Update docs theme to 1.0.6 and add CI
  .github/actions/docs/build/action.yaml
  .github/actions/docs/setup/action.yaml
  .github/workflows/docs_build.yaml
  .github/workflows/docs_deploy.yaml
  .github/workflows/pages.yaml
  .gitignore
  docs/Makefile
  docs/_utils/deploy.sh
  docs/_utils/setup.sh
  docs/hack/install-poetry.sh
  docs/poetry.lock
  docs/pyproject.toml
  docs/redirections.yaml
  docs/source/conf.py
  docs/source/index.rst
  docs/source/nodeoperations/automatic_cleanup.md
  docs/source/nodeoperations/maintenance_mode.md
  docs/source/nodeoperations/replace_node.md
  docs/source/nodeoperations/restore.md
  docs/source/nodeoperations/scylla_upgrade.md
Labels: priority/important-soon, kind/documentation

#909 Build docs on presubmits only for the current branch
  .github/actions/docs/build/action.yaml
  .github/workflows/docs_build.yaml
  .github/workflows/docs_deploy.yaml
Labels: priority/important-soon, kind/machinery

#888 Cache iotune results in persistent location
  pkg/sidecar/config/config.go
Labels: kind/feature, priority/important-soon

#910 Reduce build dependencies
  Dockerfile
Labels: priority/important-longterm, kind/machinery

#764 Live reload webhook server certificates
  pkg/cmd/operator/webhooks.go
  pkg/cmd/operator/webhooks_test.go
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/cert_key.go
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/client_ca.go
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/dynamic_cafile_content.go
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/dynamic_serving_content.go
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/dynamic_sni_content.go
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/interfaces.go
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/named_certificates.go
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/static_content.go
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/tlsconfig.go
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/union_content.go
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/util.go
  vendor/k8s.io/client-go/tools/events/OWNERS
  vendor/k8s.io/client-go/tools/events/doc.go
  vendor/k8s.io/client-go/tools/events/event_broadcaster.go
  vendor/k8s.io/client-go/tools/events/event_recorder.go
  vendor/k8s.io/client-go/tools/events/fake.go
  vendor/k8s.io/client-go/tools/events/helper.go
  vendor/k8s.io/client-go/tools/events/interfaces.go
  vendor/modules.txt
Labels: kind/feature, priority/important-soon

#884 Use direct localhost connection to Scylla in sidecar
  pkg/cmd/operator/sidecar.go
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
  pkg/controller/sidecar/controller.go
  pkg/controller/sidecar/sync.go
  pkg/controllerhelpers/scylla.go
  pkg/naming/constants.go
  pkg/scyllaclient/client.go
  pkg/scyllaclient/config.go
  pkg/scyllaclient/retry.go
  pkg/sidecar/probes.go
Labels: kind/feature, priority/important-soon

#793 Expose shard aware ports in Scylla Services
  go.mod
  go.sum
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
  test/e2e/set/scyllacluster/scyllacluster_shardawareness.go
  vendor/github.com/gocql/gocql/.travis.yml
  vendor/github.com/gocql/gocql/AUTHORS
  vendor/github.com/gocql/gocql/README.md
  vendor/github.com/gocql/gocql/cluster.go
  vendor/github.com/gocql/gocql/conn.go
  vendor/github.com/gocql/gocql/connectionpool.go
  vendor/github.com/gocql/gocql/connpicker.go
  vendor/github.com/gocql/gocql/control.go
  vendor/github.com/gocql/gocql/doc.go
  vendor/github.com/gocql/gocql/docker-compose.yml
  vendor/github.com/gocql/gocql/errors.go
  vendor/github.com/gocql/gocql/events.go
  vendor/github.com/gocql/gocql/filters.go
  vendor/github.com/gocql/gocql/frame.go
  vendor/github.com/gocql/gocql/helpers.go
  vendor/github.com/gocql/gocql/host_source.go
  vendor/github.com/gocql/gocql/install_test_deps.sh
  vendor/github.com/gocql/gocql/integration.sh
  vendor/github.com/gocql/gocql/logger.go
  vendor/github.com/gocql/gocql/marshal.go
  vendor/github.com/gocql/gocql/metadata_cassandra.go
  vendor/github.com/gocql/gocql/metadata_scylla.go
  vendor/github.com/gocql/gocql/policies.go
  vendor/github.com/gocql/gocql/prepared_cache.go
  vendor/github.com/gocql/gocql/query_executor.go
  vendor/github.com/gocql/gocql/recreate.go
  vendor/github.com/gocql/gocql/ring.go
  vendor/github.com/gocql/gocql/scylla.go
  vendor/github.com/gocql/gocql/scylla_cdc.go
  vendor/github.com/gocql/gocql/session.go
  vendor/github.com/gocql/gocql/token.go
  vendor/github.com/gocql/gocql/topology.go
  vendor/modules.txt
Labels: kind/feature, priority/important-soon

#912 Fix panic in NoeConfig e2e
  test/e2e/set/nodeconfig/nodeconfig_optimizations.go
Labels: priority/important-soon, kind/flake

#911 Explicitly set user/group for all Scylla Pod containers
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
Labels: kind/bug, priority/important-soon

#796 Allow removing empty racks from ScyllaCluster Spec
  pkg/api/validation/cluster_validation.go
  pkg/api/validation/cluster_validation_test.go
  pkg/test/unit/helpers.go
Labels: kind/feature

#924 [v1.7] Pin tags to 1.7
  Makefile
  deploy/manager/dev/50_controller_deployment.yaml
  deploy/manager/prod/50_controller_deployment.yaml
  deploy/operator/50_operator.deployment.yaml
  deploy/operator/50_webhookserver.deployment.yaml
  examples/common/manager.yaml
  examples/common/operator.yaml
  examples/gke/xfs-formatter-daemonset.yaml
  helm/scylla-manager/Chart.yaml
  helm/scylla-operator/Chart.yaml
Labels: priority/important-soon, kind/machinery

#925 Enable building documentation from v1.7
  docs/source/conf.py
Labels: kind/documentation

#926 Tune nodes immediately when tuning DaemonSet is scheduled
  pkg/controller/nodeconfigdaemon/controller.go
  pkg/controller/nodeconfigdaemon/resource.go
  test/e2e/set/nodeconfig/nodeconfig_optimizations.go
Labels: kind/bug, priority/important-soon

#930 Bump release schedule
  docs/source/releases.md
Labels: kind/documentation
