Repository scylladb/scylla-operator, pull requests merged in 2022-03, with the labels that each got.

#952 Expose node-exporter metrics in Scylla Pods
  examples/common/monitoring/scylla-service-monitor.yaml
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
Labels: kind/feature

#957 Pin google cloud SDK
  .github/workflows/go.yaml
Labels: priority/critical-urgent, kind/machinery

#959 [v1.6] Pin google cloud SDK
  .github/workflows/go.yaml
Labels: priority/critical-urgent, kind/machinery

#961 Update Golang to 1.18
  .github/workflows/go.yaml
  Dockerfile
  Makefile
  go.mod
  go.sum
Labels: priority/important-soon, kind/machinery

#960 Reconcile metadata explicitly with apply
  pkg/resourceapply/apps.go
  pkg/resourceapply/apps_test.go
  pkg/resourceapply/batch.go
  pkg/resourceapply/core.go
  pkg/resourceapply/core_test.go
  pkg/resourceapply/policy.go
  pkg/resourceapply/policy_test.go
  pkg/resourceapply/rbac.go
  pkg/resourceapply/rbac_test.go
  pkg/resourcemerge/objectmerger.go
  pkg/resourcemerge/objectmerger_test.go
Labels: kind/feature, priority/important-soon
