Repository scylladb/scylla-operator, pull requests merged in 2023-09, with the labels that each got.

#1364 Migrate leader election to leases only
  pkg/leaderelection/leaderelection.go
Labels: kind/feature, priority/important-soon, lgtm, size/XS, approved

#1370 Bump ScyllaDB to 5.2.7 in examples, Helm charts and e2e suites
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  examples/common/manager.yaml
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  helm/deploy/manager_prod.yaml
  helm/scylla-manager/values.yaml
  helm/scylla/values.yaml
  test/e2e/fixture/scylla/basic.scyllacluster.yaml
  test/e2e/set/scyllacluster/config.go
Labels: kind/machinery, lgtm, size/M, approved

#1321 Expose external seeds in ScyllaCluster
  enhancements/proposals/1304-external-seeds/README.md
  examples/common/operator.yaml
  helm/scylla-manager/values.schema.json
  helm/scylla/values.schema.json
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/types_cluster.go
  pkg/api/scylla/v1/zz_generated.deepcopy.go
  pkg/cmd/operator/sidecar.go
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
  pkg/helpers/array.go
  pkg/helpers/collections.go
  pkg/scyllaclient/client.go
  pkg/sidecar/config/config.go
  pkg/sidecar/identity/member.go
  pkg/sidecar/identity/member_test.go
  test/e2e/set/scyllacluster/scyllacluster_external_seeds.go
  test/e2e/set/scyllacluster/verify.go
  test/e2e/utils/datainserter.go
  test/e2e/utils/helpers.go
Labels: kind/feature, priority/important-soon, lgtm, size/L, approved

#1371 Use generic pointer.Ptr in entire project
  pkg/api/scylla/validation/cluster_validation_test.go
  pkg/controller/manager/sync_test.go
  pkg/controller/manager/types_old.go
  pkg/controller/nodeconfigpod/resource_test.go
  pkg/controller/nodetune/resource.go
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
  pkg/controller/scyllacluster/status.go
  pkg/controller/scyllacluster/sync_certs_test.go
  pkg/controller/scyllacluster/sync_statefulsets.go
  pkg/controller/scylladbmonitoring/status.go
  pkg/controller/scylladbmonitoring/sync_grafana.go
  pkg/controller/scylladbmonitoring/sync_prometheus.go
  pkg/controller/scylladbmonitoring/sync_prometheus_test.go
  pkg/controllerhelpers/apps_test.go
  pkg/controllerhelpers/mergepatch_test.go
  pkg/kubecrypto/certs_test.go
  pkg/pointer/pointer.go
  pkg/resourceapply/apps_test.go
  pkg/resourceapply/core_test.go
  pkg/resourceapply/helpers.go
  pkg/resourceapply/networking_test.go
  pkg/resourceapply/policy_test.go
  pkg/resourceapply/rbac_test.go
  pkg/sidecar/config/config.go
  pkg/test/unit/helpers.go
  test/e2e/set/scyllacluster/scyllacluster_tls.go
  test/e2e/set/scyllacluster/verify.go
  test/e2e/set/scylladbmonitoring/scylladbmonitoring.go
Labels: kind/cleanup, lgtm, size/L, approved

#1382 Increase fs.aio-max-nr on CI worker nodes
  hack/.ci/run-e2e-gke.sh
Labels: priority/critical-urgent, kind/machinery, lgtm, size/M, approved

#1392 Fix hosts comparison after replacement in orphaned PV e2e test
  test/e2e/set/scyllacluster/scyllacluster_pv.go
Labels: kind/failing-test, priority/critical-urgent, lgtm, size/XS, approved

#1391 Fix waiting for waitGroup in ScyllaCluster Orphaned PV e2e test
  test/e2e/set/scyllacluster/scyllacluster_pv.go
Labels: kind/bug, priority/critical-urgent, lgtm, size/XS, approved

#1393 Migrate GH Actions installing Kubernetes to pkgs.k8s.io
  .github/actions/setup-kubernetes/action.yaml
Labels: kind/machinery, lgtm, size/XS, approved

#1388 Fix a race condition in seed election algorithm
  pkg/cmd/operator/sidecar.go
  pkg/cmd/tests/tests_run.go
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
  pkg/controller/scylladbmonitoring/sync_grafana.go
  pkg/controller/scylladbmonitoring/sync_prometheus.go
  pkg/helpers/collections.go
  pkg/helpers/slices/slices.go
  pkg/naming/constants.go
  pkg/naming/labels.go
  pkg/sidecar/identity/member.go
  pkg/sidecar/identity/member_test.go
  pkg/systemd/unit.go
  pkg/systemd/unit_test.go
  test/e2e/set/scyllacluster/scyllacluster_cleanup.go
  test/e2e/set/scyllacluster/verify.go
  test/e2e/utils/datainserter.go
Labels: kind/bug, priority/important-soon, lgtm, size/L, approved

#1359 Add new ways of exposing ScyllaCluster outside
  examples/common/operator.yaml
  helm/scylla-manager/values.schema.json
  helm/scylla/values.schema.json
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/types_cluster.go
  pkg/api/scylla/v1/zz_generated.deepcopy.go
  pkg/api/scylla/validation/cluster_validation.go
  pkg/api/scylla/validation/cluster_validation_test.go
  pkg/cmd/operator/sidecar.go
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
  pkg/controller/scyllacluster/sync.go
  pkg/controller/scyllacluster/sync_certs.go
  pkg/controller/scyllacluster/sync_services.go
  pkg/controller/scyllacluster/sync_statefulsets.go
  pkg/controller/scyllacluster/validation.go
  pkg/helpers/slices/slices.go
  pkg/scyllaclient/config_client.go
  pkg/scyllafeatures/scyllafeatures.go
  pkg/sidecar/config/config.go
  pkg/sidecar/identity/member.go
  pkg/sidecar/identity/member_test.go
  test/e2e/set/scyllacluster/scyllacluster_expose.go
  test/e2e/set/scyllacluster/scyllacluster_tls.go
  test/e2e/utils/helpers.go
Labels: lgtm, size/XXL, approved

#1401 Annotate E2E namespaces with parallel process and full text of a ginkgo node
  test/e2e/framework/framework.go
Labels: kind/machinery, lgtm, size/XS, approved

#1404 Fix typo in alternator documentation
  docs/source/generic.md
Labels: kind/documentation, lgtm, size/XS, approved, ok-to-test

#1407 Promote automatic client to node TLS certificates to beta
  pkg/features/features.go
Labels: kind/feature, priority/important-soon, lgtm, size/XS, approved

#1417 Remove artificial sleep for stale conntrack entries from E2E tests
  test/e2e/utils/helpers.go
Labels: kind/cleanup, lgtm, size/XS, approved

#1423 Fix the cluster label selector in e2e helpers
  pkg/naming/labels.go
  test/e2e/utils/helpers.go
Labels: priority/important-soon, kind/flake, lgtm, size/XS, approved

#1430 Fix must-gather podman command in postsubmit's 'Dump cluster state' job
  .github/actions/run-e2e/action.yaml
Labels: kind/bug, kind/machinery, lgtm, size/XS, approved

#1431 Fix logs in orphaned PV controller
  pkg/controller/orphanedpv/sync.go
Labels: kind/bug, lgtm, size/S, approved
