Repository scylladb/scylla-operator, pull requests merged in 2023-11, with the labels that each got.

#1509 Unify docs index pages and make sure they are always in sync with the menu
  docs/source/multidc/index.rst
  docs/source/nodeoperations/index.rst
Labels: kind/documentation, priority/important-longterm, lgtm, size/S, approved

#1504 Add support and must-gather documentation
  docs/source/index.rst
  docs/source/support/index.rst
  docs/source/support/known-issues.md
  docs/source/support/must-gather.md
  docs/source/support/overview.md
  docs/source/support/troubleshooting/index.rst
  docs/source/support/troubleshooting/installation.md
Labels: priority/important-soon, kind/documentation, lgtm, size/L, approved

#1518 [v1.11] Add support and must-gather documentation
  docs/source/index.rst
  docs/source/support/index.rst
  docs/source/support/known-issues.md
  docs/source/support/must-gather.md
  docs/source/support/overview.md
  docs/source/support/troubleshooting/index.rst
  docs/source/support/troubleshooting/installation.md
Labels: priority/important-soon, kind/documentation, lgtm, size/L, approved

#1522 Fix GH Action installing kubernetes
  .github/actions/setup-kubernetes/action.yaml
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#1521 Use correct key in error message when getting agent token
  pkg/helpers/agent.go
Labels: kind/cleanup, priority/important-longterm, lgtm, size/XS, approved

#1515 Avoid service enpoints size limit in monitoring examples
  docs/source/monitoring.md
  examples/monitoring/v1alpha1/scylladbmonitoring.yaml
  test/e2e/fixture/scylla/scylladbmonitoring.yaml.tmpl
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved

#1524 Generalise naming of networking's parsing helpers
  pkg/controller/scyllacluster/sync_certs.go
  pkg/helpers/networking.go
  test/e2e/set/scyllacluster/scyllacluster_expose.go
  test/e2e/set/scyllacluster/scyllacluster_tls.go
Labels: kind/cleanup, priority/important-longterm, lgtm, size/S, approved

#1513 Describe Manager and Monitoring in MultiDC docs
  docs/source/multidc/multidc.md
Labels: priority/important-soon, kind/documentation, lgtm, size/M, approved

#1527 Make example ScyllaCluster in EKS docs consistently use scylladb-local-xfs storage class
  examples/eks/cluster.yaml
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved

#1418 Replace recommonmark with MyST-Parser in docs
  .gitignore
  docs/poetry.lock
  docs/pyproject.toml
  docs/source/_ext/scylladb_markdown.py
  docs/source/conf.py
  docs/source/exposing.md
  docs/source/generic.md
  docs/source/gke.md
  docs/source/multidc/eks.md
  docs/source/multidc/gke.md
  docs/source/multidc/multidc.md
  docs/source/support/must-gather.md
  docs/source/support/troubleshooting/installation.md
Labels: priority/backlog, kind/machinery, lgtm, size/L, approved

#1529 Remove myst.xref_missing suppression in Sphinx config
  docs/source/_ext/scylladb_markdown.py
  docs/source/eks.md
  docs/source/gke.md
  docs/source/multidc/multidc.md
Labels: kind/documentation, kind/cleanup, priority/critical-urgent, lgtm, size/S, approved

#1528 Bump gocql to scylladb/gocql@v1.12.0
  go.mod
  go.sum
  vendor/github.com/gocql/gocql/AUTHORS
  vendor/github.com/gocql/gocql/CONTRIBUTING.md
  vendor/github.com/gocql/gocql/README.md
  vendor/github.com/gocql/gocql/cluster.go
  vendor/github.com/gocql/gocql/conn.go
  vendor/github.com/gocql/gocql/connectionpool.go
  vendor/github.com/gocql/gocql/control.go
  vendor/github.com/gocql/gocql/debug_off.go
  vendor/github.com/gocql/gocql/debug_on.go
  vendor/github.com/gocql/gocql/dial.go
  vendor/github.com/gocql/gocql/doc.go
  vendor/github.com/gocql/gocql/docker-compose.yml
  vendor/github.com/gocql/gocql/errors.go
  vendor/github.com/gocql/gocql/events.go
  vendor/github.com/gocql/gocql/exec.go
  vendor/github.com/gocql/gocql/frame.go
  vendor/github.com/gocql/gocql/fuzz.go
  vendor/github.com/gocql/gocql/helpers.go
  vendor/github.com/gocql/gocql/host_source.go
  vendor/github.com/gocql/gocql/host_source_gen.go
  vendor/github.com/gocql/gocql/integration.sh
  vendor/github.com/gocql/gocql/internal/streams/streams.go
  vendor/github.com/gocql/gocql/marshal.go
  vendor/github.com/gocql/gocql/metadata_cassandra.go
  vendor/github.com/gocql/gocql/policies.go
  vendor/github.com/gocql/gocql/query_executor.go
  vendor/github.com/gocql/gocql/recreate.go
  vendor/github.com/gocql/gocql/ring.go
  vendor/github.com/gocql/gocql/scylla.go
  vendor/github.com/gocql/gocql/session.go
  vendor/github.com/gocql/gocql/version.go
  vendor/modules.txt
Labels: kind/feature, priority/important-soon, lgtm, size/XXL, approved, area/dependency

#1531 [v1.11] Describe Manager and Monitoring in MultiDC docs
  docs/source/multidc/multidc.md
Labels: priority/important-soon, kind/documentation, lgtm, size/M, approved

#1536 [v1.11] Catch up poetry to 1.5 and fix path detection
  .github/actions/docs/build/action.yaml
  .github/actions/docs/setup/action.yaml
  .github/workflows/docs_build.yaml
  .github/workflows/docs_deploy.yaml
  docs/Makefile
  docs/README-dev.md
  docs/hack/install-poetry.sh
  docs/poetry.lock
Labels: priority/important-soon, kind/machinery, lgtm, size/XL, approved

#1537 [v1.11] Update ScyllaDB Documentation Theme to 1.6
  docs/Makefile
  docs/poetry.lock
  docs/pyproject.toml
  docs/source/conf.py
Labels: priority/important-soon, kind/machinery, lgtm, size/L, approved

#1538 [v1.11] Fix GH Action installing kubernetes
  .github/actions/setup-kubernetes/action.yaml
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#1530 [v1.11] Replace recommonmark with MyST-Parser in docs
  .gitignore
  docs/poetry.lock
  docs/pyproject.toml
  docs/source/_ext/scylladb_markdown.py
  docs/source/conf.py
  docs/source/exposing.md
  docs/source/generic.md
  docs/source/gke.md
  docs/source/multidc/eks.md
  docs/source/multidc/gke.md
  docs/source/multidc/multidc.md
  docs/source/support/must-gather.md
  docs/source/support/troubleshooting/installation.md
Labels: priority/important-soon, kind/machinery, lgtm, size/L, approved

#1534 [v1.11] Remove myst.xref_missing suppression in Sphinx config
  docs/source/_ext/scylladb_markdown.py
  docs/source/eks.md
  docs/source/gke.md
  docs/source/multidc/multidc.md
Labels: priority/important-soon, kind/documentation, kind/cleanup, lgtm, size/S, approved

#1535 Make 1.11 docs use MyST
  docs/source/conf.py
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#1545 Update support matrix
  docs/source/releases.md
Labels: priority/important-soon, kind/documentation, lgtm, size/S, approved

#1544 Update release schedule
  docs/source/releases.md
Labels: priority/important-soon, kind/documentation, lgtm, size/XS, approved

#1543 Mark 1.11 as stable version in documentation
  docs/source/conf.py
Labels: priority/important-soon, kind/documentation, lgtm, size/XS, approved

#1547 Avoid controller-gen issue with path parsing
  Makefile
Labels: kind/flake, priority/important-longterm, lgtm, size/XS, approved

#1549 Update GitHub issue templates
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/ci-flake.yaml
  .github/ISSUE_TEMPLATE/feature-request.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: priority/important-soon, kind/machinery, lgtm, size/L, approved

#1550 Fix a duplicate id in GitHub 'Feature request' issue template
  .github/ISSUE_TEMPLATE/feature-request.yaml
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#1532 Move aggregated deploy manifests to deploy folder
  Makefile
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/operator.yaml
  docs/source/generic.md
  docs/source/manager.md
  docs/source/migration.md
  docs/source/upgrade.md
Labels: priority/important-longterm, kind/machinery, lgtm, size/L, approved

#1553 Fix crd tmpdir location in Makefile
  Makefile
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#1552 Generate aggregated third-party manifests
  Makefile
  examples/third-party/haproxy-ingress.yaml
  examples/third-party/prometheus-operator.yaml
Labels: priority/important-soon, kind/machinery, lgtm, size/XXL, approved

#1562 Collect CRDs in must-gather
  go.mod
  pkg/cmd/operator/mustgather.go
  pkg/cmd/operator/mustgather_test.go
Labels: kind/feature, priority/important-longterm, lgtm, size/S, approved, area/dependency

#1564 Add ScyllaCluster and scylla config examples
  examples/scylladb/scylla-config.cm.yaml
  examples/scylladb/scylla.scyllacluster.yaml
Labels: priority/important-soon, kind/machinery, lgtm, size/M, approved

#1565 Generelize GKE NodeConfig so it can be faked on libvirt
  examples/gke/nodeconfig-alpha.yaml
Labels: priority/important-soon, kind/cleanup, lgtm, size/XS, approved

#1567 Fix scylladb example so it deploys on default gke nodes
  examples/scylladb/scylla.scyllacluster.yaml
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#1569 Fix error aggregation in scyllacluster controller job sync
  pkg/controller/scyllacluster/sync_jobs.go
Labels: kind/bug, priority/important-soon, lgtm, size/XS, approved

#1584 Check for presence of ARTIFACTS env var in e2e script
  hack/.ci/run-e2e-gke.sh
Labels: priority/important-longterm, kind/machinery, lgtm, size/XS, approved

#1585 Trap unblocking functions in e2e script's subprocesses
  hack/.ci/run-e2e-gke.sh
Labels: priority/important-longterm, kind/machinery, lgtm, size/S, approved

#1586 Update outdated hyperlink to GKE's raw block devices docs in GKE docs
  docs/source/gke.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved

#1591 [v1.11] Update outdated hyperlink to GKE's raw block devices docs in GKE docs
  docs/source/gke.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved

#1595 Set kubelet's CPU manager policy for ScyllaDB node pool only in GKE docs and examples
  docs/source/gke.md
  examples/gke/gke.sh
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved

#1597 Fix Operator deployment in GKE and EKS example scripts
  examples/eks/eks.sh
  examples/gke/gke.sh
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#1596 Fix invalid commands in Scylla Manager section of GKE mulit-datacenter documentation
  docs/source/multidc/multidc.md
Labels: priority/important-soon, kind/documentation, lgtm, size/XS, approved

#1599 [v1.11] Fix invalid commands in Scylla Manager section of GKE mulit-datacenter documentation
  docs/source/multidc/multidc.md
Labels: priority/important-soon, kind/documentation, lgtm, size/XS, approved

#1602 Update grafana UBI image
  assets/monitoring/grafana/v1alpha1/deployment.yaml
Labels: kind/feature, priority/important-soon, lgtm, size/XS, approved

#1560 Add Scylla Operator demo
  .gitattributes
  recordings/basic-setup/Makefile
  recordings/basic-setup/README.md
  recordings/basic-setup/run.cast
  recordings/basic-setup/run.sh
Labels: priority/important-soon, kind/documentation, lgtm, size/XXL, approved

#1601 Add examples for popular platforms regarding LoadBalancer service exposing
  docs/poetry.lock
  docs/pyproject.toml
  docs/source/conf.py
  docs/source/exposing.md
Labels: priority/important-soon, kind/documentation, lgtm, size/M, approved

#1613 Support `scyllaArgs` in Helm chart
  helm/scylla/templates/scyllacluster.yaml
  helm/scylla/values.yaml
Labels: needs-priority, lgtm, size/XS, approved, ok-to-test, do-not-merge/needs-kind
