Repository scylladb/scylla-operator, pull requests merged in 2023-12, with the labels that each got.

#1610 Update ScyllaDB version to 5.2.11
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  docs/source/generic.md
  docs/source/multidc/multidc.md
  docs/source/performance.md
  docs/source/scylla-cluster-crd.md
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  examples/scylladb/scylla.scyllacluster.yaml
  helm/deploy/manager_prod.yaml
  helm/scylla-manager/values.yaml
  helm/scylla/values.yaml
  test/e2e/fixture/scylla/basic.scyllacluster.yaml
  test/e2e/set/scyllacluster/config.go
Labels: kind/feature, priority/important-soon, lgtm, size/M, approved

#1615 Limit scylla manager API calls duration
  pkg/cmd/operator/manager_controller.go
  pkg/controller/manager/controller.go
  pkg/mermaidclient/client.go
  test/e2e/utils/helpers.go
Labels: priority/important-soon, kind/flake, lgtm, size/M, approved

#1616 Remove image publishing in favour of Prow
  .github/actions/run-e2e/action.yaml
  .github/actions/setup-kubernetes/action.yaml
  .github/actions/setup-local-volume-provisioner/action.yaml
  .github/actions/setup-local-volume-provisioner/manifests/local-csi-driver/00_namespace.yaml
  .github/actions/setup-local-volume-provisioner/manifests/local-csi-driver/10_csidriver.yaml
  .github/actions/setup-local-volume-provisioner/manifests/local-csi-driver/10_driver_serviceaccount.yaml
  .github/actions/setup-local-volume-provisioner/manifests/local-csi-driver/10_provisioner_clusterrole.yaml
  .github/actions/setup-local-volume-provisioner/manifests/local-csi-driver/20_provisioner_clusterrolebinding.yaml
  .github/actions/setup-local-volume-provisioner/manifests/local-csi-driver/50_daemonset.yaml
  .github/actions/setup-local-volume-provisioner/manifests/storageclass_xfs.yaml
  .github/workflows/go.yaml
Labels: priority/important-soon, kind/machinery, lgtm, size/XXL, approved

#1620 [v1.11] Adjust image references for introspection with containerd
  pkg/cmd/operator/operator.go
Labels: kind/bug, priority/important-soon, lgtm, size/S, approved

#1606 Update ScyllaDB to 5.4.0
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  docs/source/generic.md
  docs/source/multidc/multidc.md
  docs/source/performance.md
  docs/source/scylla-cluster-crd.md
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  examples/scylladb/scylla.scyllacluster.yaml
  helm/deploy/manager_prod.yaml
  helm/scylla-manager/values.yaml
  helm/scylla/values.yaml
  test/e2e/fixture/scylla/basic.scyllacluster.yaml
  test/e2e/set/scyllacluster/config.go
Labels: kind/feature, priority/important-soon, lgtm, size/M, approved

#1625 Move e2e namespace initialization before Operator deployment
  hack/.ci/run-e2e-gke.sh
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#1598 Gracefully evict Pods on ScyllaDB node replacements
  pkg/controller/scyllacluster/sync_services.go
Labels: kind/feature, priority/important-soon, lgtm, size/S, approved

#1631 Allow Ingress Controller to notice Ingress objects in connection via Ingress E2E
  test/e2e/set/scyllacluster/scyllacluster_expose.go
Labels: priority/important-soon, kind/flake, lgtm, size/S, approved

#1634 Fix default ServiceAccount awaiting in E2E framework
  test/e2e/framework/framework.go
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#1636 Extend ScyllaCluster rollout timeout in E2E
  test/e2e/utils/config.go
  test/e2e/utils/helpers.go
Labels: priority/important-soon, kind/flake, lgtm, size/XS, approved

#1639 Rollback StatefulSet selector
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
  pkg/controller/scyllacluster/sync_statefulsets.go
  pkg/helpers/collections.go
  pkg/naming/labels.go
Labels: kind/bug, priority/critical-urgent, lgtm, size/M, approved

#1643 [v1.11] Rollback StatefulSet selector
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
  pkg/controller/scyllacluster/sync_statefulsets.go
  pkg/helpers/collections.go
  pkg/naming/labels.go
Labels: kind/bug, priority/critical-urgent, lgtm, size/M, approved

#1646 Fix workouround for controler-gen interpreting numbers in file paths
  Makefile
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#1603 Update Scylla Manager to 3.2.5
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_manager_deployment.yaml
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_manager_deployment.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  docs/source/generic.md
  docs/source/multidc/multidc.md
  docs/source/performance.md
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  examples/scylladb/scylla.scyllacluster.yaml
  helm/deploy/manager_prod.yaml
  helm/scylla-manager/values.yaml
  helm/scylla/values.yaml
  test/e2e/fixture/scylla/basic.scyllacluster.yaml
Labels: kind/feature, priority/important-soon, lgtm, size/M, approved

#1641 Determine host for Scylla client using ScyllaCluster expose options
  pkg/controller/scyllacluster/sync_statefulsets.go
  pkg/controllerhelpers/scylla.go
  pkg/controllerhelpers/scylla_test.go
  pkg/naming/names.go
  pkg/sidecar/identity/member.go
  pkg/sidecar/identity/member_test.go
  pkg/sidecar/probes.go
Labels: kind/bug, priority/critical-urgent, lgtm, size/XL, approved

#1651 [v1.11] Determine host for Scylla client using ScyllaCluster expose options
  pkg/controller/scyllacluster/sync_statefulsets.go
  pkg/controllerhelpers/scylla.go
  pkg/controllerhelpers/scylla_test.go
  pkg/naming/names.go
  pkg/sidecar/identity/member.go
  pkg/sidecar/identity/member_test.go
  pkg/sidecar/probes.go
Labels: kind/bug, priority/critical-urgent, lgtm, size/XL, approved

#1649 Loosen validation for LoadBalancerClass in NodeServiceTemplate
  pkg/api/scylla/validation/cluster_validation.go
  pkg/api/scylla/validation/cluster_validation_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/S, approved

#1650 [v1.11] Loosen validation for LoadBalancerClass in NodeServiceTemplate
  pkg/api/scylla/validation/cluster_validation.go
  pkg/api/scylla/validation/cluster_validation_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/S, approved

#1652 Update local volume provisioner for CI
  hack/.ci/manifests/cluster/nodeconfig.yaml
  hack/.ci/manifests/namespaces/local-csi-driver/50_daemonset.yaml
Labels: priority/important-soon, kind/machinery, lgtm, size/S, approved

#1624 Fix StatefulSet rolled out condition
  pkg/controllerhelpers/apps.go
  pkg/controllerhelpers/apps_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/M, approved

#1656 Update local volume provisioner to v0.3.0
  examples/common/local-volume-provisioner/local-csi-driver/00_scylladb-local-xfs.storageclass.yaml
  examples/common/local-volume-provisioner/local-csi-driver/10_driver.serviceaccount.yaml
  examples/common/local-volume-provisioner/local-csi-driver/50_daemonset.yaml
  hack/.ci/manifests/namespaces/local-csi-driver/50_daemonset.yaml
Labels: kind/feature, priority/important-soon, lgtm, size/S, approved

#1655 Support update of StatefulSet selector
  pkg/resourceapply/apps.go
  pkg/resourceapply/apps_test.go
  pkg/resourceapply/batch.go
  pkg/resourceapply/helpers.go
  pkg/resourceapply/rbac.go
Labels: kind/bug, priority/critical-urgent, lgtm, size/L, approved

#1660 [v1.11] Support update of StatefulSet selector
  pkg/resourceapply/apps.go
  pkg/resourceapply/apps_test.go
  pkg/resourceapply/batch.go
  pkg/resourceapply/helpers.go
  pkg/resourceapply/rbac.go
Labels: kind/bug, priority/critical-urgent, lgtm, size/L, approved

#1541 Generate API docs
  .gitignore
  Makefile
  cmd/gen-api-reference/gen-api-reference.go
  deploy/operator.yaml
  docs/source/api-reference/groups/scylla.scylladb.com.rst
  docs/source/api-reference/groups/scylla.scylladb.com/nodeconfigs.rst
  docs/source/api-reference/groups/scylla.scylladb.com/scyllaclusters.rst
  docs/source/api-reference/groups/scylla.scylladb.com/scylladbmonitorings.rst
  docs/source/api-reference/groups/scylla.scylladb.com/scyllaoperatorconfigs.rst
  docs/source/api-reference/index.rst
  docs/source/api-reference/templates/group.rst.tmpl
  docs/source/api-reference/templates/kind.rst.tmpl
  docs/source/generic.md
  docs/source/helm.md
  docs/source/index.rst
  docs/source/manager.md
  docs/source/scylla-cluster-crd.md
  pkg/api/scylla/v1alpha1/scylla.scylladb.com_scyllaoperatorconfigs.yaml
  pkg/api/scylla/v1alpha1/types_operatorconfig.go
  pkg/assets/template.go
  pkg/cmd/generateapireference/cmd.go
  pkg/cmd/generateapireference/options.go
  pkg/cmd/generateapireference/run.go
  pkg/cmd/generateapireference/run_test.go
  pkg/cmd/generateapireference/scheme.go
Labels: kind/documentation, priority/important-longterm, kind/machinery, lgtm, size/XXL, approved, area/dependency

#1508 Make E2E suite expose ScyllaClusters on PodIPs by default
  hack/.ci/run-e2e-gke.sh
  pkg/cmd/tests/options.go
  pkg/cmd/tests/tests_run.go
  test/e2e/fixture/scylla/registry.go
  test/e2e/fixture/scylla/scyllacluster.yaml.tmpl
  test/e2e/framework/framework.go
  test/e2e/framework/meta.go
  test/e2e/framework/testcontext.go
  test/e2e/set/nodeconfig/nodeconfig_optimizations.go
  test/e2e/set/scyllacluster/scyllacluster_auth.go
  test/e2e/set/scyllacluster/scyllacluster_cleanup.go
  test/e2e/set/scyllacluster/scyllacluster_evictions.go
  test/e2e/set/scyllacluster/scyllacluster_expose.go
  test/e2e/set/scyllacluster/scyllacluster_external_seeds.go
  test/e2e/set/scyllacluster/scyllacluster_hostid.go
  test/e2e/set/scyllacluster/scyllacluster_pv.go
  test/e2e/set/scyllacluster/scyllacluster_rebootstrap.go
  test/e2e/set/scyllacluster/scyllacluster_replace.go
  test/e2e/set/scyllacluster/scyllacluster_sa.go
  test/e2e/set/scyllacluster/scyllacluster_scaling.go
  test/e2e/set/scyllacluster/scyllacluster_shardawareness.go
  test/e2e/set/scyllacluster/scyllacluster_sysctl.go
  test/e2e/set/scyllacluster/scyllacluster_tls.go
  test/e2e/set/scyllacluster/scyllacluster_updates.go
  test/e2e/set/scyllacluster/scyllacluster_upgrades.go
  test/e2e/set/scyllacluster/scyllacluster_webhooks.go
  test/e2e/set/scyllacluster/scyllamanager.go
  test/e2e/set/scyllacluster/verify.go
  test/e2e/set/scylladbmonitoring/scylladbmonitoring.go
  test/e2e/utils/helpers.go
Labels: kind/feature, priority/important-soon, lgtm, size/XL, approved
