Repository scylladb/scylla-operator, pull requests merged in 2023-04, with the labels that each got.

#1197 Add missing symlink to ScyllaDBMonitoring CRD in helm CRDs
  helm/scylla-operator/crds/00_scylla.scylladb.com_scylladbmonitorings.yaml
Labels: kind/bug, priority/important-longterm

#1198 Fix PrometheusExposeOptions struct name in API definitions
  pkg/api/scylla/v1alpha1/types_monitoring.go
  pkg/api/scylla/v1alpha1/zz_generated.deepcopy.go
Labels: priority/important-soon, kind/cleanup

#1199 Fix "job" labels in Grafana dashboards' queries
  assets/monitoring/grafana/v1alpha1/dashboards.cm.yaml
Labels: kind/bug, priority/important-soon

#1211 Replace deprecated GCP Auth with a dedicated GitHub action
  .github/workflows/go.yaml
Labels: priority/important-soon, kind/machinery

#1214 Cleanup tune2fs_test.sh
  hack/test/gke/xfs-formatter/tune2fs_test.sh
Labels: kind/cleanup, priority/important-longterm

#1221 Fix node setup image in EKS example
  examples/eks/node-setup-daemonset.yaml
Labels: kind/bug, priority/critical-urgent

#1224 [v1.8] Fix node setup image in EKS example
  examples/eks/node-setup-daemonset.yaml
Labels: kind/bug, priority/critical-urgent
