Repository scylladb/scylla-operator, pull requests merged in 2023-02, with the labels that each got.

#1159 Make preleases even for alpha version to be easy to consume
  .github/workflows/releases.yaml
Labels: priority/important-soon, kind/machinery

#1162 Fix eventual waiting in monitoring e2e
  test/e2e/set/scylladbmonitoring/scylladbmonitoring.go
Labels: priority/important-soon, kind/flake

#1158 Switch cgroup manager from systemd to cgroupfs
  .github/actions/setup-kubernetes/action.yaml
Labels: priority/important-soon, kind/machinery

#1164 Fix serial job artifact names
  .github/workflows/go.yaml
Labels: priority/important-soon, kind/machinery

#1165 Add support for tuning EKS 1.24 using containerd CRI
  pkg/controller/nodeconfigdaemon/tune.go
Labels: kind/feature, priority/important-soon

#1131 Fix NodeConfigPod controller to exclusively enqueue and sync Scylla Pods
  pkg/controller/nodeconfigpod/controller.go
  pkg/controller/nodeconfigpod/sync.go
  pkg/controller/scyllacluster/controller.go
  pkg/controllerhelpers/handlers.go
  pkg/controllerhelpers/scylla.go
Labels: kind/bug, priority/important-soon

#1166 Remove CC from Slack failure report
  .github/workflows/go.yaml
Labels: priority/important-longterm, kind/machinery

#1168 Fix kubelet cgroup slices in CI setup
  .github/actions/setup-kubernetes/action.yaml
Labels: priority/important-soon, priority/critical-urgent, kind/machinery

#1169 Tune kubelet config in CI
  .github/actions/setup-kubernetes/action.yaml
Labels: priority/important-soon, kind/machinery

#1170 Set explicit timeouts for our main GH actions workflow
  .github/workflows/go.yaml
Labels: priority/important-soon, kind/machinery

#1163 Fix crypto unit test not to capture loop variable
  pkg/crypto/certcreators_test.go
Labels: priority/important-soon, kind/flake

#1173 Fix GH action setting up Kubernetes
  .github/actions/setup-kubernetes/action.yaml
Labels: priority/important-soon, kind/machinery
