Repository scylladb/scylla-operator, pull requests merged in 2023-10, with the labels that each got.

#1425 Introspect operator image to prevent skew with the sidecar
  deploy/operator/50_operator.deployment.yaml
  examples/common/operator.yaml
  helm/scylla-operator/templates/operator.deployment.yaml
  pkg/cmd/operator/operator.go
Labels: lgtm, size/L, approved

#1419 Add notes about system_auth RF configuration to the documentation
  docs/source/generic.md
Labels: priority/important-soon, kind/documentation, lgtm, size/M, approved

#1406 Add enhancement proposal to support Alternator API
  enhancements/proposals/1405-alternator/README.md
Labels: lgtm, size/L, approved

#1076 E2E for cluster connection via Ingress
  .github/actions/run-e2e/action.yaml
  hack/.ci/run-e2e-gke.sh
  pkg/cmd/tests/options.go
  pkg/cmd/tests/tests_run.go
  test/e2e/fixture/scylla/scylladbmonitoring.yaml.tmpl
  test/e2e/framework/framework.go
  test/e2e/framework/testcontext.go
  test/e2e/set/scyllacluster/scyllacluster_expose.go
  test/e2e/set/scyllacluster/verify.go
  test/e2e/set/scylladbmonitoring/scylladbmonitoring.go
  test/e2e/utils/datainserter.go
  test/e2e/utils/helpers.go
  vendor/github.com/gocql/gocql/scyllacloud/cluster.go
  vendor/github.com/gocql/gocql/scyllacloud/config.go
  vendor/github.com/gocql/gocql/scyllacloud/hostdialer.go
  vendor/modules.txt
Labels: kind/feature, priority/important-soon, lgtm, size/XL, approved

#1442 Remove explicit copying of replace label between Service instances
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
  test/e2e/set/scyllacluster/scyllacluster_replace.go
Labels: kind/bug, lgtm, size/M, approved

#1445 Enable building v1.11 documentation
  docs/source/conf.py
Labels: kind/documentation, lgtm, size/XS, approved

#1444 [v1.11] Pin tags to 1.11
  Makefile
  deploy/manager/dev/50_controller_deployment.yaml
  deploy/manager/prod/50_controller_deployment.yaml
  deploy/operator/50_operator.deployment.yaml
  deploy/operator/50_webhookserver.deployment.yaml
  examples/common/manager.yaml
  examples/common/operator.yaml
  helm/scylla-manager/Chart.yaml
  helm/scylla-operator/Chart.yaml
Labels: kind/machinery, lgtm, size/S, approved

#1443 Enable orphaned PV e2e test on envs with multiple Nodes
  test/e2e/set/scyllacluster/scyllacluster_pv.go
Labels: kind/machinery, lgtm, size/M, approved

#1450 Explicitly set TLS CQL shard aware port
  assets/scylladb/defaultconfig.yaml
  pkg/sidecar/config/config_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/XS, approved

#1451 [v1.11] Explicitly set TLS CQL shard aware port
  assets/scylladb/defaultconfig.yaml
  pkg/sidecar/config/config_test.go
Labels: kind/bug, priority/important-soon, lgtm, approved

#1453 Fix namespaced must-gather
  pkg/cmd/operator/gather.go
  pkg/cmd/operator/gatherbase.go
  pkg/cmd/operator/mustgather.go
  pkg/cmd/operator/mustgather_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/L, approved

#1457 [v1.11] Fix namespaced must-gather
  pkg/cmd/operator/gather.go
  pkg/cmd/operator/gatherbase.go
  pkg/cmd/operator/mustgather.go
  pkg/cmd/operator/mustgather_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/L, approved

#1470 Bump Go version to 1.21
  .github/workflows/go.yaml
  .github/workflows/releases.yaml
  Dockerfile
  Makefile
  go.mod
  go.sum
Labels: priority/important-soon, kind/machinery, lgtm, size/S, approved, area/dependency

#1472 Use the same tag version of gen-release-notes when preparing them
  .github/workflows/releases.yaml
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#1473 [v1.11] Use the same tag version of gen-release-notes when preparing them
  .github/workflows/releases.yaml
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#1456 Update ScyllaDB Monitoring to 4.4.5
  assets/monitoring/grafana/v1alpha1/dashboards-platform.cm.yaml
  assets/monitoring/grafana/v1alpha1/dashboards-saas.cm.yaml
  assets/monitoring/grafana/v1alpha1/dashboards.cm.yaml
  assets/monitoring/grafana/v1alpha1/dashboards/platform/advanced.json
  assets/monitoring/grafana/v1alpha1/dashboards/platform/alternator.json
  assets/monitoring/grafana/v1alpha1/dashboards/platform/cql.json
  assets/monitoring/grafana/v1alpha1/dashboards/platform/detailed.json
  assets/monitoring/grafana/v1alpha1/dashboards/platform/ks.json
  assets/monitoring/grafana/v1alpha1/dashboards/platform/manager.json
  assets/monitoring/grafana/v1alpha1/dashboards/platform/os.json
  assets/monitoring/grafana/v1alpha1/dashboards/platform/overview.json
  assets/monitoring/grafana/v1alpha1/dashboards/saas/overview.json
  assets/monitoring/grafana/v1alpha1/deployment.yaml
  assets/monitoring/grafana/v1alpha1/registry.go
  assets/monitoring/prometheus/v1/alerts.prometheusrule.yaml
  assets/monitoring/prometheus/v1/prometheus.yaml
  assets/monitoring/prometheus/v1/recording.prometheusrule.yaml
  pkg/controller/scylladbmonitoring/sync_grafana.go
  pkg/controller/scylladbmonitoring/sync_grafana_test.go
  pkg/controller/scylladbmonitoring/sync_prometheus_test.go
Labels: kind/feature, priority/important-soon, lgtm, size/XXL, approved

#1477 [v1.11] Update ScyllaDB Monitoring to 4.4.5
  assets/monitoring/grafana/v1alpha1/dashboards-platform.cm.yaml
  assets/monitoring/grafana/v1alpha1/dashboards-saas.cm.yaml
  assets/monitoring/grafana/v1alpha1/dashboards.cm.yaml
  assets/monitoring/grafana/v1alpha1/dashboards/platform/advanced.json
  assets/monitoring/grafana/v1alpha1/dashboards/platform/alternator.json
  assets/monitoring/grafana/v1alpha1/dashboards/platform/cql.json
  assets/monitoring/grafana/v1alpha1/dashboards/platform/detailed.json
  assets/monitoring/grafana/v1alpha1/dashboards/platform/ks.json
  assets/monitoring/grafana/v1alpha1/dashboards/platform/manager.json
  assets/monitoring/grafana/v1alpha1/dashboards/platform/os.json
  assets/monitoring/grafana/v1alpha1/dashboards/platform/overview.json
  assets/monitoring/grafana/v1alpha1/dashboards/saas/overview.json
  assets/monitoring/grafana/v1alpha1/deployment.yaml
  assets/monitoring/grafana/v1alpha1/registry.go
  assets/monitoring/prometheus/v1/alerts.prometheusrule.yaml
  assets/monitoring/prometheus/v1/prometheus.yaml
  assets/monitoring/prometheus/v1/recording.prometheusrule.yaml
  pkg/controller/scylladbmonitoring/sync_grafana.go
  pkg/controller/scylladbmonitoring/sync_grafana_test.go
  pkg/controller/scylladbmonitoring/sync_prometheus_test.go
Labels: kind/feature, priority/important-soon, lgtm, size/XXL, approved

#1459 Reenable E2E test for shard-aware ports
  test/e2e/set/scyllacluster/scyllacluster_shardawareness.go
Labels: priority/important-soon, kind/failing-test, lgtm, size/S, approved

#1466 Add Multi Datacenter ScyllaDB cluster deployment documentation
  docs/source/index.rst
  docs/source/multidc/eks.md
  docs/source/multidc/gke.md
  docs/source/multidc/index.rst
  docs/source/multidc/multidc.md
Labels: priority/important-soon, kind/documentation, lgtm, size/XL, approved

#1487 Add 'externalSeeds' support to ScyllaDB Helm chart
  helm/scylla/templates/scyllacluster.yaml
Labels: priority/important-longterm, kind/machinery, lgtm, size/XS, approved

#1491 [v1.11] Add 'externalSeeds' support to ScyllaDB Helm chart
  helm/scylla/templates/scyllacluster.yaml
Labels: priority/important-longterm, kind/machinery, lgtm, size/XS, approved

#1493 Set ScyllaCluster placement requirements on cleanup Jobs
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/L, approved

#1495 [v1.11] Set ScyllaCluster placement requirements on cleanup Jobs
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/L, approved

#1496 Fix example file in 'Setting up nodes for ScyllaDB' of 'Deploying Scylla on EKS' documentation page
  docs/source/eks.md
Labels: needs-priority, lgtm, size/XS, approved, do-not-merge/needs-kind

#1498 [v1.11] Fix example file in 'Setting up nodes for ScyllaDB' of 'Deploying Scylla on EKS' documentation page
  docs/source/eks.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved

#1494 Update dependencies
  go.mod
  go.sum
  vendor/github.com/aws/aws-sdk-go-v2/config/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/config/env_config.go
  vendor/github.com/aws/aws-sdk-go-v2/config/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/config/resolve.go
  vendor/github.com/cloudflare/circl/ecc/goldilocks/twist.go
  vendor/github.com/cloudflare/circl/internal/sha3/keccakf.go
  vendor/github.com/cloudflare/circl/internal/sha3/sha3.go
  vendor/github.com/cloudflare/circl/internal/sha3/shake.go
  vendor/github.com/cloudflare/circl/math/primes.go
  vendor/github.com/cloudflare/circl/sign/ed25519/ed25519.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/LICENSE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/NOTICE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/.gitignore
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/Makefile
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/decode.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/doc.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/encode.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/go.starlark.net/starlark/int.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/attributes/attributes.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/encoding/encoding.go
  vendor/google.golang.org/grpc/internal/backoff/backoff.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/status/status.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/tap/tap.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
  vendor/modules.txt
Labels: kind/feature, priority/important-soon, lgtm, size/XL, approved, area/dependency

#1499 [v1.11] Fix steps ordering in EKS and GKE documentation pages
  docs/source/eks.md
  docs/source/gke.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/S, approved

#1500 [v1.11] Don't use docs CI from master
  .github/workflows/docs_deploy.yaml
Labels: priority/critical-urgent, kind/machinery, lgtm, size/XS, approved

#1460 Update ScyllaDB Documentation Theme to 1.6
  docs/Makefile
  docs/poetry.lock
  docs/pyproject.toml
  docs/source/conf.py
Labels: priority/important-longterm, kind/machinery, lgtm, size/L, approved, ok-to-test

#1501 Bump k8s-local-volume-provisioner to 0.2.0-rc.0 in CI
  .github/actions/setup-local-volume-provisioner/manifests/local-csi-driver/50_daemonset.yaml
  hack/.ci/manifests/namespaces/local-csi-driver/50_daemonset.yaml
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#1506 Update release procedure
  release.md
Labels: priority/important-soon, kind/machinery, lgtm, size/S, approved

#1507 Fix preview target in docs readme
  docs/README-dev.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved
