Repository scylladb/scylla-operator, pull requests merged in 2023-03, with the labels that each got.

#1179 Limit CI parallelism
  pkg/cmd/tests/tests_run.go
Labels: priority/important-soon, kind/machinery

#1177 Wait for haproxy-ingress to be ready when setting up the example
  examples/third-party/haproxy-ingress/10_haproxy-ingress.deploy.yaml
Labels: priority/important-soon, kind/flake

#1178 Force default resources in CI
  .github/actions/setup-kubernetes/action.yaml
Labels: priority/important-soon, kind/machinery

#1182 Tune CI and adjust timeouts
  .github/actions/run-e2e/action.yaml
  .github/actions/setup-kubernetes/action.yaml
  .github/actions/setup-local-volume-provisioner/action.yaml
Labels: priority/important-soon, kind/machinery

#1160 Update and pin Ubuntu to 22.04
  .github/actions/setup-kubernetes/action.yaml
  .github/workflows/docs_build.yaml
  .github/workflows/docs_deploy.yaml
  .github/workflows/go.yaml
  .github/workflows/pr.yaml
  .github/workflows/releases.yaml
  Dockerfile
Labels: kind/feature, priority/important-soon

#1184 Update docs dependencies
  docs/Makefile
  docs/poetry.lock
  docs/pyproject.toml
Labels: priority/important-soon, kind/machinery

#1185 Update docs version to 1.3
  .github/actions/docs/build/action.yaml
  docs/Makefile
  docs/_utils/redirects.yaml
  docs/poetry.lock
  docs/pyproject.toml
Labels: kind/documentation

#1187 Make the hack gomod valid
  hack/gke/systemd/go.mod
Labels: priority/important-longterm, kind/machinery

#1196 Update Go to 1.20
  .github/workflows/go.yaml
  .github/workflows/releases.yaml
  Dockerfile
  Makefile
  go.mod
Labels: priority/important-soon, kind/machinery
