Repository scylladb/scylla-operator, pull requests merged in 2023-06, with the labels that each got.

#1268 Fix EKS examples
  examples/eks/cluster.yaml
  examples/eks/eks-cluster.yaml
  examples/eks/eks.sh
  examples/eks/nodeconfig-alpha.yaml
Labels: kind/documentation

#1266 Fix flaky kubelet boot in CI
  .github/actions/setup-kubernetes/action.yaml
Labels: kind/flake, kind/machinery

#1267 Fix ScyllaDB version upgrade being stuck on Pod staying in maintenance mode
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
Labels: kind/bug

#1274 Build v1.9 documentation
  docs/source/conf.py
Labels: kind/documentation

#1273 [v1.9] Pin tags to 1.9
  Makefile
  deploy/manager/dev/50_controller_deployment.yaml
  deploy/manager/prod/50_controller_deployment.yaml
  deploy/operator/50_operator.deployment.yaml
  deploy/operator/50_webhookserver.deployment.yaml
  examples/common/manager.yaml
  examples/common/operator.yaml
  examples/gke/xfs-formatter-daemonset.yaml
  helm/scylla-manager/Chart.yaml
  helm/scylla-operator/Chart.yaml
Labels: kind/machinery

#1275 Fix release notes generation
  .github/actions/release-notes/action.yaml
Labels: kind/machinery

#1276 [v1.9] Fix release notes generation
  .github/actions/release-notes/action.yaml
Labels: kind/machinery

#1269 Replace xfs-formatter with NodeConfig in GKE examples
  Dockerfile
  Makefile
  examples/gke/gke.sh
  examples/gke/nodeconfig-alpha.yaml
  examples/gke/xfs-formatter-daemonset.yaml
  hack/gke/systemd/go.mod
  hack/gke/systemd/mnt-raid\x2ddisks-disk0.mount
  hack/gke/systemd/xfs-formatter.service
  hack/gke/xfs-formatter/bin/tune2fs
  hack/gke/xfs-formatter/xfs-checker.sh
  hack/gke/xfs-formatter/xfs-formatter.sh
  hack/test/gke/xfs-formatter/tune2fs_test.sh
Labels: kind/documentation

#1272 Use Dynamic Local Volume Provisioner in EKS and GKE examples
  examples/common/local-volume-provisioner/local-csi-driver/00_namespace.yaml
  examples/common/local-volume-provisioner/local-csi-driver/10_csidriver.yaml
  examples/common/local-volume-provisioner/local-csi-driver/10_driver_serviceaccount.yaml
  examples/common/local-volume-provisioner/local-csi-driver/10_provisioner_clusterrole.yaml
  examples/common/local-volume-provisioner/local-csi-driver/20_provisioner_clusterrolebinding.yaml
  examples/common/local-volume-provisioner/local-csi-driver/50_daemonset.yaml
  examples/common/local-volume-provisioner/storageclass_xfs.yaml
  examples/common/provisioner/Chart.yaml
  examples/common/provisioner/templates/namespace.yaml
  examples/common/provisioner/templates/provisioner-cluster-role-binding.yaml
  examples/common/provisioner/templates/provisioner-service-account.yaml
  examples/common/provisioner/templates/provisioner.yaml
  examples/common/provisioner/values.yaml
  examples/eks/cluster.yaml
  examples/eks/eks.sh
  examples/eks/nodeconfig-alpha.yaml
  examples/gke/cluster.yaml
  examples/gke/gke.sh
  examples/gke/nodeconfig-alpha.yaml
Labels: kind/documentation

#1278 Fix NodeConfig DaemonSet prunning
  pkg/controller/nodeconfig/sync_daemonsets.go
Labels: kind/bug, priority/important-soon

#1279 [v1.9] Fix NodeConfig DaemonSet prunning
  pkg/controller/nodeconfig/sync_daemonsets.go
Labels: kind/bug

#1288 Fix panic in Operator occuring during node replacement
  pkg/controller/scyllacluster/sync_services.go
Labels: kind/bug

#1290 [v1.9] Fix panic in Operator occuring during node replacement
  pkg/controller/scyllacluster/sync_services.go
Labels: kind/bug
