Repository scylladb/scylla-operator, pull requests merged in 2023-08, with the labels that each got.

#1300 Enhancement proposal for running cleanup after scaling
  enhancements/proposals/1207-cleanup-after-scaling/README.md
  enhancements/proposals/dir_placeholder.delete_me_with_first_proposal
Labels: priority/important-soon, kind/design, size/L

#1294 Run node cleanup after scaling the ScyllaCluster
  pkg/cmd/operator/cleanupjob.go
  pkg/cmd/operator/cmd.go
  pkg/cmd/operator/operator.go
  pkg/controller/nodeconfigpod/sync_configmaps.go
  pkg/controller/scyllacluster/conditions.go
  pkg/controller/scyllacluster/controller.go
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
  pkg/controller/scyllacluster/sync.go
  pkg/controller/scyllacluster/sync_jobs.go
  pkg/controller/scyllacluster/sync_services.go
  pkg/controller/scyllacluster/sync_statefulsets.go
  pkg/controller/sidecar/controller.go
  pkg/controller/sidecar/sync.go
  pkg/controllerhelpers/scylla.go
  pkg/helpers/agent.go
  pkg/helpers/array.go
  pkg/naming/constants.go
  pkg/naming/names.go
  pkg/scyllaclient/client.go
  pkg/sidecar/identity/member.go
  pkg/sidecar/identity/member_test.go
  test/e2e/set/scyllacluster/scyllacluster_cleanup.go
  test/e2e/set/scyllacluster/verify.go
  test/e2e/utils/observer.go
Labels: kind/feature, lgtm, size/XXL

#1322 Bump ScyllaDB to 5.1.15 and ScyllaDB Manager to 3.1.2 in examples, Helm charts and e2e suites
  deploy/manager/dev/50_manager_deployment.yaml
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_manager_deployment.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  examples/common/manager.yaml
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  helm/deploy/manager_prod.yaml
  helm/scylla-manager/values.yaml
  helm/scylla/values.yaml
  test/e2e/fixture/scylla/basic.scyllacluster.yaml
  test/e2e/set/scyllacluster/config.go
Labels: kind/documentation, priority/important-longterm, size/M

#1313 Enhancement proposal for replacing nodes using their HostIDs
  enhancements/proposals/1311-replace-nodes-using-hostid/README.md
Labels: priority/important-soon, kind/design, lgtm, size/L

#1323 Adjust docs development workflow and add developers' README
  docs/Makefile
  docs/README-dev.md
Labels: kind/documentation, priority/important-longterm, size/S

#1308 Update docs theme version to 1.5
  docs/poetry.lock
  docs/pyproject.toml
  docs/source/conf.py
  docs/source/generic.md
  docs/source/helm.md
  docs/source/index.rst
  docs/source/known-issues.md
  docs/source/manager.md
  docs/source/nodeoperations/automatic-cleanup.md
  docs/source/nodeoperations/index.rst
  docs/source/nodeoperations/maintenance-mode.md
  docs/source/nodeoperations/replace-node.md
  docs/source/nodeoperations/scylla-upgrade.md
  docs/source/scylla-cluster-crd.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/L

#1326 Update docs dependencies
  docs/poetry.lock
  docs/pyproject.toml
Labels: priority/important-soon, kind/documentation, size/M

#1329 Enable building docs for v1.10
  docs/source/conf.py
Labels: kind/documentation, lgtm, size/XS

#1328 [v1.10] Pin tags to 1.10
  Makefile
  deploy/manager/dev/50_controller_deployment.yaml
  deploy/manager/prod/50_controller_deployment.yaml
  deploy/operator/50_operator.deployment.yaml
  deploy/operator/50_webhookserver.deployment.yaml
  examples/common/manager.yaml
  examples/common/operator.yaml
  helm/scylla-manager/Chart.yaml
  helm/scylla-operator/Chart.yaml
Labels: kind/machinery, lgtm, size/S

#1327 Fix variable defaulting and undefined variables in docs Makefile
  docs/Makefile
Labels: priority/important-soon, kind/cleanup, lgtm, size/M

#1330 Add OWNERS
  OWNERS
Labels: priority/important-soon, kind/machinery, size/S

#1180 Point all traffic targeting default backend to correct port
  examples/third-party/haproxy-ingress/10_ingress-default-backend.svc.yaml
Labels: priority/important-soon, kind/machinery

#1335 Create missing mount points when tuning nodes
  pkg/controller/nodesetup/sync_mounts.go
Labels: kind/bug, priority/important-soon, lgtm, size/XS, approved

#1332 Remove haproxy tunning that breaks GKE
  examples/third-party/haproxy-ingress/10_haproxy-ingress.cm.yaml
Labels: kind/flake, priority/critical-urgent, lgtm, size/XS, approved

#1333 Ignore not found errors when gathering artifacts
  hack/ci-gather-artifacts.sh
Labels: priority/important-soon, kind/flake, lgtm, size/XS, approved

#1337 Bump ScyllaDB version used in replace via HostID e2e to latest 5.2.6
  test/e2e/set/scyllacluster/scyllacluster_replace.go
Labels: kind/flake, priority/critical-urgent, lgtm, size/XS, approved

#1339 Increase e2e parallel jobs timeout
  .github/workflows/go.yaml
Labels: priority/important-soon, kind/machinery, size/XS, approved

#1342 Raise default ScyllaCluster storage capacity for e2es
  test/e2e/fixture/scylla/basic.scyllacluster.yaml
Labels: priority/important-soon, kind/flake, lgtm, size/XS, approved

#1331 Remove GH presubmits in favour of Prow
  .github/workflows/docs_build.yaml
  .github/workflows/go.yaml
  .github/workflows/pr.yaml
  hack/.ci/manifests/cluster/nodeconfig.yaml
  hack/.ci/manifests/namespaces/local-csi-driver/00_namespace.yaml
  hack/.ci/manifests/namespaces/local-csi-driver/00_scylladb-local-xfs.storageclass.yaml
  hack/.ci/manifests/namespaces/local-csi-driver/10_csidriver.yaml
  hack/.ci/manifests/namespaces/local-csi-driver/10_driver.serviceaccount.yaml
  hack/.ci/manifests/namespaces/local-csi-driver/10_provisioner_clusterrole.yaml
  hack/.ci/manifests/namespaces/local-csi-driver/20_provisioner_clusterrolebinding.yaml
  hack/.ci/manifests/namespaces/local-csi-driver/50_daemonset.yaml
  hack/.ci/run-e2e-gke.sh
  hack/ci-deploy.sh
  pkg/cmd/tests/tests_run.go
Labels: priority/important-soon, kind/machinery, lgtm, size/XL, approved

#1056 Fix backup field name in scylla cluster spec documentation
  docs/source/manager.md
Labels: kind/documentation, lgtm, size/XS, approved

#1213 Add imagePullSecrets support in Scylla helm chart
  helm/scylla/templates/scyllacluster.yaml
  helm/scylla/values.yaml
Labels: kind/feature, priority/important-longterm, lgtm, size/XS, approved, ok-to-test

#1257 Enhance handling of non-integer values around replica checks in Operator Helm Chart
  helm/scylla-operator/templates/operator.pdb.yaml
  helm/scylla-operator/templates/webhookserver.pdb.yaml
Labels: priority/important-longterm, kind/machinery, lgtm, approved

#1338 Enable pending replace e2e test awaiting for 2023.1.0 release
  test/e2e/set/scyllacluster/scyllacluster_replace.go
Labels: priority/important-soon, kind/cleanup, lgtm, size/XS, approved

#1351 Wait for artifact collection on e2e failures
  hack/.ci/run-e2e-gke.sh
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#1345 Stop any ongoing cleanup on Job termination and on cleanup startup
  pkg/cmd/operator/cleanupjob.go
  pkg/scyllaclient/client.go
  pkg/scyllaclient/model.go
Labels: kind/bug, priority/important-soon, lgtm, size/M, approved

#1352 Limit parallelism in e2e test suites in GH Action postsubmits
  .github/workflows/go.yaml
Labels: kind/machinery, lgtm, size/XS, approved

#1353 Mark 1.10 as latest stable version in documentation
  docs/source/conf.py
Labels: kind/documentation, lgtm, size/XS, approved

#1354 Stop building and publishing documentation for 1.7
  docs/source/conf.py
Labels: kind/documentation, lgtm, size/XS, approved

#1355 Update release schedule
  docs/source/releases.md
Labels: kind/documentation, lgtm, size/XS, approved

#1356 Add 1.10 to support matrix
  docs/source/releases.md
Labels: kind/documentation, lgtm, size/S, approved

#1360 Remove duplicate list entry in index.rst
  docs/source/index.rst
Labels: kind/documentation, lgtm, size/XS, approved, ok-to-test

#1361 Align release schedule with team sprints
  docs/source/releases.md
Labels: lgtm, size/XS, approved
