Repository scylladb/scylla-operator, pull requests merged in 2023-01, with the labels that each got.

#1133 [v1.8] Prepare 1.8 release branch
  Makefile
  deploy/manager/dev/50_controller_deployment.yaml
  deploy/manager/prod/50_controller_deployment.yaml
  deploy/operator/50_operator.deployment.yaml
  deploy/operator/50_webhookserver.deployment.yaml
  examples/common/manager.yaml
  examples/common/operator.yaml
  examples/gke/xfs-formatter-daemonset.yaml
  helm/scylla-manager/Chart.yaml
  helm/scylla-operator/Chart.yaml
Labels: kind/machinery

#1134 Build v1.8 documentation
  docs/source/conf.py
Labels: kind/documentation

#1136 Bump Go version in release pipeline
  .github/workflows/releases.yaml
Labels: kind/machinery

#1135 [v1.8] Bump Go version in release pipeline
  .github/workflows/releases.yaml
Labels: kind/machinery

#1128 Await schema agreement before verifying CQL data
  test/e2e/set/scyllacluster/verify.go
  test/e2e/utils/datainserter.go
Labels: priority/important-soon, kind/flake

#1126 Fix flakyness of replace node e2e
  test/e2e/set/scyllacluster/scyllacluster_replace.go
Labels: priority/important-soon, kind/flake

#1127 Use generic controller ref manager
  pkg/controller/nodeconfig/sync.go
  pkg/controller/nodeconfigdaemon/sync.go
  pkg/controller/nodeconfigpod/sync.go
  pkg/controller/scyllacluster/sync.go
  pkg/controllerhelpers/sync.go
  pkg/controllertools/configmapmanager.go
  pkg/controllertools/daemonsetmanager.go
  pkg/controllertools/ingressmanager.go
  pkg/controllertools/jobmanager.go
  pkg/controllertools/pdbmanager.go
  pkg/controllertools/refmanager.go
  pkg/controllertools/rolebindingmanager.go
  pkg/controllertools/secretmanager.go
  pkg/controllertools/serviceaccountmanager.go
  pkg/controllertools/servicemanager.go
  pkg/controllertools/statefulsetmanager.go
Labels: priority/important-soon, kind/cleanup

#1099 Use explicitly created SA token in E2E test suite
  test/e2e/framework/framework.go
  test/e2e/framework/util.go
Labels: kind/machinery

#1142 Fix leader election error handling and context cancelation
  pkg/leaderelection/leaderelection.go
Labels: kind/bug, priority/important-soon

#1143 Fix ApplyRoleBinding updates for immutable roleRef
  pkg/resourceapply/rbac.go
  pkg/resourceapply/rbac_test.go
Labels: kind/bug, priority/important-soon

#1146 Fix NodeConfigDaemonController working on objects from a different shard
  pkg/controller/nodeconfigdaemon/sync.go
  pkg/controllerhelpers/sync.go
Labels: kind/bug, priority/critical-urgent

#1153 Bump docs stable version to 1.8
  docs/source/conf.py
  docs/source/releases.md
Labels: priority/important-soon, kind/documentation

#1106 Bump Kubernetes version to 1.24.9 in CI
  .github/actions/run-e2e/action.yaml
  .github/actions/setup-kubernetes/action.yaml
  .github/actions/setup-local-volume-provisioner/action.yaml
  .github/actions/setup-local-volume-provisioner/manifests/00_clusterrole.yaml
  .github/actions/setup-local-volume-provisioner/manifests/00_namespace.yaml
  .github/actions/setup-local-volume-provisioner/manifests/00_storageclass.yaml
  .github/actions/setup-local-volume-provisioner/manifests/10_configmap.yaml
  .github/actions/setup-local-volume-provisioner/manifests/10_serviceaccount.yaml
  .github/actions/setup-local-volume-provisioner/manifests/20_node.clusterrolebinding.yaml
  .github/actions/setup-local-volume-provisioner/manifests/20_persistent-volume-provisioner.clusterrolebinding.yaml
  .github/actions/setup-local-volume-provisioner/manifests/50_daemonset.yaml
  .github/actions/setup-minikube/action.yaml
  .github/workflows/go.yaml
  pkg/pointer/pointer.go
  test/e2e/framework/framework.go
  test/e2e/set/scyllacluster/scyllacluster_pv.go
  test/e2e/utils/image/manifests.go
  vendor/k8s.io/component-helpers/storage/volume/helpers.go
  vendor/k8s.io/component-helpers/storage/volume/pv_helpers.go
  vendor/modules.txt
Labels: priority/important-soon, kind/machinery

#1154 Update Grafana version to 9.3.4
  assets/monitoring/grafana/v1alpha1/deployment.yaml
Labels: kind/feature, priority/important-soon
