Repository scylladb/scylla-operator, pull requests merged in 2023-05, with the labels that each got.

#1230 Fix command go-template in monitoring docs
  docs/source/monitoring.md
Labels: kind/documentation

#1238 Bump ScyllaDB and ScyllaDB Manager versions in Helm chart, examples and e2es
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  test/e2e/fixture/scylla/basic.scyllacluster.yaml
  test/e2e/set/scyllacluster/config.go
Labels: kind/feature

#1246 Revert "Bump ScyllaDB and ScyllaDB Manager versions in Helm chart, examples and e2es "
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  test/e2e/fixture/scylla/basic.scyllacluster.yaml
  test/e2e/set/scyllacluster/config.go
Labels: kind/feature, priority/critical-urgent

#1234 Refactor release notes publishing into a reusable GitHub Action
  .github/actions/release-notes/action.yaml
  .github/workflows/releases.yaml
  pkg/cmd/releasenotes/generate.go
  pkg/cmd/releasenotes/github.go
  pkg/cmd/releasenotes/options.go
  pkg/cmd/releasenotes/releasenotes.go
Labels: priority/important-soon, kind/machinery

#1235 Update HAProxy ingress example
  examples/third-party/haproxy-ingress/10_graphana.pvc.yaml
  examples/third-party/haproxy-ingress/10_haproxy-ingress.deploy.yaml
  examples/third-party/haproxy-ingress/10_prometheus.cm.yaml
  examples/third-party/haproxy-ingress/10_prometheus.deploy.yaml
  examples/third-party/haproxy-ingress/10_prometheus.svc.yaml
Labels: priority/important-soon, kind/documentation

#1247 Use ScyllaDB 5.1.9 and ScyllaDB Manager 3.1.0 as default versions in Helm chart, examples and e2e
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  test/e2e/fixture/scylla/basic.scyllacluster.yaml
  test/e2e/set/scyllacluster/config.go
Labels: kind/feature

#1248 Extract container image name as a parameter in gen-release-notes
  .github/actions/release-notes/action.yaml
  .github/workflows/releases.yaml
  pkg/cmd/releasenotes/generate.go
  pkg/cmd/releasenotes/options.go
  pkg/cmd/releasenotes/releasenotes.go
  pkg/cmd/releasenotes/render.go
Labels: kind/machinery

#1244 Update kubernetes to v1.27.1 in CI setup
  .github/actions/setup-kubernetes/action.yaml
  test/e2e/set/scylladbmonitoring/scylladbmonitoring.go
Labels: priority/important-longterm, kind/machinery

#1202 Pregenerate RSA keys and speed up bootstrap times
  hack/ci-deploy.sh
  pkg/cmd/operator/operator.go
  pkg/controller/scyllacluster/controller.go
  pkg/controller/scyllacluster/sync_certs.go
  pkg/controller/scylladbmonitoring/controller.go
  pkg/controller/scylladbmonitoring/sync_grafana.go
  pkg/controller/scylladbmonitoring/sync_prometheus.go
  pkg/crypto/ca.go
  pkg/crypto/certcreators.go
  pkg/crypto/certcreators_test.go
  pkg/crypto/keygenerator.go
  pkg/crypto/signers.go
  pkg/itemgenerator/generator.go
  pkg/itemgenerator/generator_test.go
  pkg/kubecrypto/certmanager.go
  pkg/kubecrypto/certs.go
  pkg/kubecrypto/certs_test.go
  pkg/kubecrypto/signingtlssecret.go
Labels: kind/feature, priority/important-soon

#1253 Extend test runner with a report verifier checking if every Spec was ran exactly once
  pkg/cmd/tests/tests_run.go
Labels: kind/bug, priority/critical-urgent

#1258 Fix Google GPG key file extension in Kubernetes setup GH action
  .github/actions/setup-kubernetes/action.yaml
Labels: kind/machinery

#1256 Fix seed propagation in test runner
  pkg/cmd/tests/tests_run.go
  pkg/thirdparty/github.com/onsi/ginkgo/v2/exposedinternal/parallel_support/client_server.go
  pkg/thirdparty/github.com/onsi/ginkgo/v2/exposedinternal/parallel_support/http_client.go
  pkg/thirdparty/github.com/onsi/ginkgo/v2/exposedinternal/parallel_support/http_server.go
  pkg/thirdparty/github.com/onsi/ginkgo/v2/exposedinternal/parallel_support/rpc_client.go
  pkg/thirdparty/github.com/onsi/ginkgo/v2/exposedinternal/parallel_support/rpc_server.go
  pkg/thirdparty/github.com/onsi/ginkgo/v2/exposedinternal/parallel_support/server_handler.go
Labels: kind/bug, priority/critical-urgent

#1260 Drop temporary report verifier from test runner
  pkg/cmd/tests/tests_run.go
Labels: kind/cleanup, priority/important-longterm
