Repository scylladb/scylla-operator, pull requests merged in 2023-07, with the labels that each got.

#1295 Set v1.9 documentation as stable
  docs/source/conf.py
  docs/source/releases.md
Labels: kind/documentation

#1297 Identify nodes by their Host ID instead of IP address in readiness probes
  pkg/sidecar/probes.go
Labels: kind/feature

#1298 Replace `github.com/ghodss/yaml` library with `sigs.k8s.io/yaml`
  go.mod
  go.sum
  pkg/sidecar/config/config.go
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/modules.txt
Labels: kind/cleanup, priority/important-longterm
