Repository scylladb/scylla-operator, pull requests merged in 2024-05, with the labels that each got.

#1804 Parametrize must-gather command
  pkg/cmd/operator/mustgather.go
Labels: kind/feature, priority/important-soon, lgtm, size/S, approved

#1853 Deprecate interval in manager task schedule spec
  deploy/operator.yaml
  docs/source/api-reference/groups/scylla.scylladb.com/scyllaclusters.rst
  helm/scylla-manager/values.schema.json
  helm/scylla/values.schema.json
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/types_cluster.go
  test/e2e/set/scyllacluster/scyllamanager.go
Labels: kind/feature, priority/important-longterm, lgtm, size/M, approved, ¯\_(ツ)_/¯

#1911 Fix and unify artifact collection in CI script
  hack/.ci/run-e2e-gke.sh
Labels: kind/bug, priority/critical-urgent, lgtm, size/L, approved

#1917 Bump k8s-local-volume-provisioner to 0.3.2-rc.0 in CI
  hack/.ci/manifests/namespaces/local-csi-driver/50_daemonset.yaml
Labels: kind/feature, priority/important-soon, lgtm, size/XS, approved

#1919 Fix assertion in e2e testing ingress connectivity
  test/e2e/set/scyllacluster/scyllacluster_expose.go
Labels: kind/bug, priority/important-soon, lgtm, size/XS, approved

#1850 Fix manager task reconciliation and status synchronisation
  deploy/operator.yaml
  docs/source/api-reference/groups/scylla.scylladb.com/scyllaclusters.rst
  helm/scylla-manager/values.schema.json
  helm/scylla/values.schema.json
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/types_cluster.go
  pkg/api/scylla/v1/zz_generated.deepcopy.go
  pkg/api/scylla/validation/cluster_validation.go
  pkg/api/scylla/validation/cluster_validation_test.go
  pkg/controller/manager/status.go
  pkg/controller/manager/sync.go
  pkg/controller/manager/sync_action.go
  pkg/controller/manager/sync_test.go
  pkg/controller/manager/types_old.go
  pkg/controller/manager/types_old_test.go
  test/e2e/set/scyllacluster/scyllamanager.go
Labels: kind/bug, priority/critical-urgent, lgtm, size/XXL, approved

#1880 Update Scylla Manager to 3.2.7
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_manager_deployment.yaml
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_manager_deployment.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  docs/source/generic.md
  docs/source/multidc/multidc.md
  docs/source/nodeoperations/restore.md
  docs/source/performance.md
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  examples/scylladb/scylla.scyllacluster.yaml
  helm/deploy/manager_prod.yaml
  helm/scylla-manager/values.yaml
  helm/scylla/values.yaml
  test/e2e/fixture/scylla/scyllacluster.yaml.tmpl
Labels: kind/feature, priority/important-longterm, lgtm, size/M, approved

#1824 Parametrize e2e command
  pkg/cmd/tests/options.go
  pkg/cmd/tests/tests.go
  pkg/cmd/tests/tests_run.go
Labels: priority/important-soon, kind/cleanup, lgtm, size/L, approved

#1922 Unify artifacts dir naming to match Prow default dir
  hack/ci-deploy.sh
Labels: priority/important-soon, kind/cleanup, lgtm, size/XS, approved

#1925 Update Scylla Manager to 3.2.8
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_manager_deployment.yaml
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_manager_deployment.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  docs/source/generic.md
  docs/source/multidc/multidc.md
  docs/source/nodeoperations/restore.md
  docs/source/performance.md
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  examples/scylladb/scylla.scyllacluster.yaml
  helm/deploy/manager_prod.yaml
  helm/scylla-manager/values.yaml
  helm/scylla/values.yaml
  test/e2e/fixture/scylla/scyllacluster.yaml.tmpl
Labels: kind/feature, priority/important-longterm, lgtm, size/M, approved

#1927 Bump local volume provisioner to 3.2.0
  examples/common/local-volume-provisioner/local-csi-driver/50_daemonset.yaml
  hack/.ci/manifests/namespaces/local-csi-driver/50_daemonset.yaml
Labels: priority/important-soon, kind/documentation, kind/machinery, lgtm, size/XS, approved

#1928 [v1.12] Bump local volume provisioner to 3.2.0
  examples/common/local-volume-provisioner/local-csi-driver/50_daemonset.yaml
  hack/.ci/manifests/namespaces/local-csi-driver/50_daemonset.yaml
Labels: priority/important-soon, kind/documentation, kind/machinery, lgtm, size/XS, approved

#1929 [v1.11] Bump local volume provisioner to 3.2.0
  .github/actions/setup-local-volume-provisioner/manifests/local-csi-driver/50_daemonset.yaml
  examples/common/local-volume-provisioner/local-csi-driver/50_daemonset.yaml
  hack/.ci/manifests/namespaces/local-csi-driver/50_daemonset.yaml
Labels: priority/important-soon, kind/documentation, kind/machinery, lgtm, size/XS, approved

#1923 Add version command
  pkg/cmd/operator/cmd.go
  pkg/cmd/tests/tests.go
  pkg/cmd/version/version.go
Labels: kind/feature, priority/important-longterm, lgtm, size/M, approved

#1931 Update docs dependencies
  docs/poetry.lock
Labels: priority/important-soon, kind/machinery, lgtm, size/M, approved

#1933 Clear Scylla Manager task errors from status after they've been successfully executed
  pkg/controller/manager/sync_action.go
Labels: kind/bug, priority/important-soon, lgtm, size/M, approved

#1475 Fix grafana permissions for kubectl cp and run it as non root
  assets/monitoring/grafana/v1alpha1/deployment.yaml
Labels: kind/bug, priority/important-longterm, lgtm, size/S, approved

#1945 Remove redundant check in ci deploy script
  hack/ci-deploy.sh
Labels: kind/cleanup, priority/important-longterm, lgtm, size/XS, approved

#1837 Add CI script to deploy published releases
  hack/.ci/run-e2e-gke-release.sh
  hack/ci-deploy-release.sh
Labels: priority/important-soon, kind/machinery, lgtm, size/L, approved

#1948 Update index.rst -add link to the University course
  docs/source/index.rst
Labels: needs-priority, lgtm, size/XS, approved, do-not-merge/needs-kind
