Repository scylladb/scylla-operator, pull requests merged in 2024-12, with the labels that each got.

#2219 Fix cert-manager URL in deploy release CI script
  hack/ci-deploy-release.sh
  hack/ci-deploy.sh
Labels: kind/bug, priority/important-soon, lgtm, size/XS, approved

#2220 [v1.15] Fix cert-manager URL in deploy release CI script
  hack/ci-deploy-release.sh
  hack/ci-deploy.sh
Labels: kind/bug, priority/important-soon, lgtm, size/XS, approved

#2222 Raise loglevel when reporting perftune job completion
  pkg/controller/nodetune/sync_jobs.go
Labels: kind/cleanup, priority/important-longterm, lgtm, size/XS, approved

#2233 Lazely initialize assets
  assets/monitoring/grafana/v1alpha1/registry.go
  assets/monitoring/prometheus/v1/registry.go
  assets/scylladb/registry.go
  pkg/assets/object_template.go
  pkg/controller/scylladbdatacenter/resource.go
  pkg/controller/scylladbmonitoring/main_test.go
  pkg/controller/scylladbmonitoring/sync_grafana.go
  pkg/controller/scylladbmonitoring/sync_grafana_test.go
  pkg/controller/scylladbmonitoring/sync_prometheus.go
  pkg/util/lazy/lazy.go
  test/e2e/fixture/scylla/registry.go
  test/e2e/set/scylladbmonitoring/scylladbmonitoring.go
Labels: priority/important-soon, kind/cleanup, lgtm, size/L, approved

#2238 Explicitly disable developerMode when it's not set in the API object
  pkg/controller/scylladbdatacenter/resource.go
  pkg/controller/scylladbdatacenter/resource_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/M, approved

#2236 [v1.15] Lazily initialize assets
  assets/monitoring/grafana/v1alpha1/registry.go
  assets/monitoring/prometheus/v1/registry.go
  assets/scylladb/registry.go
  pkg/assets/object_template.go
  pkg/controller/scylladbdatacenter/resource.go
  pkg/controller/scylladbmonitoring/main_test.go
  pkg/controller/scylladbmonitoring/sync_grafana.go
  pkg/controller/scylladbmonitoring/sync_grafana_test.go
  pkg/controller/scylladbmonitoring/sync_prometheus.go
  pkg/util/lazy/lazy.go
  test/e2e/fixture/scylla/registry.go
  test/e2e/set/scylladbmonitoring/scylladbmonitoring.go
Labels: priority/important-soon, kind/cleanup, lgtm, size/L, approved

#2227 Verify ScyllaCluster after each rollout in every test
  test/e2e/set/nodeconfig/nodeconfig_optimizations.go
  test/e2e/set/scyllacluster/multi_datacenter_scyllacluster_external_seeds.go
  test/e2e/set/scyllacluster/scyllacluster_alternator.go
  test/e2e/set/scyllacluster/scyllacluster_auth.go
  test/e2e/set/scyllacluster/scyllacluster_cleanup.go
  test/e2e/set/scyllacluster/scyllacluster_evictions.go
  test/e2e/set/scyllacluster/scyllacluster_expose.go
  test/e2e/set/scyllacluster/scyllacluster_external_seeds.go
  test/e2e/set/scyllacluster/scyllacluster_hostid.go
  test/e2e/set/scyllacluster/scyllacluster_pv.go
  test/e2e/set/scyllacluster/scyllacluster_rebootstrap.go
  test/e2e/set/scyllacluster/scyllacluster_replace.go
  test/e2e/set/scyllacluster/scyllacluster_scaling.go
  test/e2e/set/scyllacluster/scyllacluster_shardawareness.go
  test/e2e/set/scyllacluster/scyllacluster_sysctl.go
  test/e2e/set/scyllacluster/scyllacluster_tls.go
  test/e2e/set/scyllacluster/scyllacluster_updates.go
  test/e2e/set/scyllacluster/scyllacluster_upgrades.go
  test/e2e/set/scyllacluster/scyllacluster_webhooks.go
  test/e2e/set/scyllacluster/scyllamanager.go
  test/e2e/set/scyllacluster/scyllamanager_object_storage.go
  test/e2e/set/scylladbmonitoring/scylladbmonitoring.go
  test/e2e/utils/verification/scyllacluster/cql.go
  test/e2e/utils/verification/scyllacluster/verify.go
Labels: priority/important-soon, kind/machinery, lgtm, size/XL, approved

#2242 [v1.15] Explicitly disable developerMode when it's not set in the API object
  pkg/controller/scylladbdatacenter/resource.go
  pkg/controller/scylladbdatacenter/resource_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/M, approved

#2229 Verify that no container in a ScyllaCluster Pod has restarted during e2e run
  test/e2e/utils/helpers.go
  test/e2e/utils/verification/scyllacluster/verify.go
Labels: priority/important-soon, kind/machinery, lgtm, size/M, approved

#2245 Speed up NodeConfig optimization test
  pkg/controllerhelpers/wait.go
  test/e2e/set/nodeconfig/nodeconfig_optimizations.go
Labels: kind/bug, priority/important-soon, lgtm, size/M, approved

#2225 Propagate operator loglevel
  pkg/cmdutil/helpers.go
  pkg/controller/nodeconfig/resource.go
  pkg/controller/nodetune/resource.go
  pkg/controller/scylladbdatacenter/init_test.go
  pkg/controller/scylladbdatacenter/resource.go
  pkg/controller/scylladbdatacenter/resource_test.go
Labels: kind/feature, priority/important-soon, lgtm, size/M, approved

#2246 Fix sidecar annotation controller rate limits for better response times
  go.mod
  pkg/controller/sidecar/controller.go
Labels: kind/bug, priority/important-soon, lgtm, size/S, approved, area/dependency

#2247 Use client CA bundle as truststore
  assets/scylladb/managedconfig.cm.yaml
  pkg/controller/scylladbdatacenter/resource.go
  pkg/controller/scylladbdatacenter/resource_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/M, approved

#2212 Fix accidental ignition and stuck graceful termination
  pkg/controller/ignition/controller.go
  pkg/controller/scylladbdatacenter/resource.go
  pkg/controller/scylladbdatacenter/resource_test.go
  pkg/naming/constants.go
  pkg/naming/names.go
  test/e2e/set/nodeconfig/nodeconfig_disksetup.go
  test/e2e/set/nodeconfig/nodeconfig_optimizations.go
  test/e2e/set/scyllacluster/scyllacluster_restarts.go
  test/e2e/set/scyllacluster/scyllacluster_shardawareness.go
  test/e2e/set/scyllacluster/scyllamanager_object_storage.go
  test/e2e/utils/exec.go
  test/e2e/utils/helpers.go
  test/e2e/utils/verification/scyllacluster/verify.go
Labels: kind/bug, priority/critical-urgent, lgtm, size/XL, approved

#2235 Unify the use of taints and tolerations in deploy, docs, examples and tests
  docs/source/resources/scyllaclusters/multidc/multidc.md
  examples/common/nodeconfig-alpha.yaml
  examples/eks/scyllacluster.yaml
  examples/generic/nodeconfig-alpha.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  examples/monitoring/v1alpha1/scylladbmonitoring.yaml
  examples/scylladb/scylla.scyllacluster.yaml
  helm/scylla-manager/values.yaml
  helm/scylla/values.yaml
  test/e2e/fixture/scylla/nodeconfig.yaml
  test/e2e/fixture/scylla/scyllacluster.yaml.tmpl
  test/e2e/fixture/scylla/scylladbcluster.yaml.tmpl
  test/e2e/fixture/scylla/scylladbdatacenter.yaml.tmpl
  test/e2e/fixture/scylla/scylladbmonitoring.yaml.tmpl
  test/e2e/fixture/scylla/zonal.scyllacluster.yaml.tmpl
Labels: kind/cleanup, priority/important-longterm, lgtm, size/L, approved

#2250 [v1.15] Fix graceful termination, early ignition and related tests
  go.mod
  pkg/controller/ignition/controller.go
  pkg/controller/nodetune/sync_jobs.go
  pkg/controller/scylladbdatacenter/resource.go
  pkg/controller/scylladbdatacenter/resource_test.go
  pkg/controller/sidecar/controller.go
  pkg/controllerhelpers/wait.go
  pkg/naming/constants.go
  pkg/naming/names.go
  test/e2e/set/nodeconfig/nodeconfig_disksetup.go
  test/e2e/set/nodeconfig/nodeconfig_optimizations.go
  test/e2e/set/scyllacluster/multi_datacenter_scyllacluster_external_seeds.go
  test/e2e/set/scyllacluster/scyllacluster_alternator.go
  test/e2e/set/scyllacluster/scyllacluster_auth.go
  test/e2e/set/scyllacluster/scyllacluster_cleanup.go
  test/e2e/set/scyllacluster/scyllacluster_evictions.go
  test/e2e/set/scyllacluster/scyllacluster_expose.go
  test/e2e/set/scyllacluster/scyllacluster_external_seeds.go
  test/e2e/set/scyllacluster/scyllacluster_hostid.go
  test/e2e/set/scyllacluster/scyllacluster_pv.go
  test/e2e/set/scyllacluster/scyllacluster_rebootstrap.go
  test/e2e/set/scyllacluster/scyllacluster_replace.go
  test/e2e/set/scyllacluster/scyllacluster_restarts.go
  test/e2e/set/scyllacluster/scyllacluster_scaling.go
  test/e2e/set/scyllacluster/scyllacluster_shardawareness.go
  test/e2e/set/scyllacluster/scyllacluster_sysctl.go
  test/e2e/set/scyllacluster/scyllacluster_tls.go
  test/e2e/set/scyllacluster/scyllacluster_updates.go
  test/e2e/set/scyllacluster/scyllacluster_upgrades.go
  test/e2e/set/scyllacluster/scyllacluster_webhooks.go
  test/e2e/set/scyllacluster/scyllamanager.go
  test/e2e/set/scyllacluster/scyllamanager_object_storage.go
  test/e2e/set/scylladbmonitoring/scylladbmonitoring.go
  test/e2e/utils/exec.go
  test/e2e/utils/helpers.go
  test/e2e/utils/verification/scyllacluster/cql.go
  test/e2e/utils/verification/scyllacluster/verify.go
Labels: kind/bug, priority/critical-urgent, lgtm, size/XXL, approved, area/dependency

#2252 [v1.15] Propagate operator loglevel
  pkg/cmdutil/helpers.go
  pkg/controller/nodeconfig/resource.go
  pkg/controller/nodetune/resource.go
  pkg/controller/scylladbdatacenter/init_test.go
  pkg/controller/scylladbdatacenter/resource.go
  pkg/controller/scylladbdatacenter/resource_test.go
Labels: kind/feature, priority/critical-urgent, lgtm, size/M, approved

#2265 Add tolerations to workaround sysctl DaemonSet
  hack/.ci/lib/e2e.sh
Labels: kind/bug, priority/critical-urgent, lgtm, size/XS, approved

#2273 Drop unused examples and scripts
  Makefile
  examples/eks/eks.sh
  examples/eks/scyllacluster.yaml
  examples/generic/scyllacluster.yaml
  examples/gke/gke.sh
  examples/gke/scyllacluster.yaml
Labels: kind/cleanup, priority/important-longterm, lgtm, size/XL, approved

#2279 Fix 'OS Metrics' dashboards in ScyllaDBMonitoring
  assets/monitoring/prometheus/v1/scylladb.servicemonitor.yaml
  pkg/controller/scylladbmonitoring/sync_prometheus_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/S, approved

#2281 Mark v1.15 as latest stable in documentation
  docs/source/conf.py
Labels: priority/important-soon, kind/documentation, lgtm, size/XS, approved

#2283 Always terminate leftover jobs in scripts
  hack/.ci/lib/e2e.sh
  hack/ci-deploy-release.sh
  hack/ci-deploy.sh
  hack/lib/bash.sh
Labels: priority/important-soon, kind/machinery, lgtm, size/M, approved

#2288 Use strict decoding in e2e tests' fixture registry
  test/e2e/fixture/scylla/scylladbdatacenter.yaml.tmpl
  test/e2e/scheme/scheme.go
Labels: kind/bug, priority/important-soon, lgtm, size/M, approved

#1759 Validate open ports
  test/e2e/set/scyllacluster/scyllacluster_listen.go
  test/e2e/utils/linux/net/net.go
  test/e2e/utils/linux/net/net_test.go
Labels: kind/feature, priority/important-soon, triage/accepted, lgtm, size/XL, approved
