Repository scylladb/scylla-operator, pull requests merged in 2024-04, with the labels that each got.

#1846 Collect nodes in must-gather
  pkg/cmd/operator/mustgather.go
  pkg/cmd/operator/mustgather_test.go
Labels: kind/feature, priority/important-soon, lgtm, size/M, approved

#1862 Remove makefile check for go version
  Makefile
Labels: kind/cleanup, priority/important-longterm, lgtm, size/XS, approved

#1875 Clarify supported platform in our docs
  docs/source/releases.md
Labels: priority/important-soon, kind/documentation, lgtm, size/S, approved

#1882 [v1.12] Clarify supported platform in our docs
  docs/source/releases.md
Labels: priority/important-soon, kind/documentation, lgtm, size/S, approved

#1883 [v1.11] Clarify supported platform in our docs
  docs/source/releases.md
Labels: priority/important-soon, kind/documentation, lgtm, size/S, approved

#1884 Bump k8s-local-volume-provisioner in CI to 0.3.1-rc.0
  hack/.ci/manifests/namespaces/local-csi-driver/50_daemonset.yaml
Labels: kind/feature, priority/important-soon, lgtm, size/XS, approved

#1891 Split Scylla Manager repair and backup task integration E2E tests
  test/e2e/set/scyllacluster/scyllamanager.go
Labels: kind/feature, priority/important-longterm, lgtm, size/L, approved

#1894 Update docs dependencies
  docs/poetry.lock
Labels: kind/documentation, priority/critical-urgent, lgtm, size/L, approved

#1868 Make manager tasks' interval and start date optional and non-defaulted
  deploy/operator.yaml
  helm/scylla-manager/values.schema.json
  helm/scylla/values.schema.json
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/types_cluster.go
  pkg/api/scylla/v1/zz_generated.deepcopy.go
  pkg/api/scylla/validation/cluster_validation.go
  pkg/api/scylla/validation/cluster_validation_test.go
  pkg/controller/manager/sync_action.go
  pkg/controller/manager/sync_test.go
  pkg/controller/manager/types_old.go
  pkg/controller/manager/types_old_test.go
  test/e2e/set/scyllacluster/scyllacluster_webhooks.go
  test/e2e/set/scyllacluster/scyllamanager.go
Labels: kind/feature, priority/important-longterm, lgtm, size/L, approved

#1895 Update sphinx-scylladb-theme to 1.7.1
  docs/poetry.lock
  docs/pyproject.toml
Labels: priority/important-soon, kind/machinery, lgtm, size/S, approved, ¯\_(ツ)_/¯

#1754 Support object storage buckets in e2e test runner and script
  hack/.ci/run-e2e-gke.sh
  pkg/cmd/tests/options.go
  pkg/cmd/tests/tests_run.go
  test/e2e/framework/testcontext.go
Labels: kind/feature, priority/critical-urgent, lgtm, size/L, approved

#1855 Collect related objects for ScyllaClusters and ScyllaDBMonitorings in must-gather
  pkg/cmd/operator/mustgather_test.go
  pkg/gather/collect/collect.go
  pkg/gather/collect/collect_test.go
Labels: kind/feature, priority/important-soon, lgtm, size/L, approved

#1851 Support cron and timezone in manager task integration
  deploy/operator.yaml
  docs/source/api-reference/groups/scylla.scylladb.com/scyllaclusters.rst
  go.mod
  helm/scylla-manager/values.schema.json
  helm/scylla/values.schema.json
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/types_cluster.go
  pkg/api/scylla/v1/zz_generated.deepcopy.go
  pkg/api/scylla/validation/cluster_validation.go
  pkg/api/scylla/validation/cluster_validation_test.go
  pkg/controller/manager/types_old.go
  pkg/controller/manager/types_old_test.go
Labels: kind/feature, priority/important-longterm, lgtm, size/XL, approved, area/dependency

#1906 Update Local Volume Provisioner command to only reference the new file path for the xfs storageclass.
  docs/source/eks.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved, ok-to-test

#1887 Update Helm repo URL
  helm/README.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved, ok-to-test
