Repository scylladb/scylla-operator, pull requests merged in 2024-06, with the labels that each got.

#1947 Use conditions to wait for deploying manager DB
  hack/ci-deploy-release.sh
  hack/ci-deploy.sh
Labels: kind/cleanup, priority/important-longterm, lgtm, size/S, approved

#1946 Move webhook server resources definition to values
  helm/scylla-operator/templates/webhookserver.deployment.yaml
  helm/scylla-operator/values.yaml
Labels: kind/feature, priority/important-longterm, lgtm, size/S, approved, ok-to-test

#1881 Support multi-datacenter clusters in test runner and script
  hack/.ci/lib/e2e.sh
  hack/.ci/run-e2e-gke-release.sh
  hack/.ci/run-e2e-gke.sh
  pkg/cmd/tests/options.go
  pkg/genericclioptions/genericclioptions.go
  test/e2e/framework/client.go
  test/e2e/framework/cluster.go
  test/e2e/framework/framework.go
  test/e2e/framework/testcontext.go
  test/e2e/framework/util.go
  test/e2e/set/nodeconfig/nodeconfig_disksetup.go
  test/e2e/utils/exec.go
Labels: kind/feature, priority/important-longterm, lgtm, size/XL, approved, ¯\_(ツ)_/¯

#1951 Propagate kubeconfigs to e2e Pod
  hack/.ci/lib/e2e.sh
  pkg/genericclioptions/genericclioptions.go
Labels: kind/feature, priority/important-soon, lgtm, size/S, approved

#1952 Support overriding deploy dir in deploy script
  hack/.ci/run-e2e-gke.sh
  hack/ci-deploy.sh
Labels: kind/feature, priority/important-soon, lgtm, size/M, approved

#1742 Extend Scylla Manager E2E tests with backup and manual restore procedure
  test/e2e/framework/framework.go
  test/e2e/framework/meta.go
  test/e2e/set/scyllacluster/scyllamanager.go
  test/e2e/set/scyllacluster/scyllamanager_object_storage.go
Labels: kind/feature, priority/critical-urgent, lgtm, size/XL, approved

#1908 Add a Scylla Manager integration E2E test for error propagation for invalid tasks and invalid updates
  test/e2e/set/scyllacluster/scyllamanager.go
  test/e2e/set/scyllacluster/scyllamanager_object_storage.go
Labels: kind/feature, priority/important-longterm, lgtm, size/L, approved

#1956 Bump k8s-local-volume-provisioner to 0.4.0-rc.0 in CI
  hack/.ci/manifests/namespaces/local-csi-driver/50_daemonset.yaml
Labels: kind/feature, priority/important-soon, lgtm, size/XS, approved

#1926 Split ScyllaDB API status probes into a dedicated container
  pkg/cmd/operator/cmd.go
  pkg/cmd/operator/probeserver/cmd.go
  pkg/cmd/operator/probeserver/scylladbapistatus.go
  pkg/cmd/operator/probeserver/serveprobes.go
  pkg/cmd/operator/sidecar.go
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
  pkg/naming/constants.go
  pkg/probeserver/scylladbapistatus/prober.go
Labels: kind/feature, priority/important-soon, lgtm, size/L, approved

#1958 Bump local volume provisioner to latest stable 0.4.0
  examples/common/local-volume-provisioner/local-csi-driver/50_daemonset.yaml
  hack/.ci/manifests/namespaces/local-csi-driver/50_daemonset.yaml
Labels: kind/feature, priority/important-soon, lgtm, size/XS, approved

#1962 Build v1.13 documentation
  docs/source/conf.py
Labels: priority/important-soon, kind/documentation, lgtm, size/XS, approved

#1961 [v1.13] Pin tags to v1.13
  Makefile
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_controller_deployment.yaml
  deploy/manager/prod/50_controller_deployment.yaml
  deploy/operator.yaml
  deploy/operator/50_operator.deployment.yaml
  deploy/operator/50_webhookserver.deployment.yaml
  helm/scylla-manager/Chart.yaml
  helm/scylla-operator/Chart.yaml
Labels: priority/important-soon, kind/machinery, lgtm, size/S, approved

#1960 Add Execute() to OperatorOptions
  pkg/cmd/operator/operator.go
Labels: priority/important-soon, kind/cleanup, lgtm, size/XS, approved

#1964 Update docs dependencies
  docs/poetry.lock
Labels: kind/feature, priority/important-soon, lgtm, size/M, approved

#1965 [v1.13] Update docs dependencies
  docs/poetry.lock
Labels: kind/feature, priority/important-soon, lgtm, size/M, approved

#1970 Add a NodeConfig example for generic environments
  examples/generic/nodeconfig-alpha.yaml
Labels: kind/feature, priority/important-soon, lgtm, size/S, approved

#1974 Extend Handlers' EnqueueAll with enqueing func parameter
  pkg/controllerhelpers/handlers.go
Labels: kind/feature, priority/important-longterm, lgtm, size/S, approved

#1977 Add linux NodeSelector to generic NodeConfig example
  examples/generic/nodeconfig-alpha.yaml
Labels: kind/feature, priority/important-longterm, lgtm, size/XS, approved

#1979 Bump minimum versions for v1.13 release
  docs/source/releases.md
Labels: priority/important-soon, kind/documentation, lgtm, size/XS, approved

#1993 Mark v1.13 as stable version in documentation
  docs/source/conf.py
Labels: priority/important-soon, kind/documentation, lgtm, size/XS, approved

#1953 Add an E2E test suite for multi-datacenter clusters
  pkg/cmd/tests/tests.go
  test/e2e/fixture/scylla/registry.go
  test/e2e/fixture/scylla/zonal.scyllacluster.yaml.tmpl
  test/e2e/framework/framework.go
  test/e2e/framework/meta.go
  test/e2e/set/scyllacluster/config.go
  test/e2e/set/scyllacluster/multi_datacenter_scyllacluster_external_seeds.go
  test/e2e/utils/config.go
  test/e2e/utils/helpers.go
Labels: kind/feature, priority/important-longterm, lgtm, size/L, approved

#1992 Skip CSI driver creation for empty SO_CSI_DRIVER_PATH in deploy release script
  hack/ci-deploy-release.sh
Labels: kind/bug, priority/important-soon, lgtm, size/S, approved

#1995 Bump Scylla Manager to 3.3.0
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_manager_deployment.yaml
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_manager_deployment.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  docs/source/generic.md
  docs/source/multidc/multidc.md
  docs/source/nodeoperations/restore.md
  docs/source/performance.md
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  examples/scylladb/scylla.scyllacluster.yaml
  helm/deploy/manager_prod.yaml
  helm/scylla-manager/values.yaml
  helm/scylla/values.yaml
  test/e2e/fixture/scylla/scyllacluster.yaml.tmpl
  test/e2e/fixture/scylla/zonal.scyllacluster.yaml.tmpl
Labels: kind/feature, priority/important-soon, lgtm, size/M, approved
