Repository scylladb/scylla-operator, pull requests merged in 2024-11, with the labels that each got.

#2177 Do not set ScyllaCluster's ManagerID to empty string when calculating status
  pkg/controller/manager/status.go
  test/e2e/set/scyllacluster/scyllamanager.go
  test/e2e/set/scyllacluster/scyllamanager_object_storage.go
  test/e2e/utils/helpers.go
Labels: priority/important-soon, kind/flake, lgtm, size/M, approved

#2182 Update Scylla Manager version to 3.4.0
  assets/config/config.yaml
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_manager_deployment.yaml
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_manager_deployment.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  docs/source/generic.md
  docs/source/multidc/multidc.md
  docs/source/nodeoperations/restore.md
  docs/source/performance.md
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  examples/scylladb/scylla.scyllacluster.yaml
  helm/deploy/manager_prod.yaml
  helm/scylla-manager/values.yaml
  helm/scylla/values.yaml
Labels: priority/important-longterm, kind/machinery, lgtm, size/M, approved

#2178 Add an E2E test for NodeConfig mount degraded condition propagation for mounts over corrupted xfs filesystems
  test/e2e/set/nodeconfig/nodeconfig_disksetup.go
Labels: kind/feature, priority/important-longterm, lgtm, size/L, approved

#2165 Extend node tune controller with status conditions
  pkg/controller/nodeconfig/status.go
  pkg/controller/nodeconfig/sync.go
  pkg/controller/nodesetup/conditions.go
  pkg/controller/nodesetup/status.go
  pkg/controller/nodesetup/sync.go
  pkg/controller/nodesetup/sync_mounts.go
  pkg/controller/nodesetup/sync_raids.go
  pkg/controller/nodetune/conditions.go
  pkg/controller/nodetune/controller.go
  pkg/controller/nodetune/status.go
  pkg/controller/nodetune/sync.go
  pkg/controller/nodetune/sync_jobs.go
  pkg/internalapi/conditions.go
  test/e2e/set/nodeconfig/nodeconfig_disksetup.go
  test/e2e/set/nodeconfig/nodeconfig_optimizations.go
  test/e2e/set/nodeconfig/verify.go
  test/e2e/utils/helpers.go
Labels: kind/feature, priority/important-longterm, lgtm, size/XL, approved

#2194 Add zimnx as required dependency reviewer
  OWNERS
Labels: priority/important-longterm, kind/machinery, lgtm, size/XS, approved

#2195 Unify scheme usage
  pkg/cmd/operator/scheme.go
  pkg/cmd/operator/webhooks.go
Labels: priority/important-soon, kind/cleanup, lgtm, size/S, approved

#2197 Update UBI runtime to 9.5
  Dockerfile
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#2201 Build v1.15 documentation
  docs/source/conf.py
Labels: priority/important-soon, kind/documentation, lgtm, size/XS, approved

#2200 [v1.15] Pin image tags to v1.15
  Makefile
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_controller_deployment.yaml
  deploy/manager/prod/50_controller_deployment.yaml
  deploy/operator.yaml
  deploy/operator/50_operator.deployment.yaml
  deploy/operator/50_webhookserver.deployment.yaml
  helm/scylla-manager/Chart.yaml
  helm/scylla-operator/Chart.yaml
Labels: priority/important-soon, kind/machinery, lgtm, size/S, approved

#2207 Update GKE instance family in the quickstart to n2
  docs/source/quickstarts/gke.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved

#2206 Clarify provider disclaimer
  docs/source/quickstarts/gke.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved

#2211 Use a portable method to get systemd unit statuses
  pkg/systemd/daemon.go
  pkg/systemd/unit.go
Labels: kind/bug, priority/critical-urgent, lgtm, size/M, approved

#2208 Add tuning link to ScyllaClusters resource documentation
  docs/source/resources/scyllaclusters/basics.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved

#2214 [v1.15] Use a portable method to get systemd unit statuses
  pkg/systemd/daemon.go
  pkg/systemd/unit.go
Labels: kind/bug, priority/critical-urgent, lgtm, size/M, approved
