Repository scylladb/scylla-operator, pull requests merged in 2024-03, with the labels that each got.

#1789 Make resource helpers scheme configurable through exported variable
  pkg/resource/helpers.go
  pkg/util/resource/helpers.go
Labels: kind/feature, priority/important-longterm, lgtm, size/M, approved

#1791 Fix alternator validation
  pkg/api/scylla/validation/cluster_validation.go
  pkg/api/scylla/validation/cluster_validation_test.go
Labels: kind/bug, priority/critical-urgent, lgtm, size/L, approved

#1784 Extend Scylla Manager E2E test with progress check
  test/e2e/set/scyllacluster/scyllamanager.go
Labels: kind/feature, priority/important-longterm, lgtm, size/M, approved

#1747 Accept custom NodeConfig in script running E2E
  hack/.ci/run-e2e-gke.sh
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#1793 Add image opencontainer labels
  Dockerfile
Labels: kind/feature, priority/important-longterm, lgtm, size/XS, approved

#1800 Pass auth token on Scylla Manager cluster update
  pkg/controller/manager/sync_action.go
Labels: kind/bug, priority/important-longterm, lgtm, size/XS, approved

#1803 [v1.12] Pass auth token on Scylla Manager cluster update
  pkg/controller/manager/sync_action.go
Labels: kind/bug, priority/important-longterm, lgtm, size/XS, approved

#1798 Explicitly disable CQL over TLS in Scylla Manager cluster integration
  pkg/controller/manager/sync_action.go
Labels: kind/bug, priority/critical-urgent, lgtm, size/XS, approved

#1807 [v1.12] Explicitly disable CQL over TLS in Scylla Manager cluster integration
  pkg/controller/manager/sync_action.go
Labels: kind/bug, priority/critical-urgent, lgtm, size/XS, approved

#1814 Use gocql client's default timeouts in tests
  test/e2e/utils/datainserter.go
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#1795 Update manager to 3.2.6 and require it for v1.12
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_manager_deployment.yaml
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_manager_deployment.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  docs/source/generic.md
  docs/source/multidc/multidc.md
  docs/source/nodeoperations/restore.md
  docs/source/performance.md
  docs/source/releases.md
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  examples/scylladb/scylla.scyllacluster.yaml
  helm/deploy/manager_prod.yaml
  helm/scylla-manager/values.yaml
  helm/scylla/values.yaml
  test/e2e/fixture/scylla/scyllacluster.yaml.tmpl
Labels: kind/feature, priority/important-soon, lgtm, size/M, approved

#1817 [v1.11] Explicitly disable CQL over TLS in Scylla Manager cluster integration
  pkg/controller/manager/sync_action.go
Labels: kind/bug, priority/important-soon, lgtm, size/XS, approved

#1822 [v1.12] Fix update action loop break in manager controller
  pkg/controller/manager/sync_action.go
Labels: kind/bug, priority/important-soon, lgtm, size/XS, approved

#1828 Rollback Scylla utils image version to 5.4.0
  pkg/naming/constants.go
Labels: kind/feature, priority/critical-urgent, lgtm, size/XS, approved

#1829 [v1.12] Rollback Scylla utils image version to 5.4.0
  pkg/naming/constants.go
Labels: kind/feature, priority/critical-urgent, lgtm, size/XS, approved

#1831 Remove TLS disablement note from restore docs
  docs/source/nodeoperations/restore.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/S, approved

#1833 [v1.12] Remove TLS disablement note from restore docs
  docs/source/nodeoperations/restore.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/S, approved

#1787 Document using ScyllaDB APIs
  docs/source/clients/cql.md
  docs/source/clients/discovery.md
  docs/source/clients/index.rst
  docs/source/index.rst
Labels: priority/important-soon, kind/documentation, lgtm, size/L, approved

#1834 [v1.12] Document using ScyllaDB APIs
  docs/source/clients/cql.md
  docs/source/clients/discovery.md
  docs/source/clients/index.rst
  docs/source/index.rst
Labels: priority/important-soon, kind/documentation, lgtm, size/L, approved

#1818 Use real salted_hash in alternator e2e
  test/e2e/fixture/scylla/registry.go
  test/e2e/fixture/scylla/scylladb-config.yaml.tmpl
  test/e2e/set/scyllacluster/scyllacluster_alternator.go
Labels: kind/cleanup, priority/critical-urgent, lgtm, size/M, approved

#1835 [v1.12] Use real salted_hash in alternator e2e
  test/e2e/fixture/scylla/registry.go
  test/e2e/fixture/scylla/scylladb-config.yaml.tmpl
  test/e2e/set/scyllacluster/scyllacluster_alternator.go
Labels: kind/cleanup, priority/critical-urgent, lgtm, size/M, approved

#1823 Extend Scylla Manager E2E test with repair task update and deletion
  test/e2e/set/scyllacluster/scyllamanager.go
Labels: kind/feature, priority/important-longterm, lgtm, size/M, approved

#1836 Update cert-manager example to v1.14.4
  examples/common/cert-manager.yaml
Labels: kind/feature, priority/important-soon, lgtm, size/XXL, approved

#1840 Decouple Alternator certificates from CQL TLS feature gate
  pkg/controller/scyllacluster/sync.go
  pkg/controller/scyllacluster/sync_certs.go
  test/e2e/set/scyllacluster/verify.go
Labels: kind/bug, priority/critical-urgent, lgtm, size/L, approved

#1788 Document using Alternator API
  docs/source/clients/alternator.md
  docs/source/clients/index.rst
Labels: priority/important-soon, kind/documentation, lgtm, size/M, approved

#1843 [v1.12] Document using Alternator API
  docs/source/clients/alternator.md
  docs/source/clients/index.rst
Labels: kind/documentation, priority/critical-urgent, lgtm, size/M, approved

#1844 [v1.12] Update restore procedure docs with a workaround for Scylla OS 5.4.X and ScyllaDB Enterprise 2024.1.X
  docs/source/nodeoperations/restore.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/M, approved

#1849 Add Scheme Builder
  pkg/scheme/scheme.go
Labels: kind/feature, priority/important-soon, lgtm, size/S, approved

#1854 Add mapstructure tag to backup task spec and fix conversion funcs
  pkg/api/scylla/v1/types_cluster.go
  pkg/controller/manager/types_old.go
  pkg/controller/manager/types_old_test.go
Labels: kind/bug, priority/critical-urgent, lgtm, size/L, approved

#1859 Fix and trim release matrix to supported releases
  docs/source/releases.md
Labels: kind/documentation, priority/critical-urgent, lgtm, size/S, approved

#1864 Wire maxproc with klog and check errors
  cmd/gen-release-notes/gen-release-notes.go
  cmd/scylla-operator-tests/scylla-operator-tests.go
  cmd/scylla-operator/scylla-operator.go
  pkg/cmd/generateapireference/cmd.go
  pkg/cmd/operator/cmd.go
  pkg/cmd/releasenotes/generate.go
  pkg/cmd/tests/tests.go
  vendor/go.uber.org/automaxprocs/.codecov.yml
  vendor/go.uber.org/automaxprocs/.gitignore
  vendor/go.uber.org/automaxprocs/CHANGELOG.md
  vendor/go.uber.org/automaxprocs/CODE_OF_CONDUCT.md
  vendor/go.uber.org/automaxprocs/CONTRIBUTING.md
  vendor/go.uber.org/automaxprocs/Makefile
  vendor/go.uber.org/automaxprocs/README.md
  vendor/go.uber.org/automaxprocs/automaxprocs.go
  vendor/go.uber.org/automaxprocs/glide.yaml
  vendor/modules.txt
Labels: kind/bug, priority/important-soon, lgtm, size/L, approved

#1865 Promote v1.12 docs
  docs/source/conf.py
Labels: kind/feature, priority/important-soon, lgtm, size/XS, approved

#1866 Add release schedule for v1.13
  docs/source/releases.md
Labels: priority/important-soon, kind/documentation, lgtm, size/S, approved

#1861 Update Go version to 1.22
  .github/workflows/releases.yaml
  Dockerfile
  Makefile
  go.mod
  pkg/api/scylla/validation/cluster_validation_test.go
  pkg/api/scylla/validation/nodeconfig_validation_test.go
  pkg/assets/template.go
  pkg/auth/auth_test.go
  pkg/cmd/generateapireference/run_test.go
  pkg/cmd/operator/gather_test.go
  pkg/cmd/operator/mustgather_test.go
  pkg/cmd/operator/webhooks_test.go
  pkg/cmd/releasenotes/helpers_test.go
  pkg/cmd/releasenotes/render_test.go
  pkg/controller/manager/controller.go
  pkg/controller/manager/sync_test.go
  pkg/controller/manager/types_old_test.go
  pkg/controller/nodeconfig/controller.go
  pkg/controller/nodeconfigpod/controller.go
  pkg/controller/nodetune/tune_test.go
  pkg/controller/orphanedpv/controller.go
  pkg/controller/scyllacluster/controller.go
  pkg/controller/scyllacluster/resource_test.go
  pkg/controller/scylladbmonitoring/controller.go
  pkg/controller/scyllaoperatorconfig/controller.go
  pkg/controllerhelpers/apps_test.go
  pkg/controllerhelpers/scylla_test.go
  pkg/crypto/certcreators_test.go
  pkg/disks/block_test.go
  pkg/disks/fs_test.go
  pkg/disks/loop_test.go
  pkg/disks/raid_test.go
  pkg/gather/collect/collect_test.go
  pkg/gather/collect/printer_test.go
  pkg/kubecrypto/certs_test.go
  pkg/naming/names_test.go
  pkg/resourceapply/apps_test.go
  pkg/resourceapply/core_test.go
  pkg/resourceapply/discovery_test.go
  pkg/resourceapply/helpers_test.go
  pkg/resourceapply/networking_test.go
  pkg/resourceapply/policy_test.go
  pkg/resourceapply/rbac_test.go
  pkg/sidecar/config/config_test.go
  pkg/sidecar/identity/member_test.go
  pkg/util/algorithms/math_test.go
  pkg/util/blkutils/lsblk_test.go
  pkg/util/cpuset/mask_test.go
  pkg/util/duration/duration_string.go
  pkg/util/losetup/losetup_test.go
  pkg/util/parallel/parallel.go
  test/e2e/set/nodeconfig/nodeconfig_disksetup.go
  test/e2e/set/scyllacluster/scyllacluster_tls.go
  test/e2e/utils/datainserter.go
Labels: kind/feature, priority/important-soon, lgtm, size/L, approved, area/dependency

#1857 Validate whether Scylla container is tuned before Pod is unblocked
  pkg/controller/nodeconfigpod/sync_configmaps.go
  pkg/controller/nodetune/sync_jobs.go
  pkg/controller/nodetune/tune.go
  pkg/controllerhelpers/scylla.go
  pkg/controllerhelpers/scylla_test.go
  test/e2e/set/nodeconfig/nodeconfig_optimizations.go
  test/e2e/utils/helpers.go
Labels: kind/bug, priority/important-soon, lgtm, size/L, approved
