Repository scylladb/scylla-operator, pull requests merged in 2024-09, with the labels that each got.

#2081 Manage global configs using ScyllaOperatorConfig, add unsupported overrides and extract defaults to a common config
  Makefile
  assets/config/config.go
  assets/config/config.yaml
  assets/config/config_test.go
  assets/monitoring/grafana/v1alpha1/deployment.yaml
  assets/monitoring/prometheus/v1/prometheus.yaml
  deploy/operator.yaml
  deploy/operator/00_clusterrole_def.yaml
  deploy/operator/10_validatingwebhook.yaml
  docs/source/api-reference/groups/scylla.scylladb.com/scyllaoperatorconfigs.rst
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  examples/scylladb/scylla.scyllacluster.yaml
  go.mod
  helm/deploy/manager_prod.yaml
  helm/scylla-manager/values.yaml
  helm/scylla-operator/templates/clusterrole_def.yaml
  helm/scylla-operator/templates/validatingwebhook.yaml
  helm/scylla/values.yaml
  pkg/api/scylla/v1alpha1/scylla.scylladb.com_scyllaoperatorconfigs.yaml
  pkg/api/scylla/v1alpha1/types_operatorconfig.go
  pkg/api/scylla/v1alpha1/zz_generated.deepcopy.go
  pkg/api/scylla/validation/scyllaoperatorconfig.go
  pkg/api/scylla/validation/scyllaoperatorconfig_test.go
  pkg/cmd/operator/operator.go
  pkg/cmd/operator/webhooks.go
  pkg/controller/nodeconfig/controller.go
  pkg/controller/nodeconfig/sync_daemonsets.go
  pkg/controller/scylladbmonitoring/controller.go
  pkg/controller/scylladbmonitoring/sync.go
  pkg/controller/scylladbmonitoring/sync_grafana.go
  pkg/controller/scylladbmonitoring/sync_prometheus.go
  pkg/controller/scylladbmonitoring/sync_prometheus_test.go
  pkg/controller/scyllaoperatorconfig/resource.go
  pkg/controller/scyllaoperatorconfig/status.go
  pkg/controller/scyllaoperatorconfig/sync.go
  pkg/controllertools/errors.go
  pkg/naming/constants.go
  test/e2e/fixture/scylla/default.scyllaoperatorconfig.yaml
  test/e2e/fixture/scylla/registry.go
  test/e2e/fixture/scylla/scyllacluster.yaml.tmpl
  test/e2e/fixture/scylla/zonal.scyllacluster.yaml.tmpl
  test/e2e/framework/framework.go
  test/e2e/include.go
  test/e2e/set/nodeconfig/nodeconfig_disksetup.go
  test/e2e/set/scyllacluster/config.go
  test/e2e/set/scyllacluster/scyllacluster_pv.go
  test/e2e/set/scyllacluster/scyllacluster_replace.go
  test/e2e/set/scyllacluster/scyllacluster_upgrades.go
  test/e2e/set/scyllacluster/scyllamanager_object_storage.go
  test/e2e/set/scyllaoperatorconfig/config.go
  test/e2e/set/scyllaoperatorconfig/scyllaoperatorconfig_status.go
  test/e2e/set/scyllaoperatorconfig/scyllaoperatorconfig_webhooks.go
  test/e2e/utils/helpers.go
  test/e2e/utils/image/manifests.go
Labels: kind/feature, priority/important-soon, lgtm, size/XXL, approved, area/dependency

#2103 Update ScyllaDB versions to 6.1.1 and 2024.1.8
  assets/config/config.yaml
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  docs/source/generic.md
  docs/source/multidc/multidc.md
  docs/source/nodeoperations/restore.md
  docs/source/performance.md
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  examples/scylladb/scylla.scyllacluster.yaml
  helm/deploy/manager_prod.yaml
  helm/scylla-manager/values.yaml
  helm/scylla/values.yaml
Labels: kind/feature, priority/important-longterm, lgtm, size/M, approved

#2109 Enable building v1.14 documentation
  docs/source/conf.py
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#1918 Aggregate NodeConfig status conditions
  deploy/operator.yaml
  pkg/api/scylla/v1alpha1/scylla.scylladb.com_nodeconfigs.yaml
  pkg/api/scylla/v1alpha1/types.go
  pkg/api/scylla/v1alpha1/types_monitoring.go
  pkg/api/scylla/v1alpha1/types_nodeconfig.go
  pkg/api/scylla/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/nodeconfig/conditions.go
  pkg/controller/nodeconfig/status.go
  pkg/controller/nodeconfig/sync.go
  pkg/controller/nodeconfig/sync_clusterrolebindings.go
  pkg/controller/nodeconfig/sync_clusterroles.go
  pkg/controller/nodeconfig/sync_daemonsets.go
  pkg/controller/nodeconfig/sync_namespaces.go
  pkg/controller/nodeconfig/sync_rolebindings.go
  pkg/controller/nodeconfig/sync_roles.go
  pkg/controller/nodeconfig/sync_serviceaccounts.go
  pkg/controller/nodesetup/status.go
  pkg/controller/nodesetup/sync.go
  pkg/controllerhelpers/scylla.go
  pkg/controllerhelpers/scylla_test.go
  pkg/internalapi/conditions.go
  test/e2e/set/nodeconfig/nodeconfig_disksetup.go
  test/e2e/set/nodeconfig/nodeconfig_optimizations.go
  test/e2e/set/nodeconfig/verify.go
  test/e2e/utils/helpers.go
Labels: kind/feature, priority/important-soon, lgtm, size/XXL, approved

#2112 Make 'shared' volume mount read-write for Scylla container
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/XS, approved

#2117 Fix systemd skip in unit tests
  pkg/systemd/daemon_test.go
Labels: kind/bug, priority/critical-urgent, lgtm, size/M, approved

#2114 Parametrize webhook command
  pkg/cmd/operator/cmd.go
  pkg/cmd/operator/webhooks.go
  pkg/cmd/operator/webhooks_test.go
Labels: priority/important-soon, kind/cleanup, lgtm, size/L, approved

#2089 Update Scylla Manager version to 3.3.3
  assets/config/config.yaml
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_manager_deployment.yaml
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_manager_deployment.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  docs/source/generic.md
  docs/source/multidc/multidc.md
  docs/source/nodeoperations/restore.md
  docs/source/performance.md
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  examples/scylladb/scylla.scyllacluster.yaml
  helm/deploy/manager_prod.yaml
  helm/scylla-manager/values.yaml
  helm/scylla/values.yaml
Labels: priority/important-longterm, kind/machinery, lgtm, size/M, approved, area/dependency

#2124 Mark v1.14 as stable in documentation
  docs/source/conf.py
Labels: priority/important-soon, kind/documentation, lgtm, size/XS, approved
