Repository scylladb/scylla-operator, pull requests merged in 2024-08, with the labels that each got.

#2048 Remove default annotation from scylladb-local-xfs StorageClass in CI manifests
  hack/.ci/manifests/namespaces/local-csi-driver/00_scylladb-local-xfs.storageclass.yaml
Labels: kind/cleanup, priority/important-longterm, lgtm, size/XS, approved

#2050 Add support for S3 object storage to e2e test runner, framework and set
  pkg/cmd/tests/options.go
  test/e2e/framework/framework.go
  test/e2e/framework/testcontext.go
  test/e2e/set/scyllacluster/scyllamanager_object_storage.go
Labels: kind/feature, priority/important-soon, lgtm, size/M, approved

#2058 Fix infinite loop in tuning between sync timeout and cri client backoff
  pkg/cri/client.go
Labels: kind/bug, priority/important-soon, lgtm, size/S, approved

#2059 Adjust ci-deploy.sh rollout times to cover for graceful termination
  hack/ci-deploy.sh
Labels: priority/important-longterm, kind/machinery, lgtm, size/S, approved

#2053 Allow building images from git worktrees
  Makefile
Labels: priority/important-soon, kind/machinery, lgtm, size/S, approved

#2055 Add context on which condition failed in WaitForObjectState
  pkg/controllerhelpers/wait.go
  pkg/controllerhelpers/wait_test.go
Labels: priority/important-longterm, kind/machinery, lgtm, size/L, approved

#2070 Pin Scylla Manager version using sha reference
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_manager_deployment.yaml
  deploy/manager/prod/50_manager_deployment.yaml
  helm/scylla-manager/values.yaml
Labels: kind/bug, priority/critical-urgent, lgtm, size/S, approved

#2074 Add scylla-manager-agent readiness probe
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
Labels: kind/feature, priority/important-longterm, lgtm, size/S, approved

#2062 Substitute unbound SO_SCYLLACLUSTER_STORAGECLASS_NAME var in ci-deploy script
  hack/ci-deploy.sh
Labels: priority/important-longterm, kind/machinery, lgtm, size/XS, approved

#2064 Set explicit storageClassName in monitoring examples and docs
  docs/source/monitoring.md
  examples/monitoring/v1alpha1/scylladbmonitoring.yaml
Labels: kind/feature, priority/important-longterm, lgtm, size/XS, approved

#2073 Ensure CRI calls are not retried in NodeConfig's sync loop and have a timeout
  pkg/controller/nodetune/controller.go
  pkg/controller/nodetune/tune.go
  pkg/cri/client.go
Labels: kind/bug, priority/important-soon, lgtm, size/M, approved

#1934 Split startup logic out of ScyllaDB container
  pkg/cmd/operator/cmd.go
  pkg/cmd/operator/ignition.go
  pkg/cmd/operator/sidecar.go
  pkg/controller/ignition/controller.go
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
  pkg/controllerhelpers/tuning.go
  pkg/controllertools/errors.go
  pkg/controllertools/observer.go
  pkg/helpers/fs.go
  pkg/helpers/fs_test.go
  pkg/naming/constants.go
Labels: kind/feature, priority/important-soon, lgtm, size/XXL, approved, area/dependency

#2087 Remove host networking mentions from documentation and examples
  docs/source/generic.md
  examples/eks/cluster.yaml
  examples/gke/cluster.yaml
Labels: priority/important-soon, kind/documentation, lgtm, size/S, approved

#2088 Deprecate cpuset field in v1.ScyllaCluster
  deploy/operator.yaml
  docs/source/api-reference/groups/scylla.scylladb.com/scyllaclusters.rst
  examples/eks/cluster.yaml
  examples/gke/cluster.yaml
  helm/scylla-manager/values.schema.json
  helm/scylla/values.schema.json
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/types_cluster.go
Labels: kind/feature, priority/important-soon, lgtm, size/S, approved

#2090 Update ScyllaDB versions to 6.1.0 and 2024.1.7
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  docs/source/generic.md
  docs/source/multidc/multidc.md
  docs/source/nodeoperations/restore.md
  docs/source/performance.md
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  examples/scylladb/scylla.scyllacluster.yaml
  helm/deploy/manager_prod.yaml
  helm/scylla-manager/values.yaml
  helm/scylla/values.yaml
  test/e2e/fixture/scylla/scyllacluster.yaml.tmpl
  test/e2e/fixture/scylla/zonal.scyllacluster.yaml.tmpl
  test/e2e/set/scyllacluster/config.go
  test/e2e/set/scyllacluster/scyllamanager_object_storage.go
Labels: kind/feature, priority/important-longterm, lgtm, size/M, approved

#2094 Fix races in NodeConfig disk test
  test/e2e/set/nodeconfig/nodeconfig_disksetup.go
Labels: kind/bug, priority/important-soon, lgtm, size/M, approved

#2097 Add a note to documentation about exposeOptions being immutable
  deploy/operator.yaml
  docs/source/api-reference/groups/scylla.scylladb.com/scyllaclusters.rst
  docs/source/exposing.md
  helm/scylla-manager/values.schema.json
  helm/scylla/values.schema.json
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/types_cluster.go
Labels: priority/important-soon, kind/documentation, lgtm, size/S, approved

#2099 Validate that artifacts dir exists
  pkg/cmd/tests/options.go
Labels: kind/bug, priority/important-soon, lgtm, size/S, approved

#2100 Drop GinkgoRecover from ginkgo's container nodes
  test/e2e/set/nodeconfig/nodeconfig_disksetup.go
  test/e2e/set/nodeconfig/nodeconfig_optimizations.go
  test/e2e/set/scyllacluster/scyllacluster_alternator.go
  test/e2e/set/scyllacluster/scyllacluster_auth.go
  test/e2e/set/scyllacluster/scyllacluster_cleanup.go
  test/e2e/set/scyllacluster/scyllacluster_evictions.go
  test/e2e/set/scyllacluster/scyllacluster_expose.go
  test/e2e/set/scyllacluster/scyllacluster_external_seeds.go
  test/e2e/set/scyllacluster/scyllacluster_hostid.go
  test/e2e/set/scyllacluster/scyllacluster_rebootstrap.go
  test/e2e/set/scyllacluster/scyllacluster_replace.go
  test/e2e/set/scyllacluster/scyllacluster_sa.go
  test/e2e/set/scyllacluster/scyllacluster_scaling.go
  test/e2e/set/scyllacluster/scyllacluster_shardawareness.go
  test/e2e/set/scyllacluster/scyllacluster_sysctl.go
  test/e2e/set/scyllacluster/scyllacluster_tls.go
  test/e2e/set/scyllacluster/scyllacluster_updates.go
  test/e2e/set/scyllacluster/scyllacluster_upgrades.go
  test/e2e/set/scyllacluster/scyllacluster_webhooks.go
  test/e2e/set/scyllacluster/scyllamanager.go
  test/e2e/set/scyllacluster/scyllamanager_object_storage.go
  test/e2e/set/scylladbmonitoring/scylladbmonitoring.go
Labels: kind/bug, priority/important-soon, lgtm, size/M, approved

#2101 Fix NodeConfig e2e race check with node setup daemon
  test/e2e/set/nodeconfig/nodeconfig_optimizations.go
  test/e2e/utils/helpers.go
Labels: priority/important-soon, kind/flake, lgtm, size/XS, approved

#2091 Collect, snapshot and gracefully restore global objects in e2e test
  pkg/cmd/tests/options.go
  pkg/naming/names.go
  test/e2e/framework/cleanup.go
  test/e2e/framework/cluster.go
  test/e2e/framework/dump.go
  test/e2e/framework/framework.go
  test/e2e/framework/testcontext.go
  test/e2e/set/nodeconfig/config.go
  test/e2e/set/nodeconfig/nodeconfig_disksetup.go
  test/e2e/set/nodeconfig/nodeconfig_optimizations.go
Labels: priority/important-soon, kind/machinery, lgtm, size/XL, approved
