Repository scylladb/scylla-operator, pull requests merged in 2024-02, with the labels that each got.

#1715 Collect namespace where NodeConfig Pods are executed
  pkg/cmd/operator/mustgather.go
Labels: kind/feature, priority/important-soon, lgtm, size/XS, approved

#1713 Move ScyllaDB main config file generation from sidecar to operator
  assets/scylladb/defaultconfig.yaml
  assets/scylladb/managedconfig.cm.yaml
  assets/scylladb/registry.go
  pkg/controller/scyllacluster/conditions.go
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
  pkg/controller/scyllacluster/sync.go
  pkg/controller/scyllacluster/sync_config.go
  pkg/controller/scyllacluster/sync_statefulsets.go
  pkg/naming/constants.go
  pkg/naming/names.go
  pkg/sidecar/config/config.go
  pkg/sidecar/config/config_test.go
  test/e2e/set/scyllacluster/verify.go
Labels: priority/important-soon, kind/cleanup, lgtm, size/L, approved

#1727 Fix syntax of ScyllaCluster PreStopHook
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/XS, approved

#1728 Add identity service to ScyllaDB serving certs
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/sync_certs.go
  pkg/naming/names.go
  test/e2e/set/scyllacluster/scyllacluster_expose.go
  test/e2e/set/scyllacluster/scyllacluster_tls.go
  test/e2e/utils/helpers.go
Labels: kind/feature, priority/important-soon, lgtm, size/L, approved

#1724 Get cpuset from kubelet PodResources API
  go.mod
  go.sum
  pkg/cmd/operator/nodesetupdaemon.go
  pkg/controller/nodetune/controller.go
  pkg/controller/nodetune/sync_jobs.go
  pkg/controller/nodetune/tune.go
  pkg/controller/nodetune/tune_test.go
  pkg/kubelet/podresourcesclient.go
  vendor/k8s.io/kubelet/LICENSE
  vendor/k8s.io/kubelet/pkg/apis/podresources/v1/api.pb.go
  vendor/k8s.io/kubelet/pkg/apis/podresources/v1/api.proto
  vendor/modules.txt
Labels: kind/feature, priority/important-soon, lgtm, size/XXL, approved, area/dependency

#1731 Extend alternator proposal with using Authorization by default
  enhancements/proposals/1405-alternator/README.md
Labels: priority/important-soon, kind/design, lgtm, size/S, approved

#1737 Extend ScyllaCluster status with aggregated data for all racks
  deploy/operator.yaml
  docs/source/api-reference/groups/scylla.scylladb.com/scyllaclusters.rst
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/types_cluster.go
  pkg/api/scylla/v1/zz_generated.deepcopy.go
  pkg/controller/scyllacluster/status.go
Labels: kind/feature, priority/important-soon, lgtm, size/L, approved

#1734 Enable internode compression by default
  assets/scylladb/managedconfig.cm.yaml
  pkg/controller/scyllacluster/resource_test.go
Labels: kind/feature, priority/important-soon, lgtm, size/XS, approved

#1730 Add server-side printers to our APIs
  deploy/operator.yaml
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/types_cluster.go
  pkg/api/scylla/v1alpha1/scylla.scylladb.com_nodeconfigs.yaml
  pkg/api/scylla/v1alpha1/scylla.scylladb.com_scylladbmonitorings.yaml
  pkg/api/scylla/v1alpha1/scylla.scylladb.com_scyllaoperatorconfigs.yaml
  pkg/api/scylla/v1alpha1/types_monitoring.go
  pkg/api/scylla/v1alpha1/types_nodeconfig.go
  pkg/api/scylla/v1alpha1/types_operatorconfig.go
Labels: kind/feature, priority/important-longterm, lgtm, size/L, approved

#1740 Change minTerminationGracePeriodSeconds to *int32
  pkg/api/scylla/v1/types_cluster.go
  pkg/api/scylla/v1/zz_generated.deepcopy.go
  pkg/api/scylla/validation/cluster_validation.go
  pkg/api/scylla/validation/cluster_validation_test.go
  pkg/controller/scyllacluster/resource.go
Labels: kind/bug, priority/important-soon, lgtm, size/S, approved

#1738 Add minReadySeconds and podReadinessGates to ScyllaCluster spec
  deploy/operator.yaml
  docs/source/api-reference/groups/scylla.scylladb.com/scyllaclusters.rst
  helm/scylla-manager/values.schema.json
  helm/scylla/values.schema.json
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/types_cluster.go
  pkg/api/scylla/v1/zz_generated.deepcopy.go
  pkg/api/scylla/validation/cluster_validation.go
  pkg/api/scylla/validation/cluster_validation_test.go
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
Labels: kind/feature, priority/important-soon, lgtm, size/L, approved

#1691 Extend NodeConfig with loop device management
  deploy/operator.yaml
  docs/source/api-reference/groups/scylla.scylladb.com/nodeconfigs.rst
  pkg/api/scylla/v1alpha1/scylla.scylladb.com_nodeconfigs.yaml
  pkg/api/scylla/v1alpha1/types_nodeconfig.go
  pkg/api/scylla/v1alpha1/zz_generated.deepcopy.go
  pkg/api/scylla/validation/nodeconfig_validation.go
  pkg/api/scylla/validation/nodeconfig_validation_test.go
  pkg/controller/nodesetup/conditions.go
  pkg/controller/nodesetup/sync.go
  pkg/controller/nodesetup/sync_filesystems.go
  pkg/controller/nodesetup/sync_loopdevices.go
  pkg/controller/nodesetup/sync_mounts.go
  pkg/controller/nodesetup/sync_raids.go
  pkg/disks/loop.go
  pkg/disks/loop_test.go
  pkg/disks/raid.go
  pkg/disks/raid_test.go
  pkg/naming/constants.go
  pkg/util/losetup/losetup.go
  test/e2e/set/nodeconfig/nodeconfig_disksetup.go
  test/e2e/set/nodeconfig/verify.go
Labels: kind/feature, priority/important-soon, lgtm, size/XXL, approved

#1746 Always use default minReadySeconds so identity service works
  pkg/controller/scyllacluster/resource.go
Labels: kind/bug, priority/important-soon, lgtm, size/XS, approved

#1750 Fix headings in 'Deploying Scylla stack using Helm Charts' doc page
  docs/source/helm.md
Labels: priority/important-soon, kind/documentation, lgtm, size/XS, approved

#1744 Stop Scylla Manager task before deletion
  pkg/controller/manager/sync_action.go
Labels: kind/bug, priority/important-soon, lgtm, size/S, approved

#1755 Enable building docs for v1.12 branch
  docs/source/conf.py
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#1749 Fix typo in log message
  pkg/controller/scyllaoperatorconfig/sync.go
Labels: kind/cleanup, priority/backlog, lgtm, size/XS, approved, ok-to-test

#1771 Update version requirements for Scylla Manager
  docs/source/releases.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved

#1777 [v1.12] Update version requirements for Scylla Manager
  docs/source/releases.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved

#1776 Return empty list of loop devices when `losetup` doesn't print anything
  pkg/util/losetup/losetup.go
  pkg/util/losetup/losetup_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/L, approved

#1782 [v1.12] Return empty list of loop devices when `losetup` doesn't print anything
  pkg/util/losetup/losetup.go
  pkg/util/losetup/losetup_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/L, approved

#1780 Change default minReadySeconds to 5 seconds
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
Labels: kind/feature, priority/important-soon, lgtm, size/XS, approved

#1783 Update default ScyllaDB version to 5.4.3
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  docs/source/generic.md
  docs/source/multidc/multidc.md
  docs/source/performance.md
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  examples/scylladb/scylla.scyllacluster.yaml
  helm/deploy/manager_prod.yaml
  helm/scylla-manager/values.yaml
  helm/scylla/values.yaml
  test/e2e/fixture/scylla/scyllacluster.yaml.tmpl
  test/e2e/set/scyllacluster/config.go
Labels: kind/feature, priority/important-soon, lgtm, size/M, approved

#1781 [v1.12] Change default minReadySeconds to 5 seconds
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
Labels: kind/feature, priority/important-soon, lgtm, size/XS, approved

#1774 Collect logs from ephemeral containers in CI and must-gather
  pkg/gather/collect/collect.go
  pkg/gather/collect/collect_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/L, approved
