Repository scylladb/scylla-operator, pull requests merged in 2024-01, with the labels that each got.

#1661 Replace project-specific scylladb_markdown extension with sphinx-scylladb-markdown extension
  docs/poetry.lock
  docs/pyproject.toml
  docs/source/_ext/scylladb_markdown.py
  docs/source/conf.py
Labels: priority/important-longterm, kind/machinery, lgtm, size/L, approved, ok-to-test

#1627 Fix typo in helm docs
  docs/source/helm.md
Labels: needs-priority, lgtm, size/XS, approved, ok-to-test, do-not-merge/needs-kind

#1665 Add proposal for specifying ScyllaCluster metadata
  enhancements/proposals/1665-metadata/README.md
Labels: priority/important-soon, kind/design, lgtm, size/L, approved

#1659 Unify waiting for object state
  pkg/cmd/operator/operator.go
  pkg/cmd/operator/sidecar.go
  pkg/controllerhelpers/wait.go
  test/e2e/framework/util.go
  test/e2e/set/nodeconfig/nodeconfig_disksetup.go
  test/e2e/set/nodeconfig/nodeconfig_optimizations.go
  test/e2e/set/scyllacluster/scyllacluster_auth.go
  test/e2e/set/scyllacluster/scyllacluster_cleanup.go
  test/e2e/set/scyllacluster/scyllacluster_evictions.go
  test/e2e/set/scyllacluster/scyllacluster_expose.go
  test/e2e/set/scyllacluster/scyllacluster_external_seeds.go
  test/e2e/set/scyllacluster/scyllacluster_hostid.go
  test/e2e/set/scyllacluster/scyllacluster_pv.go
  test/e2e/set/scyllacluster/scyllacluster_rebootstrap.go
  test/e2e/set/scyllacluster/scyllacluster_replace.go
  test/e2e/set/scyllacluster/scyllacluster_sa.go
  test/e2e/set/scyllacluster/scyllacluster_scaling.go
  test/e2e/set/scyllacluster/scyllacluster_shardawareness.go
  test/e2e/set/scyllacluster/scyllacluster_sysctl.go
  test/e2e/set/scyllacluster/scyllacluster_tls.go
  test/e2e/set/scyllacluster/scyllacluster_updates.go
  test/e2e/set/scyllacluster/scyllacluster_upgrades.go
  test/e2e/set/scyllacluster/scyllacluster_webhooks.go
  test/e2e/set/scyllacluster/scyllamanager.go
  test/e2e/set/scylladbmonitoring/scylladbmonitoring.go
  test/e2e/utils/helpers.go
Labels: priority/important-soon, kind/cleanup, lgtm, size/XL, approved, ¯\_(ツ)_/¯

#1654 Make haproxy manifests work on both amd64 and arm64
  examples/third-party/haproxy-ingress.yaml
  examples/third-party/haproxy-ingress/10_ingress-default-backend.deploy.yaml
Labels: kind/feature, priority/important-soon, lgtm, size/XS, approved

#1681 Add zendesk tag for docs
  docs/poetry.lock
  docs/pyproject.toml
  docs/source/conf.py
Labels: kind/documentation, priority/important-longterm, lgtm, size/M, approved, ok-to-test

#1685 Revert introspection
  deploy/operator.yaml
  deploy/operator/50_operator.deployment.yaml
  helm/scylla-operator/templates/operator.deployment.yaml
  pkg/cmd/operator/operator.go
Labels: kind/bug, priority/important-soon, lgtm, size/L, approved

#1658 Wait for kube-root-ca.crt when creating e2e namespace
  test/e2e/framework/framework.go
Labels: priority/important-soon, kind/machinery, lgtm, size/S, approved

#1678 Update documentation about restoring from backup
  docs/source/nodeoperations/restore.md
Labels: kind/documentation, priority/critical-urgent, lgtm, size/L, approved

#1688 [v1.11] Add examples for popular platforms regarding LoadBalancer service exposing
  docs/poetry.lock
  docs/pyproject.toml
  docs/source/conf.py
  docs/source/exposing.md
Labels: priority/important-soon, kind/documentation, lgtm, size/M, approved

#1687 [v1.11] Update documentation about restoring from backup
  docs/source/nodeoperations/restore.md
Labels: kind/documentation, priority/critical-urgent, lgtm, size/L, approved

#1686 [v1.11] Revert introspection
  deploy/operator/50_operator.deployment.yaml
  examples/common/operator.yaml
  helm/scylla-operator/templates/operator.deployment.yaml
  pkg/cmd/operator/operator.go
Labels: kind/bug, priority/important-soon, lgtm, size/L, approved

#1563 Automatically create explicit dest-dir for must-gather
  pkg/cmd/operator/gatherbase.go
Labels: kind/feature, priority/important-longterm, lgtm, size/S, approved

#1699 Wait for e2e Pod even if logs end prematurely
  hack/.ci/run-e2e-gke.sh
Labels: priority/important-soon, kind/flake, lgtm, size/XS, approved

#1700 Fix kubectl logs retry in gke e2e script
  hack/.ci/run-e2e-gke.sh
Labels: priority/important-soon, kind/flake, lgtm, size/XS, approved

#1703 Add Apply functions for corev1.Endpoints and discoveryv1.EndpointSlices
  pkg/resourceapply/core.go
  pkg/resourceapply/core_test.go
  pkg/resourceapply/discovery.go
  pkg/resourceapply/discovery_test.go
Labels: priority/important-soon, kind/machinery, lgtm, size/XXL, approved

#1706 Replace nowSafety buffer with zero-value datetime in manager task scheduling
  pkg/controller/manager/types_old.go
Labels: kind/bug, priority/important-longterm, lgtm, size/XS, approved

#1664 Inherit and customize ScyllaCluster labels and annotations
  deploy/operator.yaml
  docs/source/api-reference/groups/scylla.scylladb.com/scyllaclusters.rst
  helm/scylla-manager/values.schema.json
  helm/scylla/templates/scyllacluster.yaml
  helm/scylla/values.schema.json
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/types_cluster.go
  pkg/api/scylla/v1/zz_generated.deepcopy.go
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
  pkg/test/unit/helpers.go
  test/e2e/set/scyllacluster/scyllacluster_expose.go
Labels: kind/feature, priority/important-soon, lgtm, size/XL, approved

#1707 Drain the node before Pod is terminated
  deploy/operator.yaml
  docs/source/api-reference/groups/scylla.scylladb.com/scyllaclusters.rst
  helm/scylla-manager/values.schema.json
  helm/scylla/values.schema.json
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/types_cluster.go
  pkg/api/scylla/validation/cluster_validation.go
  pkg/api/scylla/validation/cluster_validation_test.go
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
Labels: kind/feature, priority/important-soon, lgtm, size/M, approved
