Repository scylladb/scylla-operator, pull requests merged in 2024-10, with the labels that each got.

#2136 Add a deprecation notice to ScyllaCluster's HostNetworking
  deploy/operator.yaml
  docs/source/api-reference/groups/scylla.scylladb.com/scyllaclusters.rst
  helm/scylla-manager/values.schema.json
  helm/scylla/values.schema.json
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/types_cluster.go
Labels: kind/cleanup, priority/important-longterm, lgtm, size/S, approved

#2132 Update docs theme to 1.8
  docs/poetry.lock
  docs/pyproject.toml
Labels: priority/important-longterm, kind/machinery, lgtm, size/L, approved, ok-to-test

#2138 Update poetry image tag to poetry-1.8 in docs' dev readme
  docs/README-dev.md
Labels: priority/important-longterm, kind/machinery, lgtm, size/XS, approved

#2121 Switch runtime image to the new UBI base image
  Dockerfile
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#2139 Remove support for deprecated `cpuset` field
  deploy/operator.yaml
  docs/source/api-reference/groups/scylla.scylladb.com/scyllaclusters.rst
  helm/scylla-manager/values.schema.json
  helm/scylla/values.schema.json
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/types_cluster.go
  pkg/api/scylla/validation/cluster_validation.go
  pkg/sidecar/config/config.go
Labels: kind/feature, priority/important-soon, lgtm, size/M, approved

#2134 Propagate mount unit failures and stop reconciling preexisting units unmanaged by NodeConfig
  pkg/controller/nodesetup/sync_mounts.go
  pkg/systemd/daemon.go
  pkg/systemd/unit.go
  pkg/systemd/unit_test.go
  test/e2e/set/nodeconfig/nodeconfig_disksetup.go
Labels: kind/feature, priority/important-soon, lgtm, size/XL, approved

#2143 Fix manager tasks' status errors not being cleared on failed status updates for tasks present in manager state
  pkg/controller/manager/status.go
  pkg/controller/manager/sync_action.go
Labels: kind/bug, priority/important-soon, lgtm, size/M, approved

#2128 Update release schedule and supported versions
  docs/source/releases.md
Labels: priority/important-soon, kind/documentation, lgtm, size/S, approved

#2129 Fix ScyllaDBDatacenter controller selector and resource naming
  assets/scylladb/managedconfig.cm.yaml
  pkg/controller/scylladbdatacenter/resource.go
  pkg/controller/scylladbdatacenter/resource_test.go
  pkg/naming/constants.go
  pkg/naming/labels.go
  pkg/naming/names.go
Labels: kind/bug, priority/important-soon, lgtm, size/L, approved

#2137 Move resolution of developerMode and additionalScyllaDBArguments to Operator
  deploy/operator.yaml
  deploy/operator/00_scyllacluster_member_clusterrole_def.yaml
  helm/scylla-operator/templates/scyllacluster_member_clusterrole_def.yaml
  pkg/api/scylla/validation/cluster_validation.go
  pkg/cmd/operator/sidecar.go
  pkg/controller/scylladbdatacenter/resource.go
  pkg/controller/scylladbdatacenter/resource_test.go
  pkg/semver/version.go
  pkg/sidecar/config/config.go
  pkg/sidecar/identity/member.go
  pkg/sidecar/identity/member_test.go
Labels: kind/feature, priority/important-soon, lgtm, size/L, approved

#2151 Fix storageClassName field location in monitoring example
  examples/monitoring/v1alpha1/scylladbmonitoring.yaml
Labels: kind/bug, priority/important-soon, lgtm, size/XS, approved

#2154 Update gke.md about applying xfs storageclass
  docs/source/gke.md
Labels: needs-priority, lgtm, size/XS, approved, ok-to-test, do-not-merge/needs-kind

#2142 Set managed hash labels in manager tasks and only update tasks when managed hash changes
  deploy/operator.yaml
  docs/source/api-reference/groups/scylla.scylladb.com/scyllaclusters.rst
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/types_cluster.go
  pkg/api/scylla/v1/zz_generated.deepcopy.go
  pkg/controller/manager/status.go
  pkg/controller/manager/sync.go
  pkg/controller/manager/sync_action.go
  pkg/controller/manager/sync_test.go
  pkg/controller/manager/types_old.go
  pkg/controller/manager/types_old_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/XL, approved

#2156 Use Scylla Manager cluster labels for cluster reconciliation
  pkg/controller/manager/status.go
  pkg/controller/manager/sync.go
  pkg/controller/manager/sync_action.go
  pkg/controller/manager/sync_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/XXL, approved

#2122 Update golang to 1.23
  Dockerfile
  go.mod
Labels: priority/important-longterm, kind/machinery, lgtm, size/XS, approved, area/dependency

#2162 Update Git Clone command
  docs/source/generic.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved

#2160 Set open file limit for ScyllaDB processes
  pkg/cmd/operator/cmd.go
  pkg/cmd/operator/nodesetupdaemon.go
  pkg/cmd/operator/rlimitsjob.go
  pkg/cmd/operator/rlimitsjob_test.go
  pkg/controller/nodeconfig/resource.go
  pkg/controller/nodeconfig/sync_rolebindings.go
  pkg/controller/nodeconfig/sync_roles.go
  pkg/controller/nodeconfig/sync_serviceaccounts.go
  pkg/controller/nodeconfigpod/sync_configmaps.go
  pkg/controller/nodetune/controller.go
  pkg/controller/nodetune/resource.go
  pkg/controller/nodetune/sync_jobs.go
  pkg/cri/client.go
  pkg/naming/constants.go
  test/e2e/set/nodeconfig/nodeconfig_optimizations.go
Labels: kind/feature, priority/important-soon, lgtm, size/XL, approved

#2164 Update ScyllaDB versions to OS 6.2.0 and Enterprise 2024.1.11
  assets/config/config.yaml
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  docs/source/generic.md
  docs/source/multidc/multidc.md
  docs/source/nodeoperations/restore.md
  docs/source/performance.md
  examples/eks/cluster.yaml
  examples/generic/cluster.yaml
  examples/gke/cluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  examples/scylladb/scylla.scyllacluster.yaml
  helm/deploy/manager_prod.yaml
  helm/scylla-manager/values.yaml
  helm/scylla/values.yaml
Labels: priority/important-longterm, kind/machinery, lgtm, size/M, approved

#2170 Use server-side apply when deploying aggregated manifests
  docs/source/generic.md
Labels: priority/important-soon, kind/documentation, lgtm, size/XS, approved

#2167 Update docs theme to 1.8.3
  docs/poetry.lock
Labels: kind/documentation, priority/important-longterm, lgtm, size/XL, approved, ok-to-test

#2173 [v1.13] Fix systemd skip in unit tests
  pkg/systemd/daemon_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/M, approved

#2174 [v1.14] Fix systemd skip in unit tests
  pkg/systemd/daemon_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/M, approved

#2171 [v1.14] Use server-side apply when deploying aggregated manifests
  docs/source/generic.md
Labels: priority/important-soon, kind/documentation, lgtm, size/XS, approved

#2168 Fix prunning of tuning related Roles and RoleBindings
  pkg/controller/nodeconfig/sync_rolebindings.go
  pkg/controller/nodeconfig/sync_roles.go
Labels: kind/bug, priority/important-soon, lgtm, size/XS, approved

#2037 Add support for service monitors' custom labels in Scylla Helm chart
  helm/scylla-manager/templates/manager_servicemonitor.yaml
  helm/scylla-manager/values.schema.json
  helm/scylla-manager/values.schema.template.json
  helm/scylla-manager/values.yaml
  helm/scylla/templates/servicemonitor.yaml
  helm/scylla/values.yaml
Labels: priority/important-longterm, kind/machinery, lgtm, size/S, approved, ok-to-test

#2176 Bump ScyllaDB utils image to latest stable
  assets/config/config.yaml
Labels: kind/feature, priority/important-longterm, lgtm, size/XS, approved

#2175 Fix nonreliable method of validating shardawareness in e2e's
  assets/config/config.yaml
  pkg/util/cql/frame.go
  pkg/util/cql/frame_test.go
  test/e2e/set/scyllacluster/scyllacluster_shardawareness.go
Labels: priority/important-soon, kind/flake, lgtm, size/L, approved
