Repository scylladb/scylla-operator, pull requests merged in 2024-07, with the labels that each got.

#1991 Bump default ScyllaDB version used in E2E's to 6.0.1
  test/e2e/fixture/scylla/scyllacluster.yaml.tmpl
  test/e2e/set/scyllacluster/config.go
  test/e2e/set/scyllacluster/scyllacluster_alternator.go
  test/e2e/set/scyllacluster/scyllacluster_scaling.go
  test/e2e/set/scyllacluster/scyllamanager_object_storage.go
Labels: kind/feature, priority/important-soon, lgtm, size/L, approved

#1998 Bump documentation dependencies
  docs/poetry.lock
Labels: priority/important-soon, kind/documentation, lgtm, size/M, approved

#1871 Update release procedures
  release.md
Labels: priority/important-soon, kind/documentation, lgtm, size/L, approved

#1999 Fix flakiness of cleanup E2E test
  test/e2e/set/scyllacluster/scyllacluster_cleanup.go
  test/e2e/utils/helpers.go
Labels: priority/important-soon, kind/flake, lgtm, size/M, approved

#2002 Add resourceapply helpers for Pods
  pkg/resourceapply/core.go
  pkg/resourceapply/core_test.go
Labels: kind/feature, priority/important-soon, lgtm, size/XL, approved

#2004 Add resourceapply helpers for PersistentVolumeClaims
  pkg/resourceapply/core.go
  pkg/resourceapply/core_test.go
Labels: kind/feature, priority/important-soon, lgtm, size/XL, approved

#2000 Fix NodeConfig controller handlers to react on related object updates
  pkg/controller/nodeconfig/controller.go
  pkg/controllerhelpers/handlers.go
Labels: kind/bug, priority/important-soon, lgtm, size/M, approved

#2008 Add support for forceRedeploymentReason in Helm chart
  helm/scylla/templates/scyllacluster.yaml
  helm/scylla/values.yaml
Labels: kind/feature, priority/important-longterm, lgtm, size/XS, approved, ok-to-test

#1971 Add dedicated ServiceAccount for perftune jobs
  deploy/operator.yaml
  deploy/operator/00_clusterrole_def.yaml
  helm/scylla-operator/templates/clusterrole_def.yaml
  pkg/cmd/operator/operator.go
  pkg/controller/nodeconfig/controller.go
  pkg/controller/nodeconfig/resource.go
  pkg/controller/nodeconfig/sync.go
  pkg/controller/nodeconfig/sync_rolebindings.go
  pkg/controller/nodeconfig/sync_roles.go
  pkg/controller/nodeconfig/sync_serviceaccounts.go
  pkg/controller/nodetune/resource.go
  pkg/naming/constants.go
  pkg/resourceapply/rbac.go
  pkg/resourceapply/rbac_test.go
Labels: kind/feature, priority/important-soon, lgtm, size/XL, approved

#2009 Stop depending on default StorageClass' presence for ScyllaClusters in our manifests, examples, scripts and tests
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  examples/scylladb/scylla.scyllacluster.yaml
  hack/.ci/lib/e2e.sh
  hack/.ci/run-e2e-gke-release.sh
  hack/.ci/run-e2e-gke.sh
  hack/ci-deploy-release.sh
  hack/ci-deploy.sh
  helm/deploy/manager_prod.yaml
  helm/scylla-manager/values.yaml
  helm/scylla/values.yaml
  pkg/cmd/tests/options.go
  test/e2e/fixture/scylla/scyllacluster.yaml.tmpl
  test/e2e/fixture/scylla/zonal.scyllacluster.yaml.tmpl
  test/e2e/framework/framework.go
  test/e2e/framework/testcontext.go
Labels: kind/feature, priority/important-soon, lgtm, size/M, approved

#2022 Update node setup image digest to latest multiplatform
  test/e2e/utils/image/manifests.go
Labels: kind/bug, priority/critical-urgent, lgtm, size/XS, approved

#2020 Create a deploy directory per kubeconfig in CI release scripts
  hack/.ci/run-e2e-gke-release.sh
  hack/ci-deploy-release.sh
Labels: kind/bug, priority/important-soon, lgtm, size/S, approved

#2018 Make warning about using performance tuning more explicit
  docs/source/performance.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved, ok-to-test

#2024 Update supported releases in docs and stop building unsupported branches
  docs/source/conf.py
  docs/source/releases.md
Labels: priority/important-soon, kind/documentation, lgtm, size/XS, approved

#2031 Bump local-csi-driver to 0.4.1-rc.0 in CI
  hack/.ci/manifests/namespaces/local-csi-driver/50_daemonset.yaml
Labels: kind/feature, priority/important-soon, lgtm, size/XS, approved

#2032 Update stable version of scylladb/local-csi-driver
  examples/common/local-volume-provisioner/local-csi-driver/50_daemonset.yaml
  hack/.ci/manifests/namespaces/local-csi-driver/50_daemonset.yaml
Labels: needs-priority, lgtm, size/XS, approved, do-not-merge/needs-kind

#2027 Remove IP Address based node replace procedure
  pkg/controller/scyllacluster/resource.go
  pkg/controller/scyllacluster/resource_test.go
  pkg/controller/scyllacluster/sync_services.go
  pkg/sidecar/config/config.go
  test/e2e/set/scyllacluster/scyllacluster_replace.go
Labels: kind/feature, priority/important-soon, lgtm, size/L, approved

#2035 Remove pre-rollout check validating ScyllaDB version
  pkg/controller/scyllacluster/sync.go
  pkg/controller/scyllacluster/sync_services.go
  pkg/controller/scyllacluster/sync_statefulsets.go
  pkg/controller/scyllacluster/validation.go
  pkg/scyllafeatures/scyllafeatures.go
Labels: priority/important-soon, kind/cleanup, lgtm, size/M, approved

#2033 Use identical file system for node tuning and keep symlinks working
  pkg/controller/nodeconfig/resource.go
Labels: kind/bug, priority/important-soon, lgtm, size/L, approved

#2039 Set an explicit key for gcs-service-account-credentials secret in e2e scripts
  hack/.ci/lib/e2e.sh
Labels: priority/important-longterm, kind/machinery, lgtm, size/XS, approved

#2041 Increase operator cpu request
  deploy/operator.yaml
  deploy/operator/50_operator.deployment.yaml
  helm/deploy/operator.yaml
Labels: priority/important-soon, kind/failing-test, lgtm, size/XS, approved

#2040 Add duration to certificate creation logs
  pkg/kubecrypto/certs.go
Labels: kind/feature, priority/important-longterm, lgtm, size/XS, approved

#2044 Use canonical CRD locations in helm CRD symlinks
  helm/scylla-operator/crds/00_scylla.scylladb.com_scyllaclusters.yaml
  helm/scylla-operator/crds/00_scylla.scylladb.com_scyllaoperatorconfigs.yaml
Labels: priority/important-soon, kind/cleanup, lgtm, size/XS, approved

#2047 Make parallelism configurable in e2e lib
  hack/.ci/lib/e2e.sh
Labels: kind/feature, priority/important-soon, lgtm, size/XS, approved
