Repository scylladb/scylla-operator, pull requests merged in 2025-07, with the labels that each got.

#2728 Add runtime information collection to must-gather
  pkg/cmd/operator/gather.go
  pkg/cmd/operator/gatherbase.go
  pkg/cmd/operator/mustgather.go
  pkg/controllerhelpers/core.go
  pkg/gather/collect/collect.go
  pkg/gather/collect/collect_test.go
  pkg/gather/collect/podcollector.go
  pkg/gather/collect/resourcecollector.go
  pkg/gather/collect/resourcewriter.go
  test/e2e/framework/cleanup.go
  test/e2e/framework/cluster.go
  test/e2e/framework/dump.go
  test/e2e/set/nodeconfig/nodeconfig_disksetup.go
  test/e2e/set/nodeconfig/nodeconfig_optimizations.go
  test/e2e/set/remotekubernetescluster/remotekubernetescluster_finalizer.go
  test/e2e/set/scyllaoperatorconfig/scyllaoperatorconfig_status.go
  test/e2e/utils/clusters.go
Labels: priority/important-longterm, kind/machinery, lgtm, size/XL, approved

#2740 Recommend using multi-rack clusters in documentation
  docs/source/.internal/rf-warning.md
  docs/source/resources/scyllaclusters/basics.md
  docs/source/resources/scyllaclusters/multidc/multidc.md
Labels: priority/important-soon, kind/documentation, lgtm, size/L, approved

#2622 Refactor ScyllaDBCluster controller resources specs
  pkg/controller/scylladbcluster/resource.go
  pkg/controller/scylladbdatacenter/resource.go
  pkg/scylla/consts.go
Labels: kind/cleanup, priority/important-longterm, lgtm, size/L, approved

#2727 [v1.17] Make the Git references in docs point at the release branch instead of `master`
  docs/source/installation/gitops.md
  docs/source/quickstarts/eks.md
Labels: priority/important-soon, kind/documentation, lgtm, size/L, approved

#2756 Stop relying on KUBECONFIG_DIR env var in E2E machinery
  hack/.ci/lib/e2e.sh
Labels: priority/important-longterm, kind/machinery, lgtm, size/S, approved

#2679 Ensure runtime namespaces are collected regardless of ScyllaDBCluster rollout success
  pkg/controller/scylladbcluster/resource.go
  pkg/naming/names.go
  test/e2e/framework/cleanup.go
  test/e2e/set/scylladbcluster/multidatacenter/scylladbcluster_boostrap.go
  test/e2e/set/scylladbcluster/multidatacenter/scylladbcluster_config.go
  test/e2e/set/scylladbcluster/multidatacenter/scylladbcluster_fault_tolerance.go
  test/e2e/set/scylladbcluster/multidatacenter/scylladbcluster_finalizer.go
  test/e2e/utils/clusters.go
Labels: kind/cleanup, priority/important-longterm, lgtm, size/M, approved

#2770 Do not mention standalone Manager Controller
  docs/source/architecture/components-cluster_scoped.svg
  docs/source/architecture/components.odg
  docs/source/architecture/deploy.odg
  docs/source/architecture/manager.md
  docs/source/installation/deploy.odg
  docs/source/installation/deploy.svg
  docs/source/installation/helm.md
  docs/source/installation/overview.md
Labels: priority/important-soon, kind/documentation, lgtm, size/XL, approved

#2794 Change the default ScyllaDBCluster topology used in E2E test to 3x3x1 to survive rollouts
  test/e2e/fixture/scylla/scylladbcluster.yaml.tmpl
  test/e2e/utils/verification/scylladbcluster/verify.go
Labels: priority/important-soon, kind/flake, lgtm, size/S, approved

#2780 Support backup and repair task scheduling for v1alpha1.ScyllaDBCluster
  deploy/operator.yaml
  docs/source/api-reference/groups/scylla.scylladb.com/scylladbmanagertasks.rst
  pkg/api/scylla/v1alpha1/scylla.scylladb.com_scylladbmanagertasks.yaml
  pkg/api/scylla/v1alpha1/types_scylladbmanagertask.go
  pkg/api/scylla/validation/scylladbmanagertask_validation.go
  pkg/api/scylla/validation/scylladbmanagertask_validation_test.go
  test/e2e/include.go
  test/e2e/set/scyllacluster/scyllamanager.go
  test/e2e/set/scyllacluster/scyllamanager_object_storage.go
  test/e2e/set/scylladbmanagertask/multidatacenter/scylladbmanagertask_scylladbcluster_globalmanager.go
  test/e2e/set/scylladbmanagertask/multidatacenter/scylladbmanagertask_scylladbcluster_globalmanager_object_storage.go
  test/e2e/set/scylladbmanagertask/scylladbmanagertask_scylladbdatacenter_globalmanager_object_storage.go
  test/e2e/set/scylladbmanagertask/scylladbmanagertask_scylladbdataceter_globalmanager.go
  test/e2e/utils/manager.go
  test/e2e/utils/v1alpha1/helpers.go
  test/e2e/utils/verification/scylladbcluster/cql.go
  test/e2e/utils/verification/scylladbmanager.go
Labels: kind/feature, priority/important-soon, lgtm, size/XXL, approved

#2790 Update ScyllaDB Manager to 3.5.1
  assets/config/config.yaml
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_manager_deployment.yaml
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_manager_deployment.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  docs/source/conf.py
  docs/source/resources/scyllaclusters/basics.md
  docs/source/resources/scyllaclusters/multidc/multidc.md
  docs/source/resources/scyllaclusters/nodeoperations/restore.md
  docs/source/resources/scylladbclusters/scylladbclusters.md
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  examples/scylladb/scylla.scyllacluster.yaml
  helm/deploy/manager_prod.yaml
  helm/scylla-manager/values.yaml
  helm/scylla/values.yaml
Labels: priority/important-soon, lgtm, size/M, approved, kind/dependency-bump

#2806 [v1.18] Pin tags to 1.18
  Makefile
  deploy/operator.yaml
  deploy/operator/50_operator.deployment.yaml
  deploy/operator/50_webhookserver.deployment.yaml
  helm/scylla-manager/Chart.yaml
  helm/scylla-operator/Chart.yaml
Labels: priority/important-soon, kind/documentation, lgtm, size/XS, approved

#2809 Update poetry to 2.1.3
  docs/Makefile
  docs/README-dev.md
  docs/poetry.lock
  docs/pyproject.toml
Labels: priority/important-longterm, lgtm, size/L, approved, kind/dependency-bump

#2818 Fix release workflow to not mark old patches as latest
  .github/actions/release-notes/action.yaml
Labels: priority/important-longterm, kind/machinery, lgtm, size/S, approved

#2823 Don't provision 2025.3 and 2025.3.0 Grafana platform dashboards
  assets/monitoring/grafana/v1alpha1/grafanadashboards.go
  assets/monitoring/grafana/v1alpha1/grafanadashboards_test.go
Labels: kind/feature, priority/important-soon, lgtm, size/S, approved

#2824 Fix variable substitutions for multiversion documentation
  docs/source/_ext/myst_multiversion_substitutions.py
  docs/source/conf.py
  docs/source/installation/gitops.md
  docs/source/installation/helm.md
  docs/source/quickstarts/eks.md
  docs/source/resources/scyllaclusters/basics.md
  docs/source/resources/scyllaclusters/multidc/multidc.md
  docs/source/resources/scyllaclusters/nodeoperations/restore.md
  docs/source/resources/scylladbclusters/scylladbclusters.md
Labels: priority/important-soon, kind/documentation, lgtm, size/L, approved

#2811 Do not use global http.DefaultTransport directly in manager client creation
  pkg/controllerhelpers/scylladbmanager.go
Labels: priority/important-soon, kind/cleanup, lgtm, size/XS, approved

#2829 Fix Grafana container image reference to use a multi-arch index
  assets/config/config.yaml
Labels: kind/bug, priority/critical-urgent, lgtm, size/XS, approved

#2830 [v1.18] Fix Grafana container image reference to use a multi-arch index
  assets/config/config.yaml
Labels: kind/bug, priority/critical-urgent, lgtm, size/XS, approved

#2836 Grant Gateway API RBAC to haproxy ingress controller
  examples/third-party/haproxy-ingress.yaml
  examples/third-party/haproxy-ingress/10_clusterrole.yaml
Labels: priority/important-soon, kind/cleanup, lgtm, size/M, approved

#2747 Update docs theme 1.8.7
  docs/poetry.lock
  docs/source/_static/custom.css
  docs/source/_static/mascots/logo.svg
  docs/source/conf.py
  docs/source/index.md
  docs/source/installation/gitops.md
  docs/source/resources/common/exposing.md
  docs/source/resources/overview.md
  docs/source/resources/scyllaclusters/basics.md
  docs/source/resources/scyllaclusters/clients/cql.md
  docs/source/resources/scyllaclusters/clients/discovery.md
  docs/source/resources/scyllaclusters/nodeoperations/restore.md
  docs/source/resources/scylladbclusters/scylladbclusters.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/XL, approved, ok-to-test

#2833 Add support for `RetryWait` parameter in ScyllaDB Manager tasks' integration
  deploy/operator.yaml
  docs/source/api-reference/groups/scylla.scylladb.com/scyllaclusters.rst
  docs/source/api-reference/groups/scylla.scylladb.com/scylladbmanagertasks.rst
  helm/scylla-manager/values.schema.json
  helm/scylla/values.schema.json
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/types_cluster.go
  pkg/api/scylla/v1/zz_generated.deepcopy.go
  pkg/api/scylla/v1alpha1/scylla.scylladb.com_scylladbmanagertasks.yaml
  pkg/api/scylla/v1alpha1/types_scylladbmanagertask.go
  pkg/api/scylla/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/scyllacluster/migrate.go
  pkg/controller/scyllacluster/migrate_test.go
  pkg/controller/scylladbmanagertask/sync_manager.go
  pkg/controller/scylladbmanagertask/sync_manager_test.go
Labels: kind/feature, priority/important-soon, lgtm, size/XL, approved

#2844 Update scylla to 2025.1.5
  assets/config/config.yaml
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  examples/scylladb/scylla.scyllacluster.yaml
  helm/deploy/manager_prod.yaml
  helm/scylla-manager/values.yaml
  helm/scylla/values.yaml
Labels: priority/critical-urgent, lgtm, size/S, approved, kind/dependency-bump

#2845 [v1.18] Update ScyllaDB to 2025.1.5
  assets/config/config.yaml
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  examples/scylladb/scylla.scyllacluster.yaml
  helm/deploy/manager_prod.yaml
  helm/scylla-manager/values.yaml
  helm/scylla/values.yaml
Labels: priority/critical-urgent, lgtm, size/S, approved, kind/dependency-bump

#2839 Bump patch version of third-party haproxy-ingress example
  examples/third-party/haproxy-ingress.yaml
  examples/third-party/haproxy-ingress/10_clusterrole.yaml
  examples/third-party/haproxy-ingress/50_haproxy-ingress.deploy.yaml
Labels: priority/important-soon, kind/cleanup, lgtm, size/M, approved
