Repository scylladb/scylla-operator, pull requests merged in 2025-02, with the labels that each got.

#2355 Support configuring ScyllaDB and Scylla Manager versions for e2e tests with flags
  hack/.ci/lib/e2e.sh
  hack/ci-deploy-release.sh
  hack/ci-deploy.sh
  pkg/cmd/tests/options.go
  test/e2e/framework/framework.go
  test/e2e/framework/testcontext.go
  test/e2e/set/scyllacluster/scyllacluster_upgrades.go
Labels: priority/important-soon, kind/machinery, lgtm, size/L, approved, area/dependency

#2472 Update `externalapi/monitoring/v1` and prometheus-operator manifests to v0.80.0
  examples/third-party/prometheus-operator.yaml
  examples/third-party/prometheus-operator/00_monitoring.coreos.com_alertmanagerconfigs.crd.yaml
  examples/third-party/prometheus-operator/00_monitoring.coreos.com_alertmanagers.crd.yaml
  examples/third-party/prometheus-operator/00_monitoring.coreos.com_podmonitors.crd.yaml
  examples/third-party/prometheus-operator/00_monitoring.coreos.com_probes.crd.yaml
  examples/third-party/prometheus-operator/00_monitoring.coreos.com_prometheusagents.crd.yaml
  examples/third-party/prometheus-operator/00_monitoring.coreos.com_prometheuses.crd.yaml
  examples/third-party/prometheus-operator/00_monitoring.coreos.com_prometheusrules.crd.yaml
  examples/third-party/prometheus-operator/00_monitoring.coreos.com_scrapeconfigs.crd.yaml
  examples/third-party/prometheus-operator/00_monitoring.coreos.com_servicemonitors.crd.yaml
  examples/third-party/prometheus-operator/00_monitoring.coreos.com_thanosrulers.crd.yaml
  examples/third-party/prometheus-operator/10_operator.clusterrole.yaml
  examples/third-party/prometheus-operator/10_operator.clusterrolebinding.yaml
  examples/third-party/prometheus-operator/40_operator.sa.yaml
  examples/third-party/prometheus-operator/40_operator.service.yaml
  examples/third-party/prometheus-operator/50_operator.deployment.yaml
  pkg/externalapi/monitoring/v1/monitoring.coreos.com_alertmanagers.yaml
  pkg/externalapi/monitoring/v1/monitoring.coreos.com_podmonitors.yaml
  pkg/externalapi/monitoring/v1/monitoring.coreos.com_probes.yaml
  pkg/externalapi/monitoring/v1/monitoring.coreos.com_prometheuses.yaml
  pkg/externalapi/monitoring/v1/monitoring.coreos.com_prometheusrules.yaml
  pkg/externalapi/monitoring/v1/monitoring.coreos.com_servicemonitors.yaml
  pkg/externalapi/monitoring/v1/monitoring.coreos.com_thanosrulers.yaml
  pkg/externalapi/monitoring/v1/types.go
  pkg/externalapi/monitoring/v1/types_alertmanager.go
  pkg/externalapi/monitoring/v1/types_dns.go
  pkg/externalapi/monitoring/v1/types_podmonitor.go
  pkg/externalapi/monitoring/v1/types_probe.go
  pkg/externalapi/monitoring/v1/types_prometheus.go
  pkg/externalapi/monitoring/v1/types_prometheusrule.go
  pkg/externalapi/monitoring/v1/types_servicemonitor.go
  pkg/externalapi/monitoring/v1/types_thanos.go
  pkg/externalapi/monitoring/v1/zz_generated.deepcopy.go
  pkg/externalclient/monitoring/clientset/versioned/typed/monitoring/v1/alertmanager.go
  pkg/externalclient/monitoring/clientset/versioned/typed/monitoring/v1/fake/fake_alertmanager.go
  pkg/externalclient/monitoring/clientset/versioned/typed/monitoring/v1/fake/fake_prometheus.go
  pkg/externalclient/monitoring/clientset/versioned/typed/monitoring/v1/prometheus.go
Labels: priority/important-soon, kind/api-change, lgtm, size/XXL, approved

#2253 Add an e2e test for retryable NodeConfig mount units
  test/e2e/set/nodeconfig/nodeconfig_disksetup.go
Labels: kind/feature, priority/important-longterm, lgtm, size/L, approved

#2271 Add ScyllaDBCluster webhook validation
  deploy/operator.yaml
  deploy/operator/10_validatingwebhook.yaml
  helm/scylla-operator/templates/validatingwebhook.yaml
  pkg/api/scylla/validation/scylladbcluster_validation.go
  pkg/api/scylla/validation/scylladbcluster_validation_test.go
  pkg/api/scylla/validation/scylladbdatacenter_validation.go
  pkg/cmd/operator/webhooks.go
  pkg/thirdparty/k8s.io/kubernetes/pkg/apis/core/validation/export.go
  pkg/thirdparty/k8s.io/kubernetes/pkg/apis/core/validation/ref.txt
  pkg/thirdparty/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  test/e2e/set/scylladbcluster/scylladbcluster_webhook.go
Labels: kind/feature, priority/important-soon, lgtm, size/XXL, approved

#2485 Update docs theme 1.8.5
  docs/poetry.lock
  docs/source/index.md
  docs/source/logo.png
  docs/source/logo.svg
Labels: kind/documentation, priority/important-longterm, lgtm, size/L, approved, ok-to-test

#2484 Extend Rack spec with rack specific ExposeOptions
  deploy/operator.yaml
  docs/source/api-reference/groups/scylla.scylladb.com/scyllaclusters.rst
  docs/source/api-reference/groups/scylla.scylladb.com/scylladbclusters.rst
  docs/source/api-reference/groups/scylla.scylladb.com/scylladbdatacenters.rst
  helm/scylla-manager/values.schema.json
  helm/scylla/values.schema.json
  pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml
  pkg/api/scylla/v1/types_cluster.go
  pkg/api/scylla/v1/zz_generated.deepcopy.go
  pkg/api/scylla/v1alpha1/scylla.scylladb.com_scylladbclusters.yaml
  pkg/api/scylla/v1alpha1/scylla.scylladb.com_scylladbdatacenters.yaml
  pkg/api/scylla/v1alpha1/types_scylladbdatacenter.go
  pkg/api/scylla/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/scyllacluster/migrate.go
  pkg/controller/scylladbdatacenter/resource.go
  pkg/controller/scylladbdatacenter/resource_test.go
Labels: kind/feature, priority/important-soon, lgtm, size/XXL, approved

#2487 Reimplement `wait-for-object-creation` with `kubectl wait`
  hack/lib/kube.sh
Labels: kind/cleanup, priority/important-longterm, lgtm, size/XS, approved

#2486 Disable ScyllaDBMonitoring tests in OpenShift E2E
  hack/.ci/lib/e2e.sh
  hack/.ci/run-e2e-openshift-aws-release.sh
  hack/.ci/run-e2e-openshift-aws.sh
  test/e2e/set/scylladbmonitoring/scylladbmonitoring.go
Labels: priority/important-soon, kind/machinery, lgtm, size/S, approved

#2493 Use deterministic names for remote Namespace and RemoteOwner
  pkg/controller/scylladbcluster/resource.go
  pkg/controller/scylladbcluster/resource_test.go
  pkg/controller/scylladbcluster/sync_remoteowner.go
  pkg/naming/names.go
Labels: kind/bug, priority/important-soon, lgtm, size/L, approved

#2292 Extend ScyllaDBCluster controller with finalizer
  pkg/controller/scylladbcluster/conditions.go
  pkg/controller/scylladbcluster/sync.go
  pkg/controller/scylladbcluster/sync_finalizer.go
  pkg/naming/constants.go
  test/e2e/set/scylladbcluster/multidatacenter_scylladbcluster_finalizer.go
Labels: kind/feature, priority/important-soon, lgtm, size/L, approved

#2499 Fix dead links and make minor cleanups in documentation
  README.md
  RELEASE.md
  docs/README.md
  docs/source/quickstarts/eks.md
  docs/source/quickstarts/gke.md
  docs/source/resources/overview.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/M, approved

#2501 Build v1.16 documentation
  docs/source/conf.py
Labels: kind/documentation, needs-priority, lgtm, size/XS, approved

#2503 [v1.15] Fix dead links and make minor cleanups in documentation
  docs/source/quickstarts/eks.md
  docs/source/quickstarts/gke.md
  docs/source/resources/overview.md
Labels: kind/documentation, needs-priority, lgtm, size/S, approved

#2507 Bump `go.mod` deps
  go.mod
  go.sum
  vendor/github.com/emicklei/go-restful/v3/CHANGES.md
  vendor/github.com/emicklei/go-restful/v3/README.md
  vendor/github.com/emicklei/go-restful/v3/jsr311.go
  vendor/github.com/emicklei/go-restful/v3/route.go
  vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/default_value_decoders.go
  vendor/go.mongodb.org/mongo-driver/bson/unmarshal.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/modules.txt
Labels: kind/cleanup, needs-priority, lgtm, size/L, approved, area/dependency

#2505 Use alphanum characters in hashed name suffix
  pkg/controller/scylladbcluster/resource_test.go
  pkg/naming/names.go
  pkg/util/hash/hash.go
Labels: kind/bug, priority/important-soon, lgtm, size/M, approved

#2510 [1.14] Bump `go.mod` dependencies
  Dockerfile
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/unix/auxv.go
  vendor/golang.org/x/sys/unix/auxv_unsupported.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/modules.txt
Labels: kind/cleanup, needs-priority, lgtm, size/XL, approved, area/dependency

#2506 [v1.16] Use alphanum characters in hashed name suffix
  pkg/controller/scylladbcluster/resource_test.go
  pkg/naming/names.go
  pkg/util/hash/hash.go
Labels: kind/bug, priority/important-soon, lgtm, size/M, approved

#2511 [1.15] Bump `go.mod` dependencies
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/unix/auxv.go
  vendor/golang.org/x/sys/unix/auxv_unsupported.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/modules.txt
Labels: kind/cleanup, needs-priority, lgtm, size/XL, approved, area/dependency

#2514 Bump upload-artifact to v4 in GH Actions
  .github/actions/release-notes/action.yaml
Labels: priority/important-soon, kind/cleanup, lgtm, size/XS, approved

#2515 [1.16] Bump upload-artifact to v4 in GH Actions
  .github/actions/release-notes/action.yaml
Labels: priority/important-soon, kind/cleanup, lgtm, size/XS, approved

#2518 Fix pull request template contribution link
  .github/pull_request_template.md
Labels: kind/documentation, needs-priority, lgtm, size/XS, approved
