Repository scylladb/scylla-operator, pull requests merged in 2025-08, with the labels that each got.

#2834 Explicitly set and unify the number of retries and backoff duration in ScyllaDB Manager tasks in E2E tests
  test/e2e/set/scyllacluster/scyllamanager.go
  test/e2e/set/scyllacluster/scyllamanager_object_storage.go
  test/e2e/set/scylladbmanagertask/multidatacenter/scylladbmanagertask_scylladbcluster_globalmanager.go
  test/e2e/set/scylladbmanagertask/multidatacenter/scylladbmanagertask_scylladbcluster_globalmanager_object_storage.go
  test/e2e/set/scylladbmanagertask/scylladbmanagertask_scylladbdatacenter_globalmanager_object_storage.go
  test/e2e/set/scylladbmanagertask/scylladbmanagertask_scylladbdataceter_globalmanager.go
  test/e2e/utils/config.go
Labels: priority/important-soon, kind/flake, lgtm, size/M, approved

#2877 Introduce an enhancement proposal for extending NodeConfig with sysctl configuration
  enhancements/proposals/2457-nodeconfig-sysctls/README.md
Labels: priority/important-soon, kind/design, lgtm, size/L, approved

#2889 [v1.18] Fix docs issues found in testing
  Makefile
  docs/source/installation/gitops.md
  docs/source/installation/helm.md
  docs/source/quickstarts/eks.md
  docs/source/resources/scyllaclusters/basics.md
  docs/source/resources/scyllaclusters/multidc/multidc.md
  docs/source/resources/scyllaclusters/nodeoperations/restore.md
  docs/source/resources/scylladbclusters/scylladbclusters.md
  examples/helm/values.cluster.yaml
  examples/helm/values.manager.yaml
  examples/helm/values.operator.yaml
Labels: priority/important-soon, kind/documentation, lgtm, size/XL, approved

#2903 [v1.18] Update supported Kubernetes versions
  docs/source/support/releases.md
Labels: priority/important-soon, kind/documentation, lgtm, size/XS, approved

#2904 [v1.17] Update supported Kubernetes versions
  docs/source/support/releases.md
Labels: priority/important-soon, kind/documentation, lgtm, size/XS, approved

#2909 Add ScyllaDBMonitoring external Prometheus support enhancement proposal
  enhancements/proposals/2490-scylladbmonitoring-external-prometheus/README.md
Labels: priority/important-soon, kind/documentation, lgtm, size/XL, approved
