Repository scylladb/scylla-operator, pull requests merged in 2025-03, with the labels that each got.

#2526 Add `.generated_files` to make the `size` prow plugin accurate
  .generated_files
Labels: priority/backlog, kind/machinery, lgtm, size/M, approved

#2531 Update the documentation for 1.16
  docs/source/conf.py
  docs/source/support/releases.md
Labels: priority/important-soon, kind/documentation, lgtm, size/M, approved

#2532 [1.16] Update the documentation for 1.16
  docs/source/conf.py
  docs/source/support/releases.md
Labels: priority/important-soon, kind/documentation, lgtm, size/S, approved, area/dependency

#2528 Clear data keyspace snapshots for first node in rack during ScyllaDB version upgrade
  pkg/controller/scylladbdatacenter/sync_statefulsets.go
  pkg/scyllaclient/client.go
  test/e2e/set/scyllacluster/scyllacluster_upgrades.go
Labels: kind/bug, priority/important-soon, lgtm, size/M, approved

#2534 [v1.16] Clear data keyspace snapshots for first node in rack during ScyllaDB version upgrade
  pkg/controller/scylladbdatacenter/sync_statefulsets.go
  pkg/scyllaclient/client.go
  test/e2e/set/scyllacluster/scyllacluster_upgrades.go
Labels: kind/bug, priority/important-soon, lgtm, size/M, approved

#2539 [1.15] Bump upload-artifact to v4 in GH Actions
  .github/actions/release-notes/action.yaml
Labels: priority/important-soon, kind/cleanup, lgtm, size/XS, approved

#2540 Change retries of e2e artifact collection
  hack/.ci/lib/e2e.sh
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#2360 Make RSA key size configurable in operator command
  pkg/cmd/operator/operator.go
  pkg/crypto/certcreators_test.go
  pkg/crypto/config.go
  pkg/crypto/keygenerator.go
  pkg/kubecrypto/certs_test.go
Labels: priority/important-soon, kind/machinery, lgtm, size/S, approved

#2543 Fix flaky e2e test by zeroing XFS log before checking filesystem integrity
  test/e2e/set/nodeconfig/nodeconfig_disksetup.go
Labels: priority/important-soon, kind/flake, lgtm, size/XS, approved

#2474 Make RSA key size configurable in CI scripts and use 2048 bits in E2E CI jobs by default
  hack/.ci/run-e2e-shared.env.sh
  hack/ci-deploy-release.sh
  hack/ci-deploy.sh
Labels: priority/important-soon, kind/machinery, lgtm, size/S, approved

#2545 Propagate Options in DataInserter constructor in E2E utils
  test/e2e/utils/datainserter.go
Labels: kind/bug, priority/important-longterm, lgtm, size/XS, approved

#2480 Update Go to 1.24
  Dockerfile
  go.mod
  pkg/dependencymagnet/doc.go
  test/e2e/framework/cleanup.go
  test/e2e/framework/util.go
  test/e2e/set/scyllacluster/scyllamanager.go
  test/e2e/set/scyllacluster/scyllamanager_object_storage.go
Labels: priority/important-longterm, kind/machinery, lgtm, size/M, approved, area/dependency

#2541 Graceful e2e shutdown on timeout
  hack/.ci/lib/e2e.sh
  hack/.ci/run-e2e-gke-release.sh
  hack/.ci/run-e2e-gke.sh
  hack/.ci/run-e2e-openshift-aws-release.sh
  hack/.ci/run-e2e-openshift-aws.sh
  hack/lib/kube.sh
Labels: priority/important-soon, kind/machinery, lgtm, size/S, approved

#2546 Fix signal sent to e2e Pod on graceful shutdown
  hack/.ci/lib/e2e.sh
Labels: priority/important-soon, kind/machinery, lgtm, approved

#2556 Render `.spec.datacenter.racks` directly in Helm template
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  helm/scylla/templates/scyllacluster.yaml
Labels: kind/bug, priority/important-soon, lgtm, size/L, approved

#2555 [1.16] Propagate racks.exposeOptions in Helm
  helm/scylla/templates/scyllacluster.yaml
Labels: kind/feature, priority/important-soon, lgtm, size/XS, approved, area/dependency

#2557 Update local-csi-driver to 0.5.0
  examples/common/local-volume-provisioner/local-csi-driver/50_daemonset.yaml
  hack/.ci/manifests/namespaces/local-csi-driver/50_daemonset.yaml
Labels: kind/cleanup, priority/important-longterm, lgtm, size/XS, approved

#2565 Update default storage capacity to 120Gi and set sysctls' fs.aio-max-nr value to 30000000 in Scylla helm chart
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_scyllacluster.yaml
  deploy/manager/prod/50_scyllacluster.yaml
  helm/scylla/values.yaml
Labels: kind/bug, priority/important-soon, lgtm, size/XS, approved
