Repository scylladb/scylla-operator, pull requests merged in 2025-05, with the labels that each got.

#2535 Reconcile remote datacenters independently
  pkg/controller/scylladbcluster/conditions.go
  pkg/controller/scylladbcluster/conditions_test.go
  pkg/controller/scylladbcluster/resource.go
  pkg/controller/scylladbcluster/resource_test.go
  pkg/controller/scylladbcluster/sync.go
  pkg/controller/scylladbcluster/sync_configmap.go
  pkg/controller/scylladbcluster/sync_endpoints.go
  pkg/controller/scylladbcluster/sync_endpointslices.go
  pkg/controller/scylladbcluster/sync_namespace.go
  pkg/controller/scylladbcluster/sync_remoteowner.go
  pkg/controller/scylladbcluster/sync_scylladbdatacenter.go
  pkg/controller/scylladbcluster/sync_secrets.go
  pkg/controller/scylladbcluster/sync_service.go
  pkg/controllerhelpers/sync.go
  pkg/internalapi/conditions.go
  pkg/internalapi/conditions_test.go
  pkg/naming/labels.go
  test/e2e/fixture/scylla/registry.go
  test/e2e/fixture/scylla/unauthorized.kubeconfig.yaml
  test/e2e/set/scylladbcluster/multidatacenter/scylladbcluster_fault_tolerance.go
  test/e2e/utils/helpers.go
  test/e2e/utils/v1alpha1/helpers.go
  test/e2e/utils/verification/scylladbcluster/verify.go
Labels: kind/feature, priority/important-soon, lgtm, size/XXL, approved

#2628 Build v1.17 documentation
  docs/source/conf.py
Labels: priority/important-soon, kind/documentation, lgtm, size/XS, approved

#2625 Fix GitOps local-csi-driver installation command
  docs/source/installation/gitops.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved

#2629 [v1.16] Fix GitOps local-csi-driver installation command
  docs/source/installation/gitops.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved

#2630 [v1.17] Fix GitOps local-csi-driver installation command
  docs/source/installation/gitops.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved

#2631 [v1.16] Remove redundant wait for webhook CA secret in docs' GitOps installation steps
  docs/source/installation/gitops.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/S, approved

#2627 [v1.17] Pin the 1.17 tag
  Makefile
  deploy/manager-dev.yaml
  deploy/manager-prod.yaml
  deploy/manager/dev/50_controller_deployment.yaml
  deploy/manager/prod/50_controller_deployment.yaml
  deploy/operator.yaml
  deploy/operator/50_operator.deployment.yaml
  deploy/operator/50_webhookserver.deployment.yaml
  helm/scylla-manager/Chart.yaml
  helm/scylla-operator/Chart.yaml
Labels: priority/important-soon, kind/cleanup, lgtm, size/S, approved

#2636 Add documentation and examples for automated multi-dc
  docs/source/.internal/scylladbcluster-cluster-ip-exposure-caution.md
  docs/source/resources/common/exposing-images/clusterip.svg
  docs/source/resources/common/exposing-images/loadbalancer.svg
  docs/source/resources/common/exposing-images/multivpc.svg
  docs/source/resources/common/exposing-images/podips.svg
  docs/source/resources/common/exposing.md
  docs/source/resources/common/multidc/eks.md
  docs/source/resources/common/multidc/gke.md
  docs/source/resources/index.md
  docs/source/resources/overview.md
  docs/source/resources/remotekubernetesclusters.md
  docs/source/resources/remotekubernetesclusters.svg
  docs/source/resources/scyllaclusters/basics.md
  docs/source/resources/scyllaclusters/clients/discovery.md
  docs/source/resources/scyllaclusters/index.md
  docs/source/resources/scyllaclusters/multidc/index.md
  docs/source/resources/scyllaclusters/multidc/multidc.md
  docs/source/resources/scylladbclusters/index.md
  docs/source/resources/scylladbclusters/scylladbcluster.svg
  docs/source/resources/scylladbclusters/scylladbclusters.md
  examples/multi-dc/cluster-wide-resources/00_dev-us-central-1.remotekubernetescluster.yaml
  examples/multi-dc/cluster-wide-resources/00_dev-us-east-1.remotekubernetescluster.yaml
  examples/multi-dc/cluster-wide-resources/00_dev-us-west-1.remotekubernetescluster.yaml
  examples/multi-dc/namespaces/remotekubernetescluster-credentials/00_namespace.yaml
  examples/multi-dc/namespaces/remotekubernetescluster-credentials/10_dev-us-central-1.secret.yaml
  examples/multi-dc/namespaces/remotekubernetescluster-credentials/10_dev-us-east-1.secret.yaml
  examples/multi-dc/namespaces/remotekubernetescluster-credentials/10_dev-us-west-1.secret.yaml
  examples/multi-dc/namespaces/scylla/00_namespace.yaml
  examples/multi-dc/namespaces/scylla/10_scylladbcluster.yaml
Labels: priority/important-soon, kind/documentation, lgtm, size/XL, approved

#2637 [v1.17] Add documentation and examples for automated multi-dc
  docs/source/.internal/scylladbcluster-cluster-ip-exposure-caution.md
  docs/source/resources/common/exposing-images/clusterip.svg
  docs/source/resources/common/exposing-images/loadbalancer.svg
  docs/source/resources/common/exposing-images/multivpc.svg
  docs/source/resources/common/exposing-images/podips.svg
  docs/source/resources/common/exposing.md
  docs/source/resources/common/multidc/eks.md
  docs/source/resources/common/multidc/gke.md
  docs/source/resources/index.md
  docs/source/resources/overview.md
  docs/source/resources/remotekubernetesclusters.md
  docs/source/resources/remotekubernetesclusters.svg
  docs/source/resources/scyllaclusters/basics.md
  docs/source/resources/scyllaclusters/clients/discovery.md
  docs/source/resources/scyllaclusters/index.md
  docs/source/resources/scyllaclusters/multidc/index.md
  docs/source/resources/scyllaclusters/multidc/multidc.md
  docs/source/resources/scylladbclusters/index.md
  docs/source/resources/scylladbclusters/scylladbcluster.svg
  docs/source/resources/scylladbclusters/scylladbclusters.md
  examples/multi-dc/cluster-wide-resources/00_dev-us-central-1.remotekubernetescluster.yaml
  examples/multi-dc/cluster-wide-resources/00_dev-us-east-1.remotekubernetescluster.yaml
  examples/multi-dc/cluster-wide-resources/00_dev-us-west-1.remotekubernetescluster.yaml
  examples/multi-dc/namespaces/remotekubernetescluster-credentials/00_namespace.yaml
  examples/multi-dc/namespaces/remotekubernetescluster-credentials/10_dev-us-central-1.secret.yaml
  examples/multi-dc/namespaces/remotekubernetescluster-credentials/10_dev-us-east-1.secret.yaml
  examples/multi-dc/namespaces/remotekubernetescluster-credentials/10_dev-us-west-1.secret.yaml
  examples/multi-dc/namespaces/scylla/00_namespace.yaml
  examples/multi-dc/namespaces/scylla/10_scylladbcluster.yaml
Labels: priority/important-soon, kind/documentation, lgtm, size/XL, approved

#2638 Mark 1.17 docs as stable
  docs/source/conf.py
Labels: priority/important-soon, kind/documentation, lgtm, size/XS, approved

#2640 Add the 1.17 release and the 1.18 plans
  docs/source/support/releases.md
Labels: priority/important-soon, kind/documentation, lgtm, size/S, approved

#2635 Fix potential aggregated conditions' msg and reason overflow
  pkg/controllerhelpers/core.go
  pkg/controllerhelpers/core_test.go
Labels: kind/bug, priority/important-longterm, lgtm, size/L, approved

#2634 Collect StorageClass objects into must-gather archive
  pkg/cmd/operator/mustgather.go
  pkg/cmd/operator/mustgather_test.go
Labels: kind/feature, priority/important-longterm, lgtm, size/M, approved

#2643 Rename generic NodeConfig to match docs expectations
  examples/generic/nodeconfig-alpha.yaml
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved

#2645 Deduplicate ScyllaDBDatacenter resource test cases for MakeManagedScyllaDBConfig function
  pkg/controller/scylladbdatacenter/resource_test.go
Labels: priority/important-soon, kind/cleanup, lgtm, size/L, approved

#2657 Fix JUnit and JSON report setup for Ginkgo in test runner
  pkg/cmd/tests/options.go
  pkg/cmd/tests/tests_run.go
Labels: kind/bug, priority/important-longterm, lgtm, size/S, approved

#2660 Merge the Dependabot schedules
  .github/dependabot.yml
Labels: priority/important-longterm, kind/machinery, lgtm, size/XS, approved

#2578 Change the source of the ScyllaDBVersion parameter value in replace e2e
  test/e2e/set/scyllacluster/scyllacluster_replace.go
Labels: priority/important-soon, kind/cleanup, lgtm, size/XS, approved

#2658 Make E2E suite timeout configurable through an env variable
  hack/.ci/lib/e2e.sh
Labels: priority/important-longterm, kind/machinery, lgtm, size/XS, approved
