Repository scylladb/scylla-operator, pull requests merged in 2025-06, with the labels that each got.

#2652 Add minimal golangci-lint config and fix found issues
  .golangci.yaml
  CONTRIBUTING.md
  Makefile
  pkg/auth/auth_test.go
  pkg/cmd/operator/sidecar.go
  pkg/cmd/tests/tests.go
  pkg/controller/nodeconfig/controller.go
  pkg/controller/nodetune/controller.go
  pkg/controller/nodetune/sync.go
  pkg/controller/nodetune/tune.go
  pkg/controller/remotekubernetescluster/controller.go
  pkg/controller/scylladbcluster/controller.go
  pkg/kubelet/podresourcesclient.go
  pkg/resource/helpers.go
  pkg/scyllaclient/client_ping.go
  pkg/sidecar/config/config.go
  pkg/sidecar/config/config_test.go
  pkg/util/blkutils/lsblk_test.go
  test/e2e/set/scyllacluster/config.go
  test/e2e/set/scylladbcluster/multidatacenter/config.go
  test/e2e/utils/clusters.go
  test/e2e/utils/config.go
  test/e2e/utils/verification/scylladbcluster/cql.go
Labels: kind/cleanup, priority/important-longterm, lgtm, size/L, approved

#2667 Move RemoteKubernetesCluster Secret to dedicated namespace in ScyllaDBCluster webhook e2e
  test/e2e/set/scylladbcluster/scylladbcluster_webhook.go
Labels: priority/important-soon, kind/flake, lgtm, size/S, approved

#2678 Fix redirect loop in docs
  docs/_utils/redirects.yaml
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved

#2672 Fix NonRetriableError matching
  pkg/controller/scylladbmanagerclusterregistration/controller.go
  pkg/controllertools/errors.go
  pkg/controllertools/errors_test.go
  pkg/controllertools/observer.go
Labels: kind/bug, priority/important-soon, lgtm, size/L, approved

#2680 Remove linter from Makefile's update target
  CONTRIBUTING.md
  Makefile
Labels: priority/important-soon, kind/cleanup, lgtm, size/S, approved

#2684 Fix ID propagation to ScyllaDBClusterRegistration's status
  pkg/controller/scylladbmanagerclusterregistration/sync.go
  pkg/controller/scylladbmanagerclusterregistration/sync_manager.go
Labels: kind/bug, priority/important-soon, lgtm, size/S, approved

#2691 Remove required reviewers from OWNERS' dependency filter
  OWNERS
Labels: kind/cleanup, priority/important-longterm, lgtm, size/XS, approved

#2694 Fix ScyllaDB Manager task adoption in case of missing owner UID label
  pkg/controller/scylladbmanagertask/sync_manager.go
  pkg/naming/constants.go
Labels: kind/bug, priority/important-soon, lgtm, size/S, approved

#2702 Revert "Migrate rate limiting queue to typed version"
  pkg/controller/manager/controller.go
  pkg/controller/manager/sync.go
  pkg/controller/nodeconfig/controller.go
  pkg/controller/nodeconfig/sync.go
  pkg/controller/nodeconfigpod/controller.go
  pkg/controller/nodeconfigpod/sync.go
  pkg/controller/nodesetup/controller.go
  pkg/controller/nodetune/controller.go
  pkg/controller/orphanedpv/controller.go
  pkg/controller/orphanedpv/sync.go
  pkg/controller/remotekubernetescluster/controller.go
  pkg/controller/remotekubernetescluster/sync.go
  pkg/controller/remotekubernetescluster/sync_healthchecks.go
  pkg/controller/scyllacluster/controller.go
  pkg/controller/scyllacluster/sync.go
  pkg/controller/scylladbcluster/controller.go
  pkg/controller/scylladbcluster/sync.go
  pkg/controller/scylladbdatacenter/controller.go
  pkg/controller/scylladbdatacenter/sync.go
  pkg/controller/scylladbdatacenter/sync_statefulsets.go
  pkg/controller/scylladbmanagerclusterregistration/controller.go
  pkg/controller/scylladbmanagerclusterregistration/sync.go
  pkg/controller/scylladbmanagertask/controller.go
  pkg/controller/scylladbmanagertask/sync.go
  pkg/controller/scylladbmonitoring/controller.go
  pkg/controller/scylladbmonitoring/sync.go
  pkg/controller/scyllaoperatorconfig/controller.go
  pkg/controller/sidecar/controller.go
  pkg/controllerhelpers/handlers.go
  pkg/controllertools/observer.go
Labels: kind/bug, priority/important-soon, lgtm, size/L, approved

#2708 Omit empty value for switch parameters
  pkg/sidecar/config/config.go
  pkg/sidecar/config/config_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/L, approved

#2713 [v1.16] Omit empty value for switch parameters
  pkg/sidecar/config/config.go
  pkg/sidecar/config/config_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/L, approved

#2720 [v1.17] Use advertised Scylla addresses on cleanup Jobs
  pkg/api/scylla/v1alpha1/types_scylladbdatacenter.go
  pkg/controller/scylladbdatacenter/resource.go
  pkg/controller/scylladbdatacenter/resource_test.go
  pkg/controller/scylladbdatacenter/sync_jobs.go
  pkg/controllerhelpers/scylla.go
Labels: kind/bug, priority/important-soon, lgtm, size/XL, approved

#2714 [v1.17] Omit empty value for switch parameters
  pkg/sidecar/config/config.go
  pkg/sidecar/config/config_test.go
Labels: kind/bug, priority/important-soon, lgtm, size/L, approved

#2698 [1.16] Bump `github.com/cloudflare/circl` to 1.16
  go.mod
  go.sum
  vendor/github.com/cloudflare/circl/ecc/goldilocks/curve.go
  vendor/github.com/cloudflare/circl/sign/ed25519/point.go
  vendor/modules.txt
Labels: kind/cleanup, priority/important-longterm, lgtm, size/S, approved, area/dependency

#2729 Use ignition container to validate sysctls in e2e
  test/e2e/set/scyllacluster/scyllacluster_sysctl.go
Labels: priority/important-soon, kind/cleanup, lgtm, size/XS, approved
