Repository scylladb/scylla-operator, pull requests merged in 2025-01, with the labels that each got.

#2295 Remove tnozicka from OWNERS
  OWNERS
Labels: priority/important-soon, kind/cleanup, lgtm, size/XS, approved

#2299 Fix default Local CSI Driver manifest paths in CI deploy release script
  hack/ci-deploy-release.sh
Labels: kind/bug, priority/critical-urgent, lgtm, size/XS, approved

#2302 Update release schedule
  docs/source/support/releases.md
Labels: priority/important-soon, kind/documentation, lgtm, size/S, approved

#2298 Add a dedicated CI script to run E2Es with published releases on OpenShift on AWS
  hack/.ci/run-e2e-openshift-aws-release.sh
Labels: priority/important-soon, kind/machinery, lgtm, size/M, approved

#2307 Add `mflendrich` to `OWNERS`
  OWNERS
Labels: priority/important-soon, kind/cleanup, lgtm, size/XS, approved

#2309 Fix disk setup e2e assertion
  test/e2e/set/nodeconfig/nodeconfig_disksetup.go
Labels: priority/important-soon, kind/failing-test, lgtm, size/M, approved

#2313 Sync CI Openshift NodeConfig NVMe disks discovery with AWS
  hack/.ci/manifests/cluster/nodeconfig-openshift-aws.yaml
Labels: priority/important-soon, kind/cleanup, lgtm, size/XS, approved

#2297 Move overriding Scylla Operator's log level to CI scripts and make it configurable
  hack/.ci/lib/e2e.sh
  hack/ci-deploy-release.sh
  hack/ci-deploy.sh
Labels: priority/important-soon, kind/machinery, lgtm, size/M, approved

#2276 Make Scylla Operator resources configurable in CI scripts
  hack/.ci/run-e2e-gke-release.sh
  hack/.ci/run-e2e-gke.sh
  hack/.ci/run-e2e-openshift-aws-release.sh
  hack/.ci/run-e2e-openshift-aws.sh
  hack/.ci/run-e2e-shared.env.sh
  hack/ci-deploy-release.sh
  hack/ci-deploy.sh
Labels: priority/important-soon, kind/machinery, lgtm, size/L, approved

#2315 Clean up `ScyllaCluster` GET `ClusterRole`
  deploy/operator.yaml
  deploy/operator/00_scyllacluster_member_clusterrole_def.yaml
  helm/scylla-operator/templates/scyllacluster_member_clusterrole_def.yaml
Labels: priority/important-soon, kind/cleanup, lgtm, size/S, approved

#2293 Fix quickstart links
  README.md
Labels: priority/important-soon, kind/cleanup, lgtm, size/S, approved

#2130 Update contribution guide
  CONTRIBUTING.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/M, approved

#2339 Fix the reference to contributing guide in README
  README.md
Labels: priority/important-soon, kind/cleanup, lgtm, size/XS, approved

#2312 Adjust key buffer sizes in CI based on parallelism
  hack/.ci/run-e2e-shared.env.sh
  hack/ci-deploy-release.sh
  hack/ci-deploy.sh
Labels: priority/important-soon, kind/machinery, lgtm, size/M, approved

#2231 Move snitch config generation to Operator
  assets/scylladb/registry.go
  assets/scylladb/snitchconfig.cm.yaml
  pkg/controller/scylladbdatacenter/resource.go
  pkg/controller/scylladbdatacenter/resource_test.go
  pkg/controller/scylladbdatacenter/sync_config.go
  pkg/naming/constants.go
  pkg/naming/names.go
  pkg/sidecar/config/config.go
  pkg/sidecar/config/config_test.go
Labels: kind/feature, priority/important-soon, lgtm, size/XL, approved

#2272 Add RemoteKubernetesCluster finalizer
  pkg/cmd/operator/operator.go
  pkg/controller/remotekubernetescluster/conditions.go
  pkg/controller/remotekubernetescluster/controller.go
  pkg/controller/remotekubernetescluster/sync.go
  pkg/controller/remotekubernetescluster/sync_finalizer.go
  pkg/controllerhelpers/finalizers.go
  pkg/controllerhelpers/finalizers_test.go
  pkg/naming/constants.go
  test/e2e/set/remotekubernetescluster/config.go
  test/e2e/set/remotekubernetescluster/remotekubernetescluster_finalizer.go
Labels: kind/feature, priority/important-soon, lgtm, size/XL, approved

#2356 Add rzetelskik to approvers
  OWNERS
  OWNERS_ALIASES
Labels: priority/important-longterm, kind/machinery, lgtm, size/S, approved

#2357 Add a NodeConfig manifest for CI jobs on GKE on arm64
  hack/.ci/manifests/cluster/nodeconfig-gke-arm64.yaml
Labels: priority/important-soon, kind/failing-test, lgtm, size/S, approved
