Repository scylladb/scylla-operator, pull requests merged in 2025-04, with the labels that each got.

#2573 Update release 1.17 date
  docs/source/support/releases.md
Labels: kind/cleanup, needs-priority, lgtm, size/XS, approved

#2574 [1.16] Update release 1.17 date
  docs/source/support/releases.md
Labels: kind/cleanup, needs-priority, lgtm, size/XS, approved

#2569 Remove redundant wait for webhook CA secret in docs' GitOps installation steps
  docs/source/installation/gitops.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/S, approved

#2524 Mirror ConfigMaps and Secrets referenced in ScyllaDBCluster into remote datacenters
  deploy/operator.yaml
  deploy/operator/00_operator_remote.clusterrole_def.yaml
  helm/scylla-operator/templates/operator_remote.clusterrole_def.yaml
  pkg/cmd/operator/operator.go
  pkg/controller/scylladbcluster/conditions.go
  pkg/controller/scylladbcluster/controller.go
  pkg/controller/scylladbcluster/resource.go
  pkg/controller/scylladbcluster/resource_test.go
  pkg/controller/scylladbcluster/sync.go
  pkg/controller/scylladbcluster/sync_configmap.go
  pkg/controller/scylladbcluster/sync_secrets.go
  pkg/naming/constants.go
  pkg/naming/labels.go
  pkg/scyllaclient/config_client.go
  test/e2e/set/scylladbcluster/multidatacenter/multidatacenter_scylladbcluster_config.go
  test/e2e/utils/verification/scylladbcluster/verify.go
Labels: kind/feature, priority/important-soon, lgtm, size/XL, approved

#2583 Add dependency update step to release procedure
  RELEASE.md
Labels: priority/important-longterm, kind/machinery, lgtm, size/S, approved

#2584 Remove `:link:` option from sphinx-design cards
  docs/source/_static/fix-cards.js
  docs/source/conf.py
  docs/source/index.md
  docs/source/resources/overview.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/M, approved, ok-to-test

#2585 Update docs theme to 1.8.6
  docs/poetry.lock
Labels: kind/documentation, priority/important-longterm, lgtm, size/L, approved, ok-to-test

#2587 [v1.16] Remove `:link:` option from sphinx-design cards
  docs/source/_static/fix-cards.js
  docs/source/conf.py
  docs/source/index.md
  docs/source/resources/overview.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/M, approved

#2588 [v1.15] Remove `:link:` option from sphinx-design cards
  docs/source/_static/fix-cards.js
  docs/source/conf.py
  docs/source/index.md
  docs/source/resources/overview.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/M, approved

#2582 Align naming of Multidatacenter Config Sync E2E
  test/e2e/set/scylladbcluster/multidatacenter/scylladbcluster_config.go
Labels: kind/cleanup, priority/important-longterm, lgtm, size/XS, approved

#2581 Remove Type prefix for aggregated Condition Reasons
  pkg/controllerhelpers/core.go
  pkg/controllerhelpers/core_test.go
  test/e2e/set/remotekubernetescluster/remotekubernetescluster_finalizer.go
Labels: kind/feature, priority/important-soon, lgtm, size/S, approved

#2589 Forget keys on nonretriable errors in observer
  pkg/controllertools/observer.go
Labels: kind/bug, priority/important-longterm, lgtm, size/XS, approved

#2592 Introduce Dependabot to bump go.mod & vendored packages
  .github/dependabot.yml
Labels: priority/important-longterm, kind/machinery, lgtm, size/S, approved

#2593 Fix `vendor` syntax in the dependabot config
  .github/dependabot.yml
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#2594 Remove the explicit `vendor` setting from the dependabot config
  .github/dependabot.yml
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#2599 Fix Available Condition of RemoteKubernetesCluster after recovery
  pkg/controller/remotekubernetescluster/sync_healthchecks.go
  test/e2e/set/remotekubernetescluster/remotekubernetescluster_healthcheck.go
Labels: kind/bug, priority/important-soon, lgtm, size/M, approved

#2601 Update restore from backup documentation page
  docs/source/resources/scyllaclusters/nodeoperations/restore.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved

#2600 Register collection of remote Namespaces originating from ScyllaDBCluster during E2E tests
  test/e2e/framework/cleanup.go
  test/e2e/framework/cluster.go
  test/e2e/framework/framework.go
  test/e2e/set/scylladbcluster/multidatacenter/scylladbcluster_boostrap.go
  test/e2e/set/scylladbcluster/multidatacenter/scylladbcluster_config.go
  test/e2e/set/scylladbcluster/multidatacenter/scylladbcluster_finalizer.go
  test/e2e/utils/clusters.go
Labels: priority/important-soon, kind/cleanup, lgtm, size/L, approved

#2605 Fix GH issues references in code to point to OS repo
  pkg/controller/scylladbcluster/resource.go
  pkg/controller/scylladbcluster/sync_scylladbdatacenter.go
Labels: kind/cleanup, priority/important-longterm, lgtm, size/S, approved

#2608 Update docs dependencies
  docs/poetry.lock
Labels: kind/documentation, priority/important-longterm, lgtm, size/M, approved, ok-to-test

#2612 [v1.16] Update restore from backup documentation page
  docs/source/resources/scyllaclusters/nodeoperations/restore.md
Labels: priority/important-soon, kind/documentation, lgtm, size/XS, approved

#2613 Fix md redirections for multiversion support (docs)
  docs/source/conf.py
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved, ok-to-test
