Repository scylladb/scylla-operator, pull requests merged in 2025-09, with the labels that each got.

#2925 Add operator-sdk dependency to contributing guide
  CONTRIBUTING.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/XS, approved, area/dependency

#2936 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: priority/important-soon, kind/machinery, lgtm, size/XS, approved

#2938 [v1.18] Handle missing xfsprogs on GKE >= 1.32
  docs/source/.internal/gke-1-32-xfsprogs.md
  docs/source/architecture/tuning.md
  docs/source/installation/gitops.md
  docs/source/installation/index.md
  docs/source/installation/kubernetes-prerequisites.md
  docs/source/installation/kubernetes/eks.md
  docs/source/installation/kubernetes/generic.md
  docs/source/installation/kubernetes/gke.md
  docs/source/installation/kubernetes/index.md
  docs/source/quickstarts/gke.md
  examples/gke/install-xfsprogs.daemonset.yaml
Labels: priority/important-soon, kind/documentation, lgtm, size/L, approved

#2939 Add sysctl configuration guide to documentation
  docs/source/.internal/wait-for-status-conditions.nodeconfig.code-block.md
  docs/source/conf.py
  docs/source/management/index.md
  docs/source/management/sysctls.md
  docs/source/resources/nodeconfigs.md
  examples/common/configure-sysctls.nodeconfig.yaml
Labels: priority/important-soon, kind/documentation, lgtm, size/M, approved

#2960 Update documentation theme to 1.8.8
  docs/poetry.lock
Labels: kind/documentation, priority/important-longterm, lgtm, size/L, approved, ok-to-test

#2971 Link to up-to-date release procedures in RELEASE.md
  RELEASE.md
Labels: kind/documentation, priority/important-longterm, lgtm, size/L, approved

#2973 Add mflendrich to review autoassignees
  OWNERS_ALIASES
Labels: kind/cleanup, priority/important-longterm, lgtm, size/XS, approved

#2977 Refactor ScyllaDBMonitoring E2E suite
  test/e2e/set/scylladbmonitoring/scylladbmonitoring.go
Labels: priority/important-soon, kind/cleanup, lgtm, size/XL, approved
